### ISSUE TITLE
Not support alias

### ISSUE THREAD

**Issue by dozer47528** [rofl0r/proxychains-ng#101]
I have an alias like `bubo='brew update && brew outdated'`

when I use proxychain4 to execute the alise: `proxychains4 bubo`

It did not works well.

`proxychains can't load process....: No such file or directory`

**Comment by rofl0r** [comment]
yes, that's by design: proxychains isn't a shell plugin.
but you can easily add a new alias that does what you want, i.e. ```pbubo=proxychains4 brew update && proxychains4 brew outdated'```

**Comment by dozer47528** [comment]
@rofl0r 
Thanks

**Comment by Rabbit52** [comment]
is there any possible add this in future :smiley:
