### ISSUE TITLE
Steam Mint 64

### ISSUE THREAD

**Issue by alexgv99** [rofl0r/proxychains-ng#102]
I can't run Steam on my Mint 64. I'm behind a socks5 proxy with no authentication needed. My conf file is the default one. I just commented the last line and added the following one: 

`socks5  200.169.16.19   3128`

When I try

`proxychains4 steam`

> ERROR: ld.so: object '/usr/lib/libproxychains4.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

and then other errors follow this one...

Any useful tip?

Thanks.

**Comment by vikerian** [comment]
Hi,
~# find /usr/ -name libproxychains4.so -type f
~# ln -s <founded path> /usr/lib/libproxychains4.so
Viker

On 01/04/2016 01:16 PM, Alex Gouvea Vasconcelos wrote:
>
> I can't run Steam on my Mint 64. I'm behind a socks5 proxy with no
> authentication needed. My conf file is the default one. I just
> commented the last line and added the following one:
>
> |socks5 200.169.16.19 3128|
>
> When I try
>
> |proxychains4 steam|
>
>     ERROR: ld.so: object '/usr/lib/libproxychains4.so' from LD_PRELOAD
>     cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
>
> and then other errors follow this one...
>
> Any useful tip?
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rofl0r/proxychains-ng/issues/102>.
>

-- 


S pozdravem Vilem Kebrt
email: viker@viker.cz
tel: +420 604 550 132

**Comment by rofl0r** [comment]
@vikerian i believe you are mistaken.
it seems steam is a 32 bit app so @alexgv99 needs a 32bit proxychains
hint: ```make clean ; CC="gcc -m32" ./configure ; make```

**Comment by rofl0r** [comment]
@alexgv99 another thing: port 3128 is the default port of squid, so it's probably a HTTP proxy, not a socks one.

**Comment by vikerian** [comment]
wrong ELF class: ELFCLASS64 - You're right , sorry...
Viker

On 01/04/2016 02:14 PM, rofl0r wrote:
>
> @vikerian <https://github.com/vikerian> i believe you are mistaken.
> it seems steam is a 32 bit app so @alexgv99
> <https://github.com/alexgv99> needs a 32bit proxychains
> hint: |make clean ; CC="gcc -m32" ./configure ; make|
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rofl0r/proxychains-ng/issues/102#issuecomment-168674162>.
>

-- 


S pozdravem Vilem Kebrt
email: viker@viker.cz
tel: +420 604 550 132

**Comment by rofl0r** [comment]
so yes, the problem is due to usage of 32 bit binaries and 64 bit proxychains.
