### ISSUE TITLE
Symbol lookup error __fini_array_start

### ISSUE THREAD

**Issue by Programming4life** [rofl0r/proxychains-ng#106]
I keep getting this error `symbol lookup error: ./libproxychains4.so: undefined symbol: __fini_array_start` when running an application `./proxychains4 someapp`.
I'm working on an embedded device with a sh4 processor.

**Comment by rofl0r** [comment]
maybe recompile your toolchain (gcc,binutils) with ```--enable-init-fini-array```

**Comment by Programming4life** [comment]
@rofl0r I didnt build the toolchain it was prebuilt. I tried building it but was gettings errors everywhere and gave up. Is there another way to solve this without building the toolchain?

**Comment by rofl0r** [comment]
you could try to patch out the gcc constructor code used to initialize the lib and rely on the lazy initialization to work (hint: grep for "constructor" and change the ```#ifdef __GNUC__ ... ``` to ```#if 0```)

**Comment by Programming4life** [comment]
Solved it I ended up using Ubuntu 16.04 witch already has a toolchain for sh4 witch seems to work. Thanks for the tips.
