### ISSUE TITLE
hostname instead of ip

### ISSUE THREAD

**Issue by vinnitu** [rofl0r/proxychains-ng#112]
my proxy provider use cdn to get me proxy access, how can I use it with proxychains if a has error 
```
proxy my.cdn.proxy.provider.com has invalid value or is not numeric
```

?

thx

**Comment by rofl0r** [comment]
use ```host my.cdn.proxy.provider.com``` or ping to get ip address, then use IP.

**Comment by xing393939** [comment]
how to use `host my.cdn.proxy.provider.com`

**Comment by rofl0r** [comment]
`host` is a command available on most unix'es, which resolves the ip address of the DNS name you pass.
so you literally type that command into the shell.

**Comment by SalimF** [comment]
Hello I have same issue, the service I use to provide dynamic proxies changes every time I run it .
is there a way to support it in `proxychains-ng`

**Comment by rofl0r** [comment]
see resolution for the duplicate https://github.com/rofl0r/proxychains-ng/issues/246
