### ISSUE TITLE
Doesn't work when downloading boot2docker.iso even turn SIP off

### ISSUE THREAD

**Issue by 18601673727** [rofl0r/proxychains-ng#113]
```
$ csrutil status
System Integrity Protection status: disabled.
```
Works when trying `proxychains4 curl http://ifconfig.co/` but
```
$ proxychains4 docker-machine create --driver virtualbox default
[proxychains] config file found: /Users/xxx/.proxychains/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib
Running pre-create checks...
(dev) No default Boot2Docker ISO found locally, downloading the latest release...
Error with pre-create check: "Get https://api.github.com/repos/boot2docker/boot2docker/releases/latest: dial tcp 224.0.0.1:443: connect: address family not supported by protocol family"
```

**Comment by rofl0r** [comment]
unless you're using the 10.x.x.x subnet for your lan, you can try if setting remote_dns_subnet to 10 fixes it.

**Comment by 18601673727** [comment]
Thanks for the quick reply, yes, I'm using10.x.x.x subnet for my lan but setting remote_dns_subnet to 10 does not work.

**Comment by rofl0r** [comment]
yes, remote_dns_subnet 10 only works when you're *not* using it already

**Comment by rofl0r** [comment]
you may use one of these blocks: https://en.wikipedia.org/wiki/List_of_assigned_/8_IPv4_address_blocks
if you set remote_dns_subnet to 3, it could work, but you won't be able to connect to any servers belonging to "General Electric Company"

**Comment by 18601673727** [comment]
Fuxk "General Electric Company", I just need my docker machine running.

**Comment by rofl0r** [comment]
and does it work ?

**Comment by 18601673727** [comment]
It doesn't bro.

**Comment by rofl0r** [comment]
well i guess it would be sufficient to change the ip address range that you use for your LAN to 192.168.x.x or 172.16.x.x and then use 10 for the localnet.
i don't know what the exact problem is, it may be due to the fact that docker is written in Go which afaik supports only static linking.

**Comment by 18601673727** [comment]
@rofl0r ping also doesn't work btw

**Comment by rofl0r** [comment]
ping uses icmp and raw sockets, both not supported by proxychains...
it's also unlikely that your go program will ever work, since apparently go does not use libc, but does all syscalls directly.

**Comment by XadillaX** [comment]
I have the same problem.

And when I changed it to 10, it shows:

```
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/local/lib/libproxychains4.dylib
[proxychains] DLL init
[proxychains] DLL init
[proxychains] Strict chain  ...  172.16.11.14:1087  ...  github.com:22  ...  OK
[proxychains] DLL init
[proxychains] DLL init
[proxychains] DLL init
Git LFS: (0 of 7 files) 0 B / 122.51 MB
Post https://api.github.com/lfs/XadillaX/aliyun-ons/objects/batch: x509: certificate is valid for , not api.github.com
error: failed to push some refs to 'git@github.com:XadillaX/aliyun-ons.git'
```

After changing it to 3, it shows:

```
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/local/lib/libproxychains4.dylib
[proxychains] DLL init
[proxychains] DLL init
[proxychains] Strict chain  ...  172.16.11.14:1087  ...  github.com:22  ...  OK
Warning: Permanently added the RSA host key for IP address '3.0.0.1' to the list of known hosts.
[proxychains] DLL init
[proxychains] DLL init
[proxychains] DLL init
Connection to github.com closed by remote host.
Git LFS: (0 of 7 files) 0 B / 122.51 MB
Post https://api.github.com/lfs/XadillaX/aliyun-ons/objects/batch: dial tcp 3.0.0.1:443: i/o timeout
error: failed to push some refs to 'git@github.com:XadillaX/aliyun-ons.git'
```

**Comment by rofl0r** [comment]
what program are you trying to use @XadillaX ?
