### ISSUE TITLE
How does Nmap react with proxychains 

### ISSUE THREAD

**Issue by bobbuilder123** [rofl0r/proxychains-ng#117]
If someone uses Nmap (-sV) + Tor + Proxychains, how does the proxychain program react to it. If the -sV (version detection) uses other protocols than icmp, if that can't be sent through the proxy, are they sent directly to the destination (the ip scanned)? Thanks

**Comment by rofl0r** [comment]
yes and no:
yes, if you use an IP address to target your victim, the icmp/udp stuff will go out directly.
no, if you use a DNS name and have remote_dns turned on, proxychains will make an internal mapping from a unroutable ip address to the target, however only tcp will be forwarded to there.
for more details  do some tests with your network traffic sniffer (wireshark for example).
