### ISSUE TITLE
just show [proxychains] preloading /usr/lib/libproxychains4.so and no answer

### ISSUE THREAD

**Issue by istory85** [rofl0r/proxychains-ng#118]
[root@is ~]# proxychains4 curl https://www.twitter.com/
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[root@is ~]# 

and I use centos 7

**Comment by rofl0r** [comment]
pls paste the output of ```strace -f proxychains4 curl https://www.twitter.com/```

**Comment by rofl0r** [comment]
oh and also try as non-root, i believe glibc has some security mechanisms in place when you use LD_PRELOAD as root or on suid binaries.

**Comment by rofl0r** [comment]
closing because of lack of feedback
