### ISSUE TITLE
bsdthread_register error upon running "proxychains4 vagrant up"

### ISSUE THREAD

**Issue by meichuan** [rofl0r/proxychains-ng#120]
On Mac(El Capitan), after I ran `proxychains4 vagrant up`, I got error below:
`[proxychains] config file found: /usr/local/Cellar/proxychains-ng/4.11/etc/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib
fatal error: runtime: bsdthread_register error (unset DYLD_INSERT_LIBRARIES)

runtime stack:
runtime.throw(0x169380, 0x3f)
	/Users/mitchellh/code/3rdparty/go/src/runtime/panic.go:527 +0x90 fp=0x7fff5fbff920 sp=0x7fff5fbff908
runtime.goenvs()
	/Users/mitchellh/code/3rdparty/go/src/runtime/os1_darwin.go:71 +0x74 fp=0x7fff5fbff948 sp=0x7fff5fbff920
runtime.schedinit()
	/Users/mitchellh/code/3rdparty/go/src/runtime/proc1.go:60 +0x83 fp=0x7fff5fbff990 sp=0x7fff5fbff948
runtime.rt0_go(0x7fff5fbff9c8, 0x2, 0x7fff5fbff9c8, 0x0, 0x0, 0x2, 0x7fff5fbffb40, 0x7fff5fbffb48, 0x0, 0x7fff5fbffb4b, ...)
	/Users/mitchellh/code/3rdparty/go/src/runtime/asm_amd64.s:109 +0x132 fp=0x7fff5fbff998 sp=0x7fff5fbff990`
What's the problem?

**Comment by rofl0r** [comment]
programs written in GO are not compatible with proxychains since they do not use the system's libc, whose functions we hook.
