### ISSUE TITLE
proxychain4 binary md5sum different

### ISSUE THREAD

**Issue by goog** [rofl0r/proxychains-ng#121]
i used **release version 4.11** and <code>git clone https://github.com/rofl0r/proxychains-ng.git</code> 
however i got two different md5sum

**Comment by rofl0r** [comment]
please explain in detail which files you did md5sum on.

**Comment by goog** [comment]
**proxychains4** binary file

**Comment by rofl0r** [comment]
in case you compiled both git and tarball release with the same compiler and CFLAGS, that would indeed be strange. but in your case i strongly suspect PEBKAC, since you're not even capable of building a whole sentence.
