### ISSUE TITLE
gnutls_handshake() failed: Error in the push function

### ISSUE THREAD

**Issue by jk2K** [rofl0r/proxychains-ng#122]
I get an error
`Err:1 https://packagecloud.io/grafana/stable/debian wheezy/main amd64 grafana amd64 3.0.4-1464167696
  gnutls_handshake() failed: Error in the push function.
E: Failed to fetch https://packagecloud.io/grafana/stable/debian/pool/wheezy/main/g/grafana/grafana_3.0.4-1464167696_amd64.deb  gnutls_handshake() failed: Error in the push function`
when I run
`proxychains4 sudo apt install grafana`

my version: Ubuntu 16.04 LTS, proxychains-ng 4.11

**Comment by rofl0r** [comment]
just to make sure: can you try with latest git ? there was an issue fixed, and maybe it's related.

**Comment by jk2K** [comment]
My git version is `2.7.4`, it should be no related

when i use http proxy, it's ok
```bash
http_proxy=http://localhost:8123 sudo apt install grafana
```

**Comment by rofl0r** [comment]
with "latest git", i refer to checking out the latest version of this repo

**Comment by jk2K** [comment]
I use latest git `2.8.3`, the test result are same, having nothing to do with git
