### ISSUE TITLE
Proxychains rstudio server deamon doesn't work

### ISSUE THREAD

**Issue by sb2nov** [rofl0r/proxychains-ng#128]
Rstudio server creates a child process that is used for network. When running proxychains4 with R shell directly it works perfectly but doesn't work when using rstudio.

Proxychains is not printing an output as well. Is there a way to fix this ?

**Comment by rofl0r** [comment]
check the documentation if there's a way to run the server process manually, and then try to run it with proxychains.

**Comment by sb2nov** [comment]
I don't think there is a process to run the child process with proxychains with some config, even when you run the parent with proxychains.

closing it as I think of a workaround.

**Comment by rofl0r** [comment]
there are several ways to start a child process (the exec* family of functions, see ```man 3p exec```) and some of them allow you to start a process with a clean environment.
in such a case the LD_PRELOAD variable will not be preserved, and the child process started without proxychains.
