### ISSUE TITLE
"Socket error or timeout" when using localnet

### ISSUE THREAD

**Issue by antonini** [rofl0r/proxychains-ng#130]
I'm trying to execute proxychains using a socks proxy but at the same time the app is going to access a local system that is deployed on a loopback interface.

Here is my scenario:
application binding 127.0.0.1:4343

I keep receiving the following error when executing proxychains:

    [proxychains] Strict chain  ...  127.0.0.1:6500  ...  localhost:4343 <--socket error or timeout!
    [proxychains] Strict chain  ...  127.0.0.1:6500  ...  localhost:4343 <--socket error or timeout!
    [proxychains] DLL init
    [proxychains] DLL init
    [proxychains] Strict chain  ...  127.0.0.1:6500  ...  localhost:4343 <--socket error or timeout!
    [proxychains] Strict chain  ...  127.0.0.1:6500  ...  localhost:4343 <--socket error or timeout!
    [proxychains] Strict chain  ...  127.0.0.1:6500  ...  localhost:4343 <--socket error or timeout!

And the "funny" situation is that the proxychains has accessed the port 4343 because it showed the data that I want on the log, and on my ssh connection is showing the current log message:

    user@server:/home/user [user]$ 
    channel 2: open failed: connect failed: Connection refused
    channel 2: open failed: connect failed: Connection refused
    channel 2: open failed: connect failed: Connection refused

Here is my config file:

	# proxychains.conf  VER 4.x
	#
	#        HTTP, SOCKS4a, SOCKS5 tunneling proxifier with DNS.

	# The option below identifies how the ProxyList is treated.
	# only one option should be uncommented at time,
	# otherwise the last appearing option will be accepted
	#
	#dynamic_chain
	#
	# Dynamic - Each connection will be done via chained proxies
	# all proxies chained in the order as they appear in the list
	# at least one proxy must be online to play in chain
	# (dead proxies are skipped)
	# otherwise EINTR is returned to the app
	#
	strict_chain
	#
	# Strict - Each connection will be done via chained proxies
	# all proxies chained in the order as they appear in the list
	# all proxies must be online to play in chain
	# otherwise EINTR is returned to the app
	#
	#round_robin_chain
	#
	# Round Robin - Each connection will be done via chained proxies
	# of chain_len length
	# all proxies chained in the order as they appear in the list
	# at least one proxy must be online to play in chain
	# (dead proxies are skipped).
	# the start of the current proxy chain is the proxy after the last
	# proxy in the previously invoked proxy chain.
	# if the end of the proxy chain is reached while looking for proxies
	# start at the beginning again.
	# otherwise EINTR is returned to the app
	# These semantics are not guaranteed in a multithreaded environment.
	#
	#random_chain
	#
	# Random - Each connection will be done via random proxy
	# (or proxy chain, see  chain_len) from the list.
	# this option is good to test your IDS :)

	# Make sense only if random_chain or round_robin_chain
	#chain_len = 2

	# Quiet mode (no output from library)
	#quiet_mode

	# Proxy DNS requests - no leak for DNS data
	proxy_dns 

	# set the class A subnet number to use for the internal remote DNS mapping
	# we use the reserved 224.x.x.x range by default,
	# if the proxified app does a DNS request, we will return an IP from that range.
	# on further accesses to this ip we will send the saved DNS name to the proxy.
	# in case some control-freak app checks the returned ip, and denies to 
	# connect, you can use another subnet, e.g. 10.x.x.x or 127.x.x.x.
	# of course you should make sure that the proxified app does not need
	# *real* access to this subnet. 
	# i.e. dont use the same subnet then in the localnet section
	#remote_dns_subnet 127 
	#remote_dns_subnet 10
	remote_dns_subnet 224

	# Some timeouts in milliseconds
	tcp_read_time_out 15000
	tcp_connect_time_out 8000

	### Examples for localnet exclusion
	## localnet ranges will *not* use a proxy to connect.
	## Exclude connections to 192.168.1.0/24 with port 80
	# localnet 192.168.1.0:80/255.255.255.0

	## Exclude connections to 192.168.100.0/24
	# localnet 192.168.100.0/255.255.255.0

	## Exclude connections to ANYwhere with port 80
	# localnet 0.0.0.0:80/0.0.0.0

	## RFC5735 Loopback address range
	## if you enable this, you have to make sure remote_dns_subnet is not 127
	## you'll need to enable it if you want to use an application that 
	## connects to localhost.
	localnet 127.0.0.0/255.0.0.0

	## RFC1918 Private Address Ranges
	# localnet 10.0.0.0/255.0.0.0
	# localnet 172.16.0.0/255.240.0.0
	# localnet 192.168.0.0/255.255.0.0

	# ProxyList format
	#       type  ip  port [user pass]
	#       (values separated by 'tab' or 'blank')
	#
	#       only numeric ipv4 addresses are valid
	#
	#
	#        Examples:
	#
	#            	socks5	192.168.67.78	1080	lamer	secret
	#		http	192.168.89.3	8080	justu	hidden
	#	 	socks4	192.168.1.49	1080
	#	        http	192.168.39.93	8080	
	#		
	#
	#       proxy types: http, socks4, socks5
	#        ( auth types supported: "basic"-http  "user/pass"-socks )
	#
	[ProxyList]
	# add proxy here ...
	# meanwile
	# defaults set to "tor"
	socks4 	127.0.0.1 1234

**Comment by rofl0r** [comment]
turn off proxy_dns or use 127.0.0.1 as your app server address instead of localhost.
since localhost is a name, not an ip, the localnet detection does not catch it, so the connection to the proxy is made which does the lookup of localhost and then tries to connect port 4343 on its own loopback interface.

**Comment by antonini** [comment]
Thanks @rofl0r! It worked!

**Comment by sebmaker** [comment]
Hello I am the same troble. Please help me
I send the code "proxychains wget https://www.cosco.com/
But appear this:
[proxychains] config file found: /root/proxychains.conf
[proxychains] preloading /usr/lib/x86_64-linux-gnu/libproxychains.so.4
[proxychains] DLL init: proxychains-ng 4.14
--2021-04-17 14:59:06-- https://www.cisco.com/
Resolviendo www.cisco.com (www.cisco.com)... 224.0.0.1
Conectando con www.cisco.com (www.cisco.com)[224.0.0.1]:443... [proxychains] Strict
chain . . .  208.94.215.238:39593   .  .  .  www.cisco.com:443  <--denied
failed: Connection refuse

**Comment by rofl0r** [comment]
maybe use a proxy that actually works?

**Comment by sebmaker** [comment]
I try with tor but it appears the same. My conf is this:
# proxychains.conf  VER 3.1
#
#        HTTP, SOCKS4, SOCKS5 tunneling proxifier with DNS.
#

# The option below identifies how the ProxyList is treated.
# only one option should be uncommented at time,
# otherwise the last appearing option will be accepted
#
#dynamic_chain
#
# Dynamic - Each connection will be done via chained proxies
# all proxies chained in the order as they appear in the list
# at least one proxy must be online to play in chain
# (dead proxies are skipped)
# otherwise EINTR is returned to the app
#
strict_chain
#
# Strict - Each connection will be done via chained proxies
# all proxies chained in the order as they appear in the list
# all proxies must be online to play in chain
# otherwise EINTR is returned to the app
#
#random_chain
#
# Random - Each connection will be done via random proxy
# (or proxy chain, see  chain_len) from the list.
# this option is good to test your IDS :)

# Make sense only if random_chain
#chain_len = 2

# Quiet mode (no output from library)
#quiet_mode

# Proxy DNS requests - no leak for DNS data
proxy_dns 

# Some timeouts in milliseconds
tcp_read_time_out 15000
tcp_connect_time_out 8000

# ProxyList format
#       type  host  port [user pass]
#       (values separated by 'tab' or 'blank')
#
#
#        Examples:
#
#               socks5  192.168.67.78   1080    lamer   secret
#               http    192.168.89.3    8080    justu   hidden
#               socks4  192.168.1.49    1080
#               http    192.168.39.93   8080
#
#
#       proxy types: http, socks4, socks5
#        ( auth types supported: "basic"-http  "user/pass"-socks )
#
[ProxyList]
# add proxy here ...
# meanwile
# defaults set to "tor"
socks4 185.40.72.90 4153

**Comment by sebmaker** [comment]
I try with tor but it appears the same
It´s my code

```
# proxychains.conf  VER 3.1
#
#        HTTP, SOCKS4, SOCKS5 tunneling proxifier with DNS.
#

# The option below identifies how the ProxyList is treated.
# only one option should be uncommented at time,
# otherwise the last appearing option will be accepted
#
#dynamic_chain
#
# Dynamic - Each connection will be done via chained proxies
# all proxies chained in the order as they appear in the list
# at least one proxy must be online to play in chain
# (dead proxies are skipped)
# otherwise EINTR is returned to the app
#
strict_chain
#
# Strict - Each connection will be done via chained proxies
# all proxies chained in the order as they appear in the list
# all proxies must be online to play in chain
# otherwise EINTR is returned to the app
#
#random_chain
#
# Random - Each connection will be done via random proxy
# (or proxy chain, see  chain_len) from the list.
# this option is good to test your IDS :)

# Make sense only if random_chain
#chain_len = 2

# Quiet mode (no output from library)
#quiet_mode

# Proxy DNS requests - no leak for DNS data
proxy_dns 

# Some timeouts in milliseconds
tcp_read_time_out 15000
tcp_connect_time_out 8000

# ProxyList format
#       type  host  port [user pass]
#       (values separated by 'tab' or 'blank')
#
#
#        Examples:
#
#               socks5  192.168.67.78   1080    lamer   secret
#               http    192.168.89.3    8080    justu   hidden
#               socks4  192.168.1.49    1080
#               http    192.168.39.93   8080
#
#
#       proxy types: http, socks4, socks5
#        ( auth types supported: "basic"-http  "user/pass"-socks )
#
[ProxyList]
# add proxy here ...
# meanwile
# defaults set to "tor"
socks4 127.0.0.1 9050

```

**Comment by sebmaker** [comment]
And when i try with tor ip 127.0.0.1 9050
appear thist:

```
[proxychains] config file found: /home/kali/proxychains.conf
[proxychains] preloading /usr/lib/x86_64-linux-gnu/libproxychains.so.4
[proxychains] DLL init: proxychains-ng 4.14
--2021-04-17 09:58:20--  https://www.cisco.com/
Resolving www.cisco.com (www.cisco.com)... 224.0.0.1
Connecting to www.cisco.com (www.cisco.com)|224.0.0.1|:443... [proxychains] Strict chain  ...  127.0.0.1:9050  ...  www.cisco.com:443  ...  OK
connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-04-17 09:58:23 ERROR 403: Forbidden.
```

**Comment by rofl0r** [comment]
you're aware that you need to run tor on your machine first?

**Comment by rofl0r** [comment]
oh look, it's because cisco.com doesnt allow connections from tor.

**Comment by sebmaker** [comment]
yes, first i run tor, but i don´t understan why when i put a other service proxy don´t run and this appears failed: Connection refuse

**Comment by sebmaker** [comment]
Thanks you I found the error
