### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by theman480** [rofl0r/proxychains-ng#133]
Is there any way to use proxychains-ng with windows?

**Comment by rofl0r** [comment]
i heard something about windows 10 being able to run native linux binaries, so it possibly works (but only when used with other native linux apps).

**Comment by Programming4life** [comment]
@theman480 Why do you need to do this on windows? Do you want to intercept traffic?

**Comment by theman480** [comment]
@Programming4life  The same reason you need it on linux, i guess.
