### ISSUE TITLE
libproxychains4.so problem, can't load process....: No such file or directory

### ISSUE THREAD

**Issue by photonxp** [rofl0r/proxychains-ng#139]
What I did:
Downloaded the source file proxychains-ng-4.11.tar.bz2 from sourceforge

Compiled it on the 64-bit Ubutun 12.04
$ sudo ./configure --prefix=/usr --sysconfdir=/etc
checking whether netinet/in.h defines s6_addr16 ... yes
checking whether $CC defines __OpenBSD__ ... no
Done, now run make && make install

Make install
$ sudo make && make install
cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/nameinfo.o src/nameinfo.c
printf '#define VERSION "%s"\n' "$(sh tools/version.sh)" > src/version.h
cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/version.o src/version.c
cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/core.o src/core.c
cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/common.o src/common.c
cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/libproxychains.o src/libproxychains.c
cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/allocator_thread.o src/allocator_thread.c
cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/ip_type.o src/ip_type.c
src/ip_type.c:4:1: warning: missing braces around initializer [-Wmissing-braces]
src/ip_type.c:4:1: warning: (near initialization for ‘ip_type_localhost.addr.v4.octet’) [-Wmissing-braces]
cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/hostsreader.o src/hostsreader.c
cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/hash.o src/hash.c
cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/debug.o src/debug.c
cc -shared -fPIC -Wl,--no-as-needed -ldl -lpthread -Wl,-soname=libproxychains4.so  \
		-o libproxychains4.so src/nameinfo.o src/version.o src/core.o src/common.o src/libproxychains.o src/allocator_thread.o src/ip_type.o src/hostsreader.o src/hash.o src/debug.o
cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/main.o src/main.c
cc src/main.o src/common.o  -o proxychains4
./tools/install.sh -D -m 644 libproxychains4.so /usr/lib/libproxychains4.so
./tools/install.sh: 53: ./tools/install.sh: cannot create /usr/lib/libproxychains4.so.tmp.11365: Permission denied
make: *** [/usr/lib/libproxychains4.so] Error 2

Worked around the error
$ sudo chown root ./tools/install.sh

Installed it
$ sudo make install
./tools/install.sh -D -m 644 libproxychains4.so /usr/lib/libproxychains4.so
./tools/install.sh -D -m 755 proxychains4 /usr/bin/proxychains4

Run it
$ proxychains4 -c /etc/proxychains4.conf aptitude update
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
proxychains can't load process....: No such file or directory

$ echo $PATH
/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/game

**Comment by rofl0r** [comment]
the syntax for specifying a config file is `-f`, not `-c`

so what happens to you is that proxychains thinks it should call a command `-f` which does not exist.

**Comment by ucoker** [comment]
Same issue on the 64-bit Ubutun 14.04  

```bash
$ proxychains4 curl twitter.com
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
proxychains can't load process....: No such file or directory
```

**Comment by rofl0r** [comment]
@ucoker : try `which curl` and then pass the full path to curl to proxychains4.
would also be interesting to get the output of `proxychains4 bash -c export`.

**Comment by ucoker** [comment]
I try   `sudo apt-get install proxychains`
It's worked.

proxychains version:    `3.1-6`

OS Version:   `ubuntu 14.04`

**Comment by rofl0r** [comment]
@ucoker: that is an ancient proxychains version (since debian does still not have proxychains-ng in their repos, i guess), but when it works for you, fine.
i would however still be interested in why it didnt work, so if you could follow the steps i outlined above and provide the requested feedback, it could be helpful for us.

**Comment by ucoker** [comment]
@rofl0r ,How to know the correct version of proxychains? 

- my proxychains.conf  

the version is `VER 3.1`

```bash
# proxychains.conf  VER 3.1
#
#        HTTP, SOCKS4, SOCKS5 tunneling proxifier with DNS.
#       

# The option below identifies how the ProxyList is treated.
# only one option should be uncommented at time,
# otherwise the last appearing option will be accepted
#
#dynamic_chain
#
# Dynamic - Each connection will be done via chained proxies
# all proxies chained in the order as they appear in the list
# at least one proxy must be online to play in chain
# (dead proxies are skipped)
# otherwise EINTR is returned to the app
#
strict_chain
#
# Strict - Each connection will be done via chained proxies
# all proxies chained in the order as they appear in the list
# all proxies must be online to play in chain
# otherwise EINTR is returned to the app
#
#random_chain
#
# Random - Each connection will be done via random proxy
# (or proxy chain, see  chain_len) from the list.
# this option is good to test your IDS :)

# Make sense only if random_chain
#chain_len = 2

# Quiet mode (no output from library)
#quiet_mode

# Proxy DNS requests - no leak for DNS data
proxy_dns

# Some timeouts in milliseconds
tcp_read_time_out 15000
tcp_connect_time_out 8000

# ProxyList format
#       type  host  port [user pass]
#       (values separated by 'tab' or 'blank')
#
#
#        Examples:
#
#               socks5  192.168.67.78   1080    lamer   secret
#               http    192.168.89.3    8080    justu   hidden
#               socks4  192.168.1.49    1080
#               http    192.168.39.93   8080    
#               
#
#       proxy types: http, socks4, socks5
#        ( auth types supported: "basic"-http  "user/pass"-socks )
#
[ProxyList]
# add proxy here ...
# meanwile
# defaults set to "tor"
socks5  127.0.0.1 1080
```

- the output of `proxychains4 bash -c export`

the version is `proxychains-ng 4.11`?
output:

```bash
  root@my:~# proxychains4 bash -c export
  [proxychains] config file found: /etc/proxychains.conf
  [proxychains] preloading /usr/lib/libproxychains4.so
  [proxychains] DLL init: proxychains-ng 4.11-git-9-gcf9a16d
  declare -x HOME="/root"
  declare -x LANG="en_US.UTF-8"
  declare -x LANGUAGE="en_US:"
  declare -x LD_PRELOAD="/usr/lib/libproxychains4.so"
  declare -x LESSCLOSE="/usr/bin/lesspipe %s %s"
  declare -x LESSOPEN="| /usr/bin/lesspipe %s"
  declare -x LOGNAME="root"
  declare -x LS_COLORS="rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:"
  declare -x MAIL="/var/mail/root"
  declare -x OLDPWD
  declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
  declare -x PROXYCHAINS_CONF_FILE="/etc/proxychains.conf"
  declare -x PWD="/root"
  declare -x SHELL="/bin/bash"
  declare -x SHLVL="2"
  declare -x SSH_CLIENT="xxx.xxx.xxx.xxx xxx 22"
  declare -x SSH_CONNECTION="x.x.x.x x x.x.x.x 22"
  declare -x SSH_TTY="/dev/pts/0"
  declare -x TERM="xterm-256color"
  declare -x USER="root"
  declare -x XDG_RUNTIME_DIR="/run/user/0"
  declare -x XDG_SESSION_ID="12"
  declare -x _="/usr/bin/proxychains4"
```

so what is the correct version ? And this version works for me.

**Comment by ucoker** [comment]
I try to download source and compiled it.
It works for me now.
Thanks.

```bash
# download the source of proxychains-ng
git clone https://github.com/rofl0r/proxychains-ng.git

cd proxychains-ng

# configure and install 
./configure --prefix=/usr --sysconfdir=/etc
make
sudo make install
sudo make install-config # installs /etc/proxychains.conf
```

Test:
```bash
$ proxychains4 curl twitter.com
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.11-git-9-gcf9a16d
[proxychains] Strict chain  ...  127.0.0.1:1080  ...  twitter.com:80  ...  OK
```

**Comment by rofl0r** [comment]
sweet. thanks for info.

**Comment by Leviathan1995** [comment]
@ucoker maybe you not install `curl`
`sudo apt-get install curl`

`$ proxychains4 curl www.google.com`
`[proxychains] config file found: /usr/local/etc/proxychains.conf`
`[proxychains] preloading /usr/local/lib/libproxychains4.so`
`[proxychains] DLL init: proxychains-ng 4.11`
`[proxychains] Strict chain  ...  127.0.0.1:1080  ...  www.google.com:80  ...  OK`
`<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">`
`<TITLE>302 Moved</TITLE></HEAD><BODY>`
`<H1>302 Moved</H1>`
`The document has moved`
`<A HREF="http://www.google.com.vn/?gfe_rd=cr&amp;ei=xNoPWbyzJYbM8gfJrY1A">here</A>.`
`</BODY></HTML>`
`

**Comment by slw07g** [comment]
I experienced the same bug, I worked around it by using proxychains3 with no issues.
