### ISSUE TITLE
proxyresolv is not installed on CentOS 7

### ISSUE THREAD

**Issue by ukll** [rofl0r/proxychains-ng#144]
When I built it as described in README, it successfully built and installed proxychains to /usr/bin/proxychains4. However, there is nothing like proxyresolv* anywhere.

**The log messages are:**

    #./configure --prefix=/usr --sysconfdir=/etc
    checking whether netinet/in.h defines s6_addr16 ... yes
    checking whether $CC defines __OpenBSD__ ... no
    Done, now run make && make install

    #sudo make
    cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/nameinfo.o src/nameinfo.c
    printf '#define VERSION "%s"\n' "$(sh tools/version.sh)" > src/version.h
    cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/version.o src/version.c
    cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/core.o src/core.c
    cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/common.o src/common.c
    cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/libproxychains.o src/libproxychains.c
    cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/allocator_thread.o src/allocator_thread.c
    cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/ip_type.o src/ip_type.c
    src/ip_type.c:4:1: warning: missing braces around initializer [-Wmissing-braces]
     const ip_type ip_type_localhost = { .addr.v4 = {127, 0, 0, 1} };
     ^
    src/ip_type.c:4:1: warning: (near initialization for ‘ip_type_localhost.addr.v4.octet’) [-Wmissing-braces]
    cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/hostsreader.o src/hostsreader.c
    cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/hash.o src/hash.c
    cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/debug.o src/debug.c
    cc -shared -fPIC -Wl,--no-as-needed -ldl -lpthread -Wl,-soname=libproxychains4.so  \
	-o libproxychains4.so src/nameinfo.o src/version.o src/core.o src/common.o src/libproxychains.o src/allocator_thread.o src/ip_type.o src/hostsreader.o src/hash.o src/debug.o
    cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/main.o src/main.c
    cc src/main.o src/common.o  -o proxychains4

    #sudo make install
    ./tools/install.sh -D -m 644 libproxychains4.so /usr/lib/libproxychains4.so
    ./tools/install.sh -D -m 755 proxychains4 /usr/bin/proxychains4

    #sudo make install-config
    ./tools/install.sh -D -m 644 src/proxychains.conf /etc/proxychains.conf

**Comment by rofl0r** [comment]
yes, that is by design. proxyresolv is no longer *required* for proxychains-ng itself to work, and because it has external dependencies (dig program), it only ships as a bonus in the tarball - that means the onus to install it is on your side.
