### ISSUE TITLE
proxychains can't load process....: No such file or directory

### ISSUE THREAD

**Issue by githubstarit** [rofl0r/proxychains-ng#150]
os x 10.10.3

run proxychains4 docker build -t hosea/php:5.6.8 ./

[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.dylib
proxychains can't load process....: No such file or directory

proxychains4 git clone ····
just docker error！

**Comment by rofl0r** [comment]
paste output of
`which docker`
`echo $PATH`

**Comment by Random1984** [comment]
I had the same problem because my /etc/tor/torrc file was configured to listen on my IPv4 LAN address but my /etc/proxychains.conf was trying to access to 127.0.0.1. Changing it to the IP configured in torrc may solve the problem.
Hope I help you.

**Comment by rofl0r** [comment]
little point trying to help someone who opened an issue 2 years ago and then fails to report back after initial support inquiry. closing.
