### ISSUE TITLE
Not working with youtube-dl: undefined symbol: pthread_once

### ISSUE THREAD

**Issue by drunkard** [rofl0r/proxychains-ng#156]
I'm using youtube-dl with proxychains in Gentoo, and encounter this problem, can anyone help? thanks:

10:34:33 ~ $ /usr/bin/proxychains /usr/bin/youtube-dl --no-check-certificate -c https://www.youtube.com/watch?v=_PQbVH_aO5E
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib64/libproxychains.so.4.12
/usr/bin/python-exec2c: symbol lookup error: /usr/lib64/libproxychains.so.4.12: undefined symbol: pthread_once

10:37:51 ~ $ ldd /usr/lib64/libproxychains.so.4.12
	linux-vdso.so.1 (0x00007ffca15e2000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fbde8bba000)
	/lib64/ld-linux-x86-64.so.2 (0x00005560b2243000)

Is it build problem? how can I solve this?

**Comment by rofl0r** [comment]
libproxychains4.so should have a DT_NEEDED entry for libpthread.so 
`readelf -a libproxychains4.so | grep -i NEEDED`. since your libproxychains.so has a non-standard name i suspect the author of the gentoo recipe did something unintended.
try compiling proxychains by hand with configure and make and see if that works.

**Comment by drunkard** [comment]
Is it should be like this?

22:35:47 ~ $ readelf -a /usr/lib64/libproxychains.so.4.12 | grep -i NEEDED
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]

**Comment by rofl0r** [comment]
no, it's missing libpthread.so

**Comment by drunkard** [comment]
Thank you very much, issue solved.

**Comment by rofl0r** [comment]
did the gentoo devs fix their broken recipe ?

**Comment by drunkard** [comment]
Yes, they fixed.
