### ISSUE TITLE
ERROR: ld.so: object '/usr/lib/libproxychains4.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

### ISSUE THREAD

**Issue by 872517414** [rofl0r/proxychains-ng#157]
SteamCMD
![1](https://cloud.githubusercontent.com/assets/9050713/22138881/deba534c-df1d-11e6-8efd-82718f776da7.png)

**Comment by rofl0r** [comment]
duplicate of https://github.com/rofl0r/proxychains-ng/issues/153

**Comment by bluefatshao** [comment]
Have you solved this problem?

**Comment by wordlesswind** [comment]
> Have you solved this problem?

Maybe not, I haven't used it in a long time.
