### ISSUE TITLE
openSUSE Leap 42 preloading problem

### ISSUE THREAD

**Issue by hoooooomp** [rofl0r/proxychains-ng#160]
**[proxychains] preloading /usr/lib64/libproxychains4.so
proxychains can't load process....: No such file or directory**

This is what I get. I read the issues that other users had but didn't solve my problem.
I checked for libproxychains4.so and it is located in /usr/lib64/

I would love to get it it working though.

**_proxychains4 bash -c export_   
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib64/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.10
declare -x ALSA_CONFIG_PATH="/etc/alsa-pulse.conf"
declare -x AUDIODRIVER="pulseaudio"
declare -x COLORFGBG="15;0"
declare -x COLORTERM="1"
declare -x CONFIG_SITE="/usr/share/site/x86_64-unknown-linux-gnu"
declare -x CPU="x86_64"
declare -x CSHEDIT="emacs"
declare -x DBUS_SESSION_BUS_ADDRESS="unix:abstract=/tmp/dbus-dxtV8eMEsh,guid=bc74e2cec3cdb52b113bf72c589ca260"
declare -x DESKTOP_SESSION="/usr/share/xsessions/plasma5"
declare -x DISPLAY=":0"
declare -x FROM_HEADER=""
declare -x GPG_TTY="/dev/pts/2"
declare -x GS_LIB="/home/h0mp/.fonts"
declare -x GTK2_RC_FILES="/etc/gtk-2.0/gtkrc:/home/h0mp/.gtkrc-2.0"
declare -x GTK_IM_MODULE="cedilla"
declare -x GTK_MODULES="canberra-gtk-module"
declare -x G_BROKEN_FILENAMES="1"
declare -x G_FILENAME_ENCODING="@locale,UTF-8,ISO-8859-15,CP1252"
declare -x HISTSIZE="1000"
declare -x HOME="/root"
declare -x HOST="linux-oz31.suse"
declare -x HOSTNAME="linux-oz31.suse"
declare -x HOSTTYPE="x86_64"
declare -x INPUTRC="/home/h0mp/.inputrc"
declare -x JAVA_BINDIR="/usr/lib64/jvm/jre/bin"
declare -x JAVA_HOME="/usr/lib64/jvm/jre"
declare -x JAVA_ROOT="/usr/lib64/jvm/jre"
declare -x JRE_HOME="/usr/lib64/jvm/jre"
declare -x KDE_FULL_SESSION="true"
declare -x KDE_SESSION_UID="1000"
declare -x KDE_SESSION_VERSION="5"
declare -x KONSOLE_DBUS_SERVICE=":1.94"
declare -x KONSOLE_DBUS_SESSION="/Sessions/1"
declare -x KONSOLE_DBUS_WINDOW="/Windows/1"
declare -x KONSOLE_PROFILE_NAME="Default"
declare -x LANG="en_US.UTF-8"
declare -x LANGUAGE=""
declare -x LD_PRELOAD="/usr/lib64/libproxychains4.so"
declare -x LESS="-M -I -R"
declare -x LESSCLOSE="lessclose.sh %s %s"
declare -x LESSKEY="/etc/lesskey.bin"
declare -x LESSOPEN="lessopen.sh %s"
declare -x LESS_ADVANCED_PREPROCESSOR="no"
declare -x LOGNAME="h0mp"
declare -x LS_COLORS="no=00:fi=00:di=01;34:ln=00;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=41;33;01:ex=00;32:*.cmd=00;32:*.exe=01;32:*.com=01;32:*.bat=01;32:*.btm=01;32:*.dll=01;32:*.tar=00;31:*.tbz=00;31:*.tgz=00;31:*.rpm=00;31:*.deb=00;31:*.arj=00;31:*.taz=00;31:*.lzh=00;31:*.lzma=00;31:*.zip=00;31:*.zoo=00;31:*.z=00;31:*.Z=00;31:*.gz=00;31:*.bz2=00;31:*.tb2=00;31:*.tz2=00;31:*.tbz2=00;31:*.xz=00;31:*.avi=01;35:*.bmp=01;35:*.fli=01;35:*.gif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mng=01;35:*.mov=01;35:*.mpg=01;35:*.pcx=01;35:*.pbm=01;35:*.pgm=01;35:*.png=01;35:*.ppm=01;35:*.tga=01;35:*.tif=01;35:*.xbm=01;35:*.xpm=01;35:*.dl=01;35:*.gl=01;35:*.wmv=01;35:*.aiff=00;32:*.au=00;32:*.mid=00;32:*.mp3=00;32:*.ogg=00;32:*.voc=00;32:*.wav=00;32:"
declare -x LS_OPTIONS="-A -N --color=tty -T 0"
declare -x MACHTYPE="x86_64-suse-linux"
declare -x MAIL="/var/spool/mail/h0mp"
declare -x MANPATH="/usr/local/man:/usr/share/man"
declare -x MINICOM="-c on"
declare -x MORE="-sl"
declare -x NNTPSERVER="news"
declare -x OLDPWD
declare -x OSTYPE="linux"
declare -x PAGER="less"
declare -x PATH="/home/h0mp/bin:/usr/local/bin:/usr/bin:/sbin:/usr/sbin:/bin:/usr/bin/X11:/usr/games"
declare -x PROFILEHOME=""
declare -x PROFILEREAD="true"
declare -x PROXYCHAINS_CONF_FILE="/etc/proxychains.conf"
declare -x PWD="/home/h0mp/Downloads/proxychains-ng-master"
declare -x PYTHONSTARTUP="/etc/pythonstart"
declare -x QEMU_AUDIO_DRV="pa"
declare -x QMLSCENE_DEVICE="false"
declare -x QSG_RENDER_LOOP=""
declare -x QT_AUTO_SCREEN_SCALE_FACTOR="0"
declare -x QT_IM_MODULE="xim"
declare -x QT_IM_SWITCHER="imsw-multi"
declare -x QT_SYSTEM_DIR="/usr/share/desktop-data"
declare -x SDL_AUDIODRIVER="pulse"
declare -x SESSION_MANAGER="local/linux-oz31.suse:@/tmp/.ICE-unix/1505,unix/linux-oz31.suse:/tmp/.ICE-unix/1505"
declare -x SHELL="/bin/bash"
declare -x SHELL_SESSION_ID="6bfc40478fc34000be8cb7b264349033"
declare -x SHLVL="4"
declare -x SSH_ASKPASS="/usr/lib/ssh/ksshaskpass"
declare -x TERM="xterm"
declare -x USER="h0mp"
declare -x VDPAU_DRIVER="va_gl"
declare -x WINDOWID="96468997"
declare -x WINDOWMANAGER="/usr/bin/startkde"
declare -x XAUTHLOCALHOSTNAME="linux-oz31.suse"
declare -x XAUTHORITY="/root/.xauthTvS2Q4"
declare -x XCURSOR_THEME="breeze_cursors"
declare -x XDG_CONFIG_DIRS="/etc/xdg"
declare -x XDG_CURRENT_DESKTOP="KDE"
declare -x XDG_DATA_DIRS="/usr/share"
declare -x XDG_RUNTIME_DIR="/run/user/1000"
declare -x XDG_SEAT="seat0"
declare -x XDG_SEAT_PATH="/org/freedesktop/DisplayManager/Seat0"
declare -x XDG_SESSION_CLASS="user"
declare -x XDG_SESSION_DESKTOP="KDE"
declare -x XDG_SESSION_ID="3"
declare -x XDG_SESSION_PATH="/org/freedesktop/DisplayManager/Session1"
declare -x XDG_SESSION_TYPE="x11"
declare -x XDG_VTNR="7"
declare -x XKEYSYMDB="/usr/X11R6/lib/X11/XKeysymDB"
declare -x XMODIFIERS="@im=local"
declare -x XNLSPATH="/usr/share/X11/nls"
declare -x XSESSION_IS_UP="yes"
declare -x _="/usr/bin/proxychains4"**

**Comment by rofl0r** [comment]
what does not work? it seem it works with bash. maybe try with wget or curl ?
also provide build log, in case you built from source, if not, tell where you got proxychains from.

**Comment by hoooooomp** [comment]
Hi, I was away for the weekend. Tried again just now and it just works.

I installed proxychains through YaST.

Thanks anyway!
