### ISSUE TITLE
multithreading and namespace sandboxing

### ISSUE THREAD

**Issue by soredake** [rofl0r/proxychains-ng#161]
https://unix.stackexchange.com/questions/303179/if-youre-ld-preloading-nvidia-gl
i get `Sandbox: unexpected multithreading found; this prevents using namespace sandboxing. (If you're LD_PRELOAD'ing nVidia GL: that's not necessary for Gecko.)` in firefox log.
whether it is possible to do something with it to make the namespace sandboxing work with proxychains?

**Comment by rofl0r** [comment]
the answer you got there is accurate. there are however valid reasons why one would want to use proxychains with firefox: it's easier to just prefix the firefox command with proxychains when you want to run it with tor, and leave it away when you dont want to.
however a separate profile might be the better tool for the job.

i don't see how having proxychains' second thread could prevent firefox from using a sandbox, so your best bet is to open an issue in the mozilla bugtracker and explain that there are valid reasons to preload other things than just nvidia dlls.
