### ISSUE TITLE
proxychains does not work with cabal

### ISSUE THREAD

**Issue by zhao-ji** [rofl0r/proxychains-ng#165]
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.8 (wheezy)
Release:	7.8
Codename:	wheezy

proxychains cabal update
ProxyChains-3.1 (http://proxychains.sf.net)
Downloading the latest package list from hackage.haskell.org
Segmentation fault

**Comment by rofl0r** [comment]
proxychains 3.1 is no longer supported. try the latest release, proxychains-ng 4.12.

**Comment by zhao-ji** [comment]
ok!
