### ISSUE TITLE
how do i uninstall it

### ISSUE THREAD

**Issue by ericoda** [rofl0r/proxychains-ng#166]
i used following command lines to install it, and now i cant not reach the local internet and seems caused by this tool, how can i uninstall this tool completely, thanks.

```
git clone https://github.com/rofl0r/proxychains-ng.git
cd proxychains-ng
./configure
make && make install
cp ./src/proxychains.conf /etc/proxychains.conf
cd .. && rm -rf proxychains-ng

**Comment by rofl0r** [comment]
lol. proxychains is certainly not the reason for your network issues, unless you've configured it wrong and exported LD_PRELOAD globally, which i hope you didn't.
anyway, here's what your asking for:
run make install and look for which files got installed, then remove those manually.

**Comment by ericoda** [comment]
thanks so much

**Comment by StevenJokes** [comment]
sudo proxychains -q /bin/zsh

Then I uninstalled it ,because I can't use yay.
ERROR:ld.so:object 'usr/lib/libproxychains4.so'from LD_PRELOAD cannot
 be preloaded.
How can I solve it?
