### ISSUE TITLE
make fails: unknown type name ‘cpu_set_t’

### ISSUE THREAD

**Issue by soaringswine** [rofl0r/proxychains-ng#167]
Running Kali 4.4.0-kali1-686 in a VMWare Fusion on OS Sierra. ./configure is fine, but make fails with 

cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/libproxychains.o src/libproxychains.c
In file included from src/libproxychains.c:35:0:
/usr/include/pthread.h:398:12: error: unknown type name ‘cpu_set_t’
      const cpu_set_t *__cpuset)
            ^~~~~~~~~
/usr/include/pthread.h:405:6: error: unknown type name ‘cpu_set_t’
      cpu_set_t *__cpuset)
      ^~~~~~~~~
/usr/include/pthread.h:475:14: error: unknown type name ‘cpu_set_t’
        const cpu_set_t *__cpuset)
              ^~~~~~~~~
/usr/include/pthread.h:480:8: error: unknown type name ‘cpu_set_t’
        cpu_set_t *__cpuset)
        ^~~~~~~~~

**Comment by rofl0r** [comment]
we don't use cpu_set_t in proxychains.
the error you're getting is because your libc headers are somehow broken.
probably this testfile here will cause the error too:
```
include <pthread.h>
void main() {}
```
i'd report it on the kali bugtracker.
