### ISSUE TITLE
How close the prompt ＃ of localnet exceed 64.

### ISSUE THREAD

**Issue by Arnosir** [rofl0r/proxychains-ng#169]
# proxychains.conf
\#Quiet mode (no output from library)
quiet_mode

\## RFC1918 Private Address Ranges
localnet 10.0.0.0/255.0.0.0
localnet 172.16.0.0/255.240.0.0
localnet 192.168.0.0/255.255.0.0
localnet 127.0.0.1/255.255.255.255

\##  Internet Address Ranges
localnet 36.96.0.0/255.128.0.0
localnet 59.191.240.0/255.128.0.0
……

# issue
When executing the proxychains4，  it will prompt a lot of information 【＃ of localnet exceed 64.】
Is there an option to close this prompt? If not consider whether to add this feature?

**Comment by rofl0r** [comment]
why do you add public internet ranges to localnet to begin with ?

**Comment by Arnosir** [comment]
@rofl0r Because I want the designated public network request does not take the agent.

**Comment by rofl0r** [comment]
well, seems you are the only one doing that so far.
anyway, if you need more than 64 localnets, edit this line in core.h and recompile
```
#define     MAX_LOCALNET 64
```

**Comment by Arnosir** [comment]
@rofl0r  I think this scene will be a lot in China, such as FE using npm install to install some programs, npm package does not through the agent, and  the package dependency to download through the agent.

Finally , Thanks a lot.
