### ISSUE TITLE
proxychains-ng ssh connection question

### ISSUE THREAD

**Issue by Fomovet** [rofl0r/proxychains-ng#172]
System and Proxychains-ng version:
- macOS 10.12.4
- proxychains-ng-4.12

**normal connection：**
```
➜ ssh root@41.93.25.175            
Last login: Wed May  3 02:35:02 2017 from 41.93.25.175
[root@seattle ~]#
```
**connection will automatically disconnect：**
```
➜ proxychains4 ssh root@41.93.25.175
[proxychains] config file found: /usr/local/etc/proxychains.conf
[proxychains] preloading /usr/local/lib/libproxychains4.dylib
[proxychains] DLL init: proxychains-ng 4.12-git-1-gbb3df1e
[proxychains] Strict chain  ...  127.0.0.1:1086  ...  42.63.75.115:22  ...  OK
Last login: Wed May  3 02:39:06 2017 from 42.63.75.115:22
[root@seattle ~]# Connection to 45.63.35.175 closed by remote host.
Connection to 41.93.25.175closed.
➜
```
If used`➜ proxychains4 ssh root@41.93.25.175`connection will soon be disconnected  I am searching for a long time on net. But no use. please help or try to give some ideas 
thanks in advance.

**Comment by Fomovet** [comment]
update title

**Comment by rofl0r** [comment]
does it help if you change the timeout variables in proxychains.conf ?
from the conf:
```
# Some timeouts in milliseconds
tcp_read_time_out 15000
tcp_connect_time_out 8000
```
also, i did use proxychains in the past with ssh and i don't think i experienced such a problem.
maybe it's the fault of the proxy ? in such case it may help if you make ssh send pings more often: http://stackoverflow.com/questions/25084288/keep-ssh-session-alive

**Comment by Fomovet** [comment]
**You're a good person Thank you very much The problem has been solved**
Reference material：http://stackoverflow.com/questions/19161960
