### ISSUE TITLE
Time out  "!!!need more proxies!!!

### ISSUE THREAD

**Issue by Enniari** [rofl0r/proxychains-ng#174]
Dear Team;
When I tired to scan all port using Proxychains with nmap I got a time out error "!!! need more proxies !!!"
even if I used three proxies from the same server (not localhost), after scanning around 300 first ports I got the error from all of the three proxies that I have(after that Proxychains switching to next socket in the list it gave the same error):
!!! need more proxies!!!
[proxychains] Dynamic chain ... xx.xxx.xx.xxx:9060  timeout
[proxychains] Dynamic chain ... xx.xxx.xx.xxx:9061  timeout
[proxychains] Dynamic chain ... xx.xxx.xx.xxx:9062  timeout

!! need more proxies!!!
[proxychains] Dynamic chain ... xx.xxx.xx.xxx:9060  timeout
[proxychains] Dynamic chain ... xx.xxx.xx.xxx:9061  timeout
[proxychains] Dynamic chain ... xx.xxx.xx.xxx:9062  timeout
.
.
After few seconds it continue scanning but escaping hundreds of ports !! 
I tried other options using in the config file, but didn't work, citing:
- Increase time out for tcp_read_time_out:150000000, tcp_connect_time_out:80000000;
- use dynamic_chain, strict_chain ....(one uncommented)
- Having proxy_dns (uncommented)

Can you please give me a hand ?

NB: I used socks4, I tested the sockets and it worked properly, the command that I use:
proxychains4 nmap  -p 1-65535 -r xxxxx.onion -oX result.xml

Kind regards.
Saad.

**Comment by rofl0r** [comment]
well, apparently the connection to the proxies fails for some reason.
as for "escaping hundreds of ports": that's normal if you use unreliable proxies.
if you want to find all open ports reliably in such case your best bet is to do several scans over the entire range and filter out duplicates.

**Comment by Enniari** [comment]
Thanks for your quick response  :+1:

**Comment by ICMP01** [comment]
Hello everybody, I have the same problem. Even adding new addresses (socks4 or 5) connections make several jumps, and hardly the result is expected. For example, web scans..
