### ISSUE TITLE
How to change the used DNS Server?

### ISSUE THREAD

**Issue by Againstreality** [rofl0r/proxychains-ng#178]
Hi, maybe i am totaly stupid but we use proxychains on all our Linux and Windows machines with a specific DNS Server. which works fine. But our Mac User cant because proxychains_ng always uses the google DNS.
I cant find a config File to change this. Can you help?

**Comment by rofl0r** [comment]
proxychains uses either the system dns server via libc routines, or when remote_dns is enabled does the lookup on the server. so i suppose you can just edit /etc/hosts and thats it.

**Comment by tangxinfa** [comment]
Accoding to this article [Changing proxychains' "hardcoded" DNS server ](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=5&cad=rja&uact=8&ved=0ahUKEwiU0L_b4ODXAhWLw1QKHV42DdYQFghJMAQ&url=http%3A%2F%2Fcarnal0wnage.attackresearch.com%2F2013%2F09%2Fchanging-proxychains-hardcoded-dns.html&usg=AOvVaw0d8OU-lhUkWk4g_pFm95lj), proxychains accept DNS_SERVER envirement variable, you can change it as you like.

      export DNS_SERVER=8.8.8.8
      proxychains firefox

**Comment by rofl0r** [comment]
@tangxinfa that is true for proxychains 3.1, but not for proxychains-ng.

**Comment by tangxinfa** [comment]
@rofl0r I use [proxychains-ng on Archlinux](https://www.archlinux.org/packages/community/x86_64/proxychains-ng/), DNS_SERVER envirement variable is works, this also use by the [proxyresolv](https://raw.githubusercontent.com/rofl0r/proxychains-ng/e527b9ee64f86f708b1ec952e01d2a0cbe9a9350/src/proxyresolv) tool.

**Comment by rofl0r** [comment]
proxyresolv is just a bonus, it will not be installed by default, and proxychains-ng itself doesnt use it. i looked at that package and it does nothing special, so there's no way DNS_SERVER could influence `proxychains4` program.
