### ISSUE TITLE
proxychains hangs without doing anything

### ISSUE THREAD

**Issue by Cris70** [rofl0r/proxychains-ng#179]
Hi, I'm trying to proxify nylas-mail (see https://github.com/nylas/nylas-mail/issues/104), but when I start proxychains I have the following behavior:

```
cristiano@xmper8q3 [~]$ proxychains4 -f /etc/proxychains.conf /usr/bin/nylas-mail
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib64/libproxychains4.so
```
...and nothing else. nylas-mail does not show its window, nothing more is output in the CLI.

Any hint?

I'm on openSUSE Tumbleweed fully updated.

TIA
Cris

**Comment by rofl0r** [comment]
please report output from debug mode. you need to recompile passing the following options to configure: `CFLAGS=-DDEBUG ./configure`

**Comment by Cris70** [comment]
The privately compiled proxychains works ok (nylas-mail does not work even when proxified, but that's another story).  
OpenSUSE Tumbleweed has v4.11 in its repos, maybe that's the difference.
Thank you!
Cris

**Comment by rofl0r** [comment]
looking at that nylas issue, maybe you need to enable the localnet for 127.0.0.x in proxychains.conf (it is already there as a commented out template in the default config).

**Comment by Cris70** [comment]
Thank you @rofl0r ! Changing the configuration as per your suggestion made it work!!
