### ISSUE TITLE
some applications not supported 

### ISSUE THREAD

**Issue by 1a1a11a** [rofl0r/proxychains-ng#182]
for example https://github.com/Optiminer/OptiminerZcash

**Comment by rofl0r** [comment]
your post is not very helpful. what do you expect me to do, download the program, compile it, and try to find the bug for you? that's not how it works...

**Comment by 1a1a11a** [comment]
Oh, sorry, I didn't mean that, I just have no idea why it hangs after printing out the initial message. I hope if you can point me to some direction that I might be able to find the bug or solve the problem. Thank you!

**Comment by rofl0r** [comment]
Ah, it hangs. first bit of information successfully submitted. anything else i should know about your issue?
