### ISSUE TITLE
Enable and Disable proxychains-ng

### ISSUE THREAD

**Issue by Newbiesc** [rofl0r/proxychains-ng#185]
Hi, i have an application that i want to use this proxychains. This application will be running all the time. My question is, Is there is a method/ a command to tell the proxychains to enable using proxy or to disable using proxy? Because the application will be execute once and also the proxychains will always hook to that application right?

**Comment by rofl0r** [comment]
no, that is not possible. also it's questionable whether it would make sense since you cannot un-proxify existing connections... but it would theoretically be possible to implement it using a signal handler for a specific signal such as SIGUSR1 that sets a global flag and depending on whether it is set or not the hooked functions would just call the original libc function, or do the usual redirects. but then applications might use that signal for some other purpose, so proxychains would then turn off and on "randomly"...

**Comment by Newbiesc** [comment]
First of all, thanks for your reply.
That would be great. Can you please add that feature (the global flag)? Or maybe you can tell me the correct position must i put it in the source code? In which file?

**Comment by rofl0r** [comment]
no, i won't add it... but in short, the change would involve installing a signal handler for SIGUSR1 from init() which sets global variable and depending on it you call true_connect() etc from hook functions

```
int disable_proxychains = 0;
void sigh(int x) {
  disable_proxychains = !disable_proxychains;
}
init() {
signal(SIGUSR1, sigh);
...
}

int connect(a, b, c) {
  if (disable_proxychains) return true_connect(a, b, c);
  ...
}

int sendto(a, b, c) {
  if (disable_proxychains) return true_sendto(a,b,c);
  ...
}
```
etc. the same repeated for all libc functions that are hooked (grep for `true_`).

**Comment by Newbiesc** [comment]
Ok, sir thanks for the info. But maybe you can explain a little about my problem here. 
1.  i add the "if (disable_proxychains) ..." code in every hooked functions and i add a debug message in that if. but when i send the signal, the debug message only appear in the close() function. the random chain message still appear.

2. when i send the signal, do every apps that use the proxychains get the signal, or only the one that the PID point to?

**Comment by rofl0r** [comment]
2) only the one with the specified PID
1) show your code i guess ?

**Comment by Newbiesc** [comment]
here is a part of the libproxychains:
int connect(int sock, const struct sockaddr *addr, unsigned int len) {
	if (disable_proxychains) {
		proxychains_write_log(LOG_PREFIX "bypass connect\n");
		return true_connect(sock, addr, len);
	}
	INIT();
	PFUNC();


and here is the script that i run with proxychains4

count=0
max=60
delay=2
noLimit=0

while [ 1 = 1 ];
do sleep $delay;count=$(($count + 1));
wget -qO- -T 8 https://ipinfo.io
if [[ $count -ge $max && $noLimit = 0 ]]
then
exit 1;
fi
done;

**Comment by Newbiesc** [comment]
Here is the output i get:
....
[proxychains] bypass close
[proxychains] Signal registered
[proxychains] Test DLL init: proxychains-ng 4.12
[proxychains] bypass close
[proxychains] Signal registered
[proxychains] Test DLL init: proxychains-ng 4.12
[proxychains] Random chain  ...  xxx.xxx.xxx.xxx:1080  ...  xxx.xxx.xxx.xxx:80  ...  OK
xxx.xxx.xxx.xxx[proxychains] bypass close
[proxychains] Signal registered
[proxychains] Test DLL init: proxychains-ng 4.12
[proxychains] bypass close

**Comment by rofl0r** [comment]
sigh. you're not running one long-living process as you initially told, you're running many short-living jobs from a script. that means nothing prevents you to run wget from inside your script with or without proxychains, according to external input (maybe presence of a specifically named file).

**Comment by Newbiesc** [comment]
Well, it just a test of the original program. As i did another debug, the close function called twice, and the 2nd one read the disable_proxychains variable correctly while the 1st one get it from the initial variable declaration. But that give me a conclusion to make the variable more global to be used by the lib.
Anyway, thanks a lot of your creation and your help sir. GBU.
