### ISSUE TITLE
in mac 10.12.4 there is a error

### ISSUE THREAD

**Issue by buzai** [rofl0r/proxychains-ng#188]
@xxxxx[21:39:38]:/usr/local/Cellar/proxychains-ng/4.11/etc$proxychains4 curl ip.gs
[proxychains] config file found: /usr/local/Cellar/proxychains-ng/4.11/etc/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib

**Comment by buzai** [comment]
System Integrity Protection status: enabled (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: disabled
	Filesystem Protections: disabled
	Debugging Restrictions: enabled
	DTrace Restrictions: enabled
	NVRAM Protections: enabled
	BaseSystem Verification: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.

**Comment by rofl0r** [comment]
i can't see any error.

**Comment by rofl0r** [comment]
see https://github.com/rofl0r/proxychains-ng/issues/78 you probably gotta turn of SIP completely
