### ISSUE TITLE
New Proxychains Release

### ISSUE THREAD

**Issue by samirotiv** [rofl0r/proxychains-ng#191]
Hi,

Please make a new release to reflect the latest commit for download.

Best,
Samir.

**Comment by quydo** [comment]
[`_****_`](

> 

- [ ] 

- @1. url

)

**Comment by rofl0r** [comment]
there have been only 2 minor fixes, i guess it would be easier for you to either just apply those 2 patches on top of the 4.12 tarball, or grab a github tarball from the latest commit id.

**Comment by rofl0r** [comment]
4.13 is now available...
