### ISSUE TITLE
Question about proxychains-ng

### ISSUE THREAD

**Issue by mdnpro** [rofl0r/proxychains-ng#192]
Hi
I have a question that might looks stupid!
When my pc (Server A) connects to a server (Server B) using proxychains-ng and send a request to a server (Server C) what information about my pc (Server A) revels to Server C?( ip? nameserver? what? )
I'm using Server proxychains-ng to send a request to a server but that server realizes that request has not been sent from actual server that should be. Actually it understand that requst was sent by using proxy.

thanks

**Comment by rofl0r** [comment]
it depends on the protocol and application. for example you might proxify a HTTP connection, but your browser sends cookies and other unique data that could be tracked back to you.
i assume that in your scenario "Server B" is the proxy. if it is the only proxy you're using, someone eavesdropping on it can see the incoming and outgoing connections as well as the unencrypted SOCKS headers, so he knows quite well about your activity.

typically proxychains is used with remote_dns turned on, so all DNS requests are done on the proxy, in which case no DNS lookup info from your PC gets leaked.
so if there are no leaks inside the protocol/application data itself, server C will only see a connection originating from server B.
