### ISSUE TITLE
How to build on msys2 (windows) ?

### ISSUE THREAD

**Issue by eromoe** [rofl0r/proxychains-ng#193]
Hi, I'd like to use this tool in my msys2 env, but I can't build it because 

```
cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/nameinfo.o src/nameinfo.c
src/nameinfo.c:1:10: fatal error: sys/socket.h: No such file or directory
 #include <sys/socket.h>
          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:81: src/nameinfo.o] Error 1


```

**Comment by rofl0r** [comment]
if your build environment does not offer sys/socket.h, there's no way it could ever work, i'm afraid. also, i doubt if msys actually implements a dynamic loader that is compatible with LD_PRELOAD. i guess there's no way to make this work on M$ OS.
