### ISSUE TITLE
Question about build system (dropped autotools?)

### ISSUE THREAD

**Issue by hosiet** [rofl0r/proxychains-ng#194]
I'm just wondering why proxychains4 dropped autotools, which was used in proxychains3.

When it comes to cross-platform, obviously autotools is the best option. CMake is also a good option. Handwritten Makefiles / configure scripts is rather limited.

**Comment by rofl0r** [comment]
1) CMake sucks in every regard
2) Autotools sucks in that:
 - generated code is huge, often way bigger than all the code in the project
   in the case of proxychains, getting rid of autotools shrinked the tarball about 90% iirc
 - it is hard to read,write, and understand the M4 gibberish and its utterly underdocumented
 - but it's portable, and well-established, so i try to mimic all aspects of its user-facing interface
