### ISSUE TITLE
Use proxychains-ng on ios

### ISSUE THREAD

**Issue by karmamaster** [rofl0r/proxychains-ng#196]
Hello,
Can I use proxychains-ng on IOS? if yes can you provide the release version for it 👍 👍 

Thanks at first.

**Comment by rofl0r** [comment]
i've seen this: https://github.com/Qusic/proxychains-ios - no idea if it's any good though.

**Comment by karmamaster** [comment]
So your version can not run on IOS, right?

**Comment by rofl0r** [comment]
the repo i linked to does use my version... but it seems to require some additional stuff.

**Comment by karmamaster** [comment]
thanks, i will try it and be back with the result

**Comment by karmamaster** [comment]
Hello,
When I tried to build your src I get this error:

```
proxychains/src/nameinfo.c:8:5: error: conflicting types for 'getnameinfo'
int getnameinfo(const void *sa, socklen_t salen, 
    ^
/Applications/Xcode8.3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/usr/include/netdb.h:272:17: note: 
      previous declaration is here
int             getnameinfo(const struct sockaddr * __restrict, socklen_t,
                ^
1 error generated.

```
Can you take a look at this?

Thanks.

**Comment by rofl0r** [comment]
yeah, proxychains only works on a per-application basis. on a real computer you can "trick" though and start your shell (bash) with proxychains, so all apps started from that shell will be automatically proxified.

**Comment by karmamaster** [comment]
So there is no way to apply proxychains to whole system, right?

**Comment by rofl0r** [comment]
no

but using linux's iptables firewall it is possible to configure a system in a way it routes all traffic over a proxy (and drops the traffic than can not be proxified) - but that is probably not applicable to iOs.

**Comment by karmamaster** [comment]
Yeah, I got it. Do you have any else communicate channel beside github? like facebook, skype or something like that? Make friends are never be so bad :D

**Comment by rofl0r** [comment]
not really. though the README mentions the IRC channel which can be used for discussion related to proxychains.

**Comment by ienthach** [comment]
Hello
After use MSHookFunction to hook functions, proxychains-ng can run on iOS. 
Most of apps is work fine with proxy but some app still crash.
Could you support for iOS?

**Comment by rofl0r** [comment]
> Could you support for iOS?

i don't have neither iOS devices nor development environment, but i'm willing to merge support for it if somebody can come up with a reasonably clean PR.

**Comment by ienthach** [comment]
Thank you. i will wait it happen.
