### ISSUE TITLE
Running app on Mac OS X

### ISSUE THREAD

**Issue by sitemate** [rofl0r/proxychains-ng#20]
Is it possible to open .app files with proxychains? Now if I type ./proxychains4 open /Applications/Firefox.app it fails with an error `dyld: could not load inserted library: ./libproxychains4.dylib`
Although ../libproxychains4.dylib is the correct relative path and command ./proxychains4 curl icanhazip.com works fine. 
Is there any restriction to run only daemons and shell programms? 
Thanks

**Comment by fly-away** [comment]
Chrome sends all your stuff to google, so what is the point to use proxies at all with chrome?
Its like walking down the street naked but with hat on.
