### ISSUE TITLE
proxychains-ng 4.12 not available on sourceforge

### ISSUE THREAD

**Issue by pranavk** [rofl0r/proxychains-ng#206]
https://sourceforge.net/projects/proxychains-ng/files/

Is it by mistake or there are no plans to make it available there from now? I was updating the package in fedora where the sourceforge URL is mentioned against the Sources. I can change it to github, ofcourse, but if you plan to upload the tarball to SF, then I wouldn't bother.

**Comment by rofl0r** [comment]
oops, yeah i had temporarily no access to sf.net. its there now and should be ready for dl in a few mins
