### ISSUE TITLE
[bug report] custom prefix path cause `couldnt locate libproxychains4.so`

### ISSUE THREAD

**Issue by livc** [rofl0r/proxychains-ng#207]
related issue: https://stackoverflow.com/questions/36325239/proxychains-ng-couldnt-locate-libproxychains4-so

solution:
if using custom prefix like `prefix=~/usr`, he must change https://github.com/rofl0r/proxychains-ng/blob/master/src/main.c#L42 and https://github.com/rofl0r/proxychains-ng/blob/master/src/main.c#L43 from `"/usr/lib",` `"/usr/local/lib",` to `"~/usr/lib"` `"~/usr/local/lib"`.

It essential for those don't have root permission.

**Comment by rofl0r** [comment]
actually, you can run `./proxychains4` straight from the build directory... 
anyway. which prefix did you use when running `./configure` ?
if you used `./configure --prefix=$HOME/usr` then everything should work as expected without having to change stuff in main.c...
so i think your problem is PEBKAC.

**Comment by livc** [comment]
Custom `--prefix=` will cause `couldnt locate libproxychains4.so`. Because proxychains-ng will search for the `libproxychains4.so` in the directory `/usr/lib` instead of the path user set.
As I know, it's not the only one case, many people have encountered this problem like the stackoverflow question I listed.

**Comment by rofl0r** [comment]
when you configured proxychains, did you use the character `~` to denote your home dir ? this will not work since that is shell expansion, and proxychains doesnt use the shell.
you need to use `/home/username` literally.

**Comment by livc** [comment]
I saw regex in source code so I tried both `~` and `/home/username`. Neither works.

**Comment by rofl0r** [comment]
you're wrong.

```
root:/$ cd /home/
root:/home$ mkdir foo
root:/home$ cd foo/
root:/home/foo$ tar xf /src/tarballs/proxychains-ng-4.12.tar.xz
root:/home/foo$ cd proxychains-ng-4.12/
root:/home/foo/proxychains-ng-4.12$ ./configure --prefix=/home/foo/usr
checking whether netinet/in.h defines s6_addr16 ... yes
checking whether $CC defines __OpenBSD__ ... no
Done, now run make && make install
root:/home/foo/proxychains-ng-4.12$ make -j8 >/dev/null 2>&1 && make install
./tools/install.sh -D -m 644 libproxychains4.so /home/foo/usr/lib/libproxychains4.so
./tools/install.sh -D -m 755 proxychains4 /home/foo/usr/bin/proxychains4
root:/home/foo/proxychains-ng-4.12$ make install-config
./tools/install.sh -D -m 644 src/proxychains.conf /home/foo/usr/etc/proxychains.conf
root:/home/foo/proxychains-ng-4.12$ cd ..
root:/home/foo$ proxychains4 curl google.com
[proxychains] config file found: /home/foo/usr/etc/proxychains.conf
[proxychains] preloading /home/foo/usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.12
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0[proxychains] Stri
ct chain  ...  127.0.0.1:9050  ...  timeout
curl: (7) Couldn't connect to server
root:/home/foo$

```

**Comment by livc** [comment]
Yes, you are right. I'm sorry that I forgot to type the command `curl` which caused 
```
➜  proxychains-ng git:(master) ./proxychains4 -f ~/etc/proxychains.conf  google.com
[proxychains] config file found: /home/lizhao/etc/proxychains.conf
[proxychains] preloading ./libproxychains4.so
proxychains can't load process....: No such file or directory
```

**Comment by Azuresonance** [comment]
Solved the same issue by editing the main.c source code. Nothing else works.

**Comment by rofl0r** [comment]
> Solved the same issue by editing the main.c source code. Nothing else works.

what did you change ?
