### ISSUE TITLE
How to get local port on Mac

### ISSUE THREAD

**Issue by CoXier** [rofl0r/proxychains-ng#209]
Here is a config file from other's website.

    strict_chain
    proxy_dns 
    remote_dns_subnet 224
    tcp_read_time_out 15000
    tcp_connect_time_out 8000
    localnet 127.0.0.0/255.0.0.0
    quiet_mode

    [ProxyList]
    socks5  127.0.0.1 1080

In the end line, there is a port `1080`. **I want to know how to get my local port.** Thanks in advance. Have a good day.😊

**Comment by rofl0r** [comment]
"how to get my local port" ? i don't get the question. please be more specific.

**Comment by CoXier** [comment]
I want to know what `1080` is meaning and how can I get the number on my device.

**Comment by rofl0r** [comment]
you need a proxy, and then put ip and port of the proxy.
you could for example install and then put the port used by tor there (usually 9050 or 9150)

**Comment by CoXier** [comment]
Thanks for your reply.

I do not know I should create the issue in this repo or shadowsocks. So I ask it on `stackexchange`.

Here is the qeustion link : https://unix.stackexchange.com/questions/412962/using-shadowsocks-with-command-line-tools
