### ISSUE TITLE
doesnt work on mac 

### ISSUE THREAD

**Issue by deret00000** [rofl0r/proxychains-ng#210]
Does not work on Mac os Sierra 10.12.4
The problem is that the proxy specified in the config does not work. As if simply ignored.

In the log, only the following: 
$ proxychains4 curl XXX.ru/123.php
[proxychains] config file found: /usr/local/etc/proxychains.conf
[proxychains] preloading ./libproxychains4.dylib
///site answer////

How can I try to solve the problem?

**Comment by rofl0r** [comment]
see #78

**Comment by deret00000** [comment]
thntx 4 answer. No it works with curl ( need to use /usr/bin/local/curl). 

But it dont work with Firefox 
MacBook-Pro-Alexey:proxychains-ng alexeymikeda$ proxychains4 /Applications/Firefox.app/Contents/MacOS/Firefox
[proxychains] config file found: /usr/local/etc/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.12_1/lib/libproxychains4.dylib
Segmentation fault: 11

**Comment by rofl0r** [comment]
well, there are some issues in mac support, which i unfortunately can't debug due to lack of a mac. you are of course free to launch **your** debugger and dig into it, and then report your findings here.

**Comment by xiaohui-zhangxh** [comment]
per https://zhuanlan.zhihu.com/p/21281236 , this is SIP issue, when SIP is disabled, it works.

```shell
reboot
# Hold option Key
# press Command + R when system recovery screen presents.
# Choose language, click Terminal of Utilities from top bar
csrutil disable
reboot
```

**Comment by rofl0r** [comment]
yes, exactly as i mentioned in my first reply here. good job not reading. it's even mentioned in README.
