### ISSUE TITLE
couldnt find configuration file: No such file or directory

### ISSUE THREAD

**Issue by dncmn** [rofl0r/proxychains-ng#217]
to do according this page 
http://shawnelee88.github.io/2015/07/10/proxychains-shadowsocks%E7%A5%9E%E5%99%A8/
but 
I run into this problems this "couldnt find configuration file: No such file or directory"

**Comment by rofl0r** [comment]
citing README.md:

>   [optional] sudo make install-config (installs proxychains.conf)
