### ISSUE TITLE
Feature Request: localnet configuration ipv6 support

### ISSUE THREAD

**Issue by adamyi** [rofl0r/proxychains-ng#218]
It would be nice to support ipv6 localnet configuration (e.g. ::1/128)

**Comment by ralequi** [comment]
It is probably necessary as i get in proxychains4 apt update something like:

`Ign:84 http://es.archive.ubuntu.com/ubuntu xenial-updates/restricted Translation-en
Ign:51 http://security.ubuntu.com/ubuntu xenial-security/universe Translation-es_ES16 
4% [Connecting to localhost (::1)] ...  ::1:27016 <--socket error or timeout!
<--socket error or timeout!
[proxychains] Random chain  ...  127.0.0.1:8123  ...  ::1:27016 [proxychains] Random chain  ...  127.0.0.1:8123  ...  ::1:27016 <--socket error or timeout!
`

**Comment by rofl0r** [comment]
PR welcome. it's kinda hard to develop a feature when you can't test it.

**Comment by jsrobson10** [comment]
Maybe someone could create a fork? I can't work on/test this issue because I don't have ipv6.
