### ISSUE TITLE
How to cancel the proxy ?

### ISSUE THREAD

**Issue by erstens** [rofl0r/proxychains-ng#219]
I have configure the port in 1087 .I want to cancel the proxy . How to do ?
Thanks .

**Comment by rofl0r** [comment]
sorry, i don't understand what you mean with "cancel a proxy".
proxychains does not run a proxy on your machine, if you mean that.

**Comment by erstens** [comment]
Disabled proxy ?

**Comment by rofl0r** [comment]
no idea what you are talking about. maybe you find a friend who speaks much better english than you, so he can help you to make your point.

or you post your question in chinese and someone reading this can figure out what you want...
