### ISSUE TITLE
proxychain docker pull command

### ISSUE THREAD

**Issue by hsafe** [rofl0r/proxychains-ng#220]
Hi,
Can someone explain why proxychaining the docker command to pull images fails?I get the error from an embargoed country like below,while every other commands in the bash behaves correctly(I am behind a tor circuit):
Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<html><body><h1>403 Forbidden</h1>\nSince Docker is a US company, we must comply with US export control regulations. In an effort to comply with these, we now block all IP addresses that are located in Cuba, Iran, North Korea, Republic of Crimea, Sudan, and Syria. If you are not in one of these cities, countries, or regions and are blocked, please reach out to https://support.docker.com\n</body></html>\n\n"

**Comment by rofl0r** [comment]
docker is written in GO language, which 1) sucks 2) is statically linked 3) doesn't use libc.
any of those reasons except 1 prevents proxychains from working. as a workaround, if docker supports http proxies you may try to proxify tinyproxy instead and let docker connect to that.
