### ISSUE TITLE
Request: add possibility to run proxychains without config file via command line params

### ISSUE THREAD

**Issue by Justsoos** [rofl0r/proxychains-ng#223]
first, proxychains-ng is a great work.
I did not find how to invoke proxychains-ng by argument like:
`$proxychains --proxy=http://uri` 
or
`$proxychains --port 2018 --ip 1.1.1.1` 
which might not exist yet, if that, could you add such helpful capacity?? 
另外，作者是中国人？哈，握手
用conf文件调用实在是太笨重了

**Comment by rofl0r** [comment]
this can easily be done with a script wrapper around proxychains that writes the config file according to your command line arguments. see this post here for an example https://github.com/rofl0r/proxychains-ng/issues/246#issuecomment-401019706

**Comment by Justsoos** [comment]
thx, go on at https://github.com/rofl0r/proxychains-ng/issues/246#issuecomment-416108132 , here close
