### ISSUE TITLE
how to build proxychains-ng statically

### ISSUE THREAD

**Issue by moralrebuild** [rofl0r/proxychains-ng#225]
I don't want to get the shared library file, i.e. libproxychains4.so, generated. Is there a way to make a static compiling for this amazing tool? I must admit that I have very little experience with C/C++

**Comment by rofl0r** [comment]
nope.

first paragraph in README:

>  ProxyChains is a UNIX program, that hooks network-related libc functions
>  in DYNAMICALLY LINKED programs via a preloaded DLL (dlsym(), LD_PRELOAD)
>  and redirects the connections through SOCKS4a/5 or HTTP proxies.
>  It supports TCP only (no UDP/ICMP etc).

in short, dynamic linking is required to hook libc functions.

**Comment by moralrebuild** [comment]
Thanks for clarification. But the excerpt makes me a little bit confusion. Have my DNS queries been forwarded through my socks5 proxy ?

**Comment by rofl0r** [comment]
i don't know what you did, but in case you used dynamically linked proxychains-ng and had the `proxy_dns` option set in your config, then at least the DNS lookups **should** have been proxified. to have 100% certainty, you can check with wireshark....

**Comment by moralrebuild** [comment]
good point. "It support TCP only" is a misleading statement. It should say the proxified traffic only in tcp mode, not the original traffic limited to tcp.

**Comment by rofl0r** [comment]
well, the README is intended to be read completely, and not just one paragraph (after asking about things that are explained in that first paragraph).
