### ISSUE TITLE
does proxychains4 has some sort of cache?

### ISSUE THREAD

**Issue by lowprofileusername** [rofl0r/proxychains-ng#227]
I use proxychains for squid proxy.

and I block facebook.com with squid 
acl fb2 dstdomain ".facebook.com"
http_reply_access deny fb2
 http_access deny CONNECT fb2

however I changed .facebook.com to .goole.com and reload squid

proxychains still block facebook.com but not google.com but if I use the squid proxy directly . google.com is not accessable. and facebook.com is fine.

So I was wondering if proxychains has cache that caused the settings not updated.

thanks.

**Comment by rofl0r** [comment]
no. when you use proxy_dns setting, it forwards all DNS to proxy. if not enabled, it will do live lookup via libc.
