### ISSUE TITLE
OpenBSD 6.3 fails to compile Proxychains-ng

### ISSUE THREAD

**Issue by b-irl** [rofl0r/proxychains-ng#228]
# Current version, from Github.
# Proxychains4 (ng? forget) was installed successfully in 6.1 and worked moderately in 6.2, but it died in 6.3, so I removed it and sought to re-install.
# Urgent!

$ cd proxychains-ng-master         
                                                                            
$ ls
AUTHORS   COPYING   Makefile  README    TODO      VERSION   configure src       tests     tools

$ ./configure --prefix=/usr --sysconfdir=/etc
checking whether $CC defines __APPLE__ ... no
checking whether $CC defines __FreeBSD__ ... no
checking whether $CC defines __OpenBSD__ ... yes
checking whether OpenBSDs fclose() (illegally) calls close() ... no
checking whether $CC defines __sun ... no
checking whether we can use -Wl,--no-as-needed ... yes
checking what's the option to use in linker to set library name ... --soname
Done, now run gmake && gmake install

$ gmake   # note: also attempted with just "make"
cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -DIS_BSD   -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/nameinfo.o src/nameinfo.c
printf '#define VERSION "%s"\n' "$(sh tools/version.sh)" > src/version.h
cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -DIS_BSD   -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/version.o src/version.c
cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -DIS_BSD   -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/core.o src/core.c
src/core.c:844:59: error: too many arguments to function call, expected 4, have 6
        if(service) getservbyname_r(service, NULL, &se_buf, buf, sizeof(buf), &se);
                    ~~~~~~~~~~~~~~~                              ^~~~~~~~~~~~~~~~
/usr/include/netdb.h:306:1: note: 'getservbyname_r' declared here
int             getservbyname_r(const char *, const char *, struct servent *,
^
1 error generated.
gmake: *** [Makefile:82: src/core.o] Error 1

**Comment by rofl0r** [comment]
try now.
