### ISSUE TITLE
quiet mode is not quiet, still spit unexpected message "proxychains can't load process....: No such file or directory"

### ISSUE THREAD

**Issue by moralrebuild** [rofl0r/proxychains-ng#229]
I think the quiet mode is used to suppress any kind of messages, no matter success or failure. the program exit code can help identify the boolean result.  So it is more like a bug than expected behavior. Can anyone help fix it or let me know which code part should be taken care? Thanks in advance!

**Comment by rofl0r** [comment]
"proxychains can't load process" is an error message.
it's a diagnostic facility, which means it's always active and you should better fix your usage.
