### ISSUE TITLE
git parsing options error with proxychains4 

### ISSUE THREAD

**Issue by rhuab** [rofl0r/proxychains-ng#232]
I execute the following command:
`proxychains4 -q git whatchanged --no-abbrev -M "--format=commit %H%ntree %T%nparent %P%nauthor %aN <%aE> %ai%ncommitter %cN <%cE> %ci%n%n%w(76,4,4)%s%n%n%b" -n 1024 cc78cbdf8871f096d6d59d165be026d5370d6833 ^6c817af9c54bb52ebeb76f571692ec77c47ae4db` in the root directory of git repo and get the following error:
`fatal: invalid --pretty format: commit`. 
If I wipe "proxychains4" out this command works well. My git version is 2.7.4 and I use the latest commit of proxychains on the master branch.

**Comment by rofl0r** [comment]
can you check with `strace -f  -s 1024 -o log.txt COMMAND_HERE` what actually happens.
write one logfile (`log.txt`) with proxychains, other without, then compare in the log the `execve` line that starts `git` command.

what OS is this, btw ?

**Comment by rhuab** [comment]
The difference is:
` execve("/usr/bin/git", ["/usr/bin/git", "whatchanged", "--no-abbrev", "-M", "--format=commit %H%ntree %T%nparent %P%nauthor %aN <%aE> %ai%ncommitter %cN <%cE> %ci%n%n%w(76,4,4)%s%n%n%b", "-n", "1024", "cc78cbdf8871f096d6d59d165be026d5370d6833", "^6c817af9c54bb52ebeb76f571692ec77c47ae4db"], [/* 33 vars */]) = 0`
` execve("/usr/bin/git", ["/usr/bin/git", "whatchanged", "--no-abbrev", "-M", "--format=commit %H%ntree %T%nparent %P%nauthor %aN <%aE> %ai%ncommitter %cN <%cE> %ci%n%n%w(76,4,4)%s%n%n%b", "-n", "1024", "cc78cbdf8871f096d6d59d165be026d5370d6833", "^6c817af9c54bb52ebeb76f571692ec77c47ae4db"], [/* 33 vars */]) = 0`

My system is Ubuntu-16.04.

**Comment by rofl0r** [comment]
look again into the log with proxychains, there will be another EXECVE line later on that runs /usr/bin/git. i need that one.

**Comment by rhuab** [comment]
sorry, I think I should provide more information in details about my system here:
1. First, the git command is at /usr/bin/git, and I create a shell script at /usr/local/bin/git, the content is `proxychains4 -q /usr/bin/git $@`.
2. If I type "which git", the result is "/usr/local/bin/git"
Now I execute command `git whatchanged --no-abbrev -M "--format=commit %H%ntree %T%nparent %P%nauthor %aN <%aE> %ai%ncommitter %cN <%cE> %ci%n%n%w(76,4,4)%s%n%n%b" -n 1024 cc78cbdf8871f096d6d59d165be026d5370d6833 ^6c817af9c54bb52ebeb76f571692ec77c47ae4db`, the final command should be `proxychains4 -q /usr/bin/git whatchanged --no-abbrev -M "--format=commit %H%ntree %T%nparent %P%nauthor %aN <%aE> %ai%ncommitter %cN <%cE> %ci%n%n%w(76,4,4)%s%n%n%b" -n 1024 cc78cbdf8871f096d6d59d165be026d5370d6833 ^6c817af9c54bb52ebeb76f571692ec77c47ae4db`
3. Now I get log.txt via strace, I can see several EXECVE lines here:
`execve("/usr/local/bin/git", ["git", "whatchanged", "--no-abbrev", "-M", "--format=commit %H%ntree %T%nparent %P%nauthor %aN <%aE> %ai%ncommitter %cN <%cE> %ci%n%n%w(76,4,4)%s%n%n%b", "-n", "1024", "cc78cbdf8871f096d6d59d165be026d5370d6833", "^6c817af9c54bb52ebeb76f571692ec77c47ae4db"], [/* 33 vars */]) = 0`
`execve("/usr/local/bin/proxychains4", ["proxychains4", "-q", "/usr/bin/git", "whatchanged", "--no-abbrev", "-M", "--format=commit", "%H%ntree", "%T%nparent", "%P%nauthor", "%aN", "<%aE>", "%ai%ncommitter", "%cN", "<%cE>", "%ci%n%n%w(76,4,4)%s%n%n%b", "-n", "1024", "cc78cbdf8871f096d6d59d165be026d5370d6833", "^6c817af9c54bb52ebeb76f571692ec77c47ae4db"], [/* 33 vars */]) = 0`
`execve("/usr/bin/git", ["/usr/bin/git", "whatchanged", "--no-abbrev", "-M", "--format=commit", "%H%ntree", "%T%nparent", "%P%nauthor", "%aN", "<%aE>", "%ai%ncommitter", "%cN", "<%cE>", "%ci%n%n%w(76,4,4)%s%n%n%b", "-n", "1024", "cc78cbdf8871f096d6d59d165be026d5370d6833", "^6c817af9c54bb52ebeb76f571692ec77c47ae4db"], [/* 36 vars */]) = 0`

**Comment by rofl0r** [comment]
the difference is 
without proxychains: 
```
"--format=commit %H%ntree %T%nparent %P%nauthor %aN <%aE> %ai%ncommitter %cN <%cE> %ci%n%n%w(76,4,4)%s%n%n%b"
```

with proxychains
```
"--format=commit", "%H%ntree", "%T%nparent", "%P%nauthor", "%aN", "<%aE>", "%ai%ncommitter", "%cN", "<%cE>", "%ci%n%n%w(76,4,4)%s%n%n%b"
```
i.e. the format string is split into pieces rather than a single string. it's probably the fault of your /usr/local/bin/git wrapper

it should look like
```
proxychains4 -q /usr/bin/git "$@"
```
