### ISSUE TITLE
Proxychains for single directory

### ISSUE THREAD

**Issue by testprooject** [rofl0r/proxychains-ng#238]
Hi How to set proxychains to run in a single directory automatically in user login?

**Comment by rofl0r** [comment]
please reformulate the question so it makes sense.

in case you mean that you want your entire shell session "proxified", you can run `proxychains4 bash`.

**Comment by testprooject** [comment]
I'm using "proxychains4 bash" command but it starts proxychains4 in all of my server.
I just want to enable it in a directory like : /root/test
Is it possible?

**Comment by rofl0r** [comment]
proxychains works on a per-program basis, not on a per-directory, whatever you mean with that.
