### ISSUE TITLE
Diffrence to default proxychains?

### ISSUE THREAD

**Issue by anonymouz4** [rofl0r/proxychains-ng#239]
What exactly is the diffrence between proxychains from `apt-get install proxychains` and proxychains-ng from `apt-get install proxychains-ng`?

Which is newer and which is better?

I noticed that -q doesn't work on the default proxychains.

**Comment by rofl0r** [comment]
proxychains is unmaintained since > 10 years, this one not.
for a list of differences, see the README and look for the changes since 3.1.
