### ISSUE TITLE
How to custom config path with DYLD_INSERT_LIBRARIES insert?

### ISSUE THREAD

**Issue by qokelate** [rofl0r/proxychains-ng#243]
same as the title,  I want to use `DYLD_INSERT_LIBRARIES` env to load,  possible?

```
DYLD_INSERT_LIBRARIES=/tmp/libproxychains4.dylib curl ip.cn
```

**Comment by rofl0r** [comment]
yes that should work. why don't you just try it out ?

**Comment by qokelate** [comment]
Yes, it works, but i want to use custom conf path, like `proxychains4 -f '/tmp/111.conf' curl ip.cn`, how to set /tmp/111.conf ?

**Comment by rofl0r** [comment]
use the source, luke:
src/main.c:
```c
#include "common.h"
...
        /* Set PROXYCHAINS_CONF_FILE to get proxychains lib to use new config file. */
        setenv(PROXYCHAINS_CONF_FILE_ENV_VAR, path, 1);
```

src/common.h
```
#define PROXYCHAINS_CONF_FILE_ENV_VAR "PROXYCHAINS_CONF_FILE"
```

**Comment by qokelate** [comment]
ok, thanks a lot!
