### ISSUE TITLE
proxychains doesn't work I updated it from proxychains-3 to proxychains-ng(v4)

### ISSUE THREAD

**Issue by c02y** [rofl0r/proxychains-ng#244]
I use old proxychains (v3) with shadowsocksr in terminal, and after I use my system package manager to update proxychains to proxychains-ng, proxychains4 doesn't work like proxychains. I already enable shadowsocksr in the background, and when I run proxychains4 in termina such as:

    $ proxychains4 youtube-dl "https://www.youtube.com/xxx"

the link I can open in my Chrome Browser using switchyomega+shadowsocksr.

It prints:

    [proxychains] config file found: /etc/proxychains.conf
    [proxychains] preloading /usr/lib64/libproxychains4.so
    [proxychains] DLL init: proxychains-ng 4.11
    [proxychains] DLL init: proxychains-ng 4.11
    \[youtube] iRcKFbksTTY: Downloading webpage
    [proxychains] Strict chain  ...  127.0.0.1:9050  ...  timeout
    ERROR: Unable to download webpage: <urlopen error [Errno 111] Connection refused> (caused by 
    URLError(ConnectionRefusedError(111, 'Connection refused'),))

and 

    >> proxyresolv4 www.facebook.com
    [proxychains] DLL init: proxychains-ng 4.11
    [proxychains] DLL init: proxychains-ng 4.11
    [proxychains] Strict chain  ...  127.0.0.1:9050  ...  timeout

Facebook cannot be accessed normally in here, and it cannot be accessed in terminal using proxychains-ng but work perfectly using proxychains (v3)

**Comment by rofl0r** [comment]
`[proxychains] Strict chain  ...  127.0.0.1:9050  ...  timeout`

is proxy running on port 9050 ? it seems not.

`[proxychains] DLL init: proxychains-ng 4.11`

4.11 is not latest version

`proxyresolv4 www.facebook.com`

proxyresolv is deprecated and is only shipped as a bonus, it is not installed by default. which distro's package are you using?

**Comment by c02y** [comment]
Sorry about that, I already changed the port in /etc/proxychains.conf to 1080 which is the same port used by switchyomega extension in Chrome Browser, the proxychains4 won't work even I reboot my computer.

    >> proxychains4 youtube-dl "https://www.youtube.com/watch?v=xxxxx"
    [proxychains] config file found: /etc/proxychains.conf
    [proxychains] preloading /usr/lib64/libproxychains4.so
    [proxychains] DLL init: proxychains-ng 4.11
    [proxychains] DLL init: proxychains-ng 4.11
    [youtube] iRcKFbksTTY: Downloading webpage
    [proxychains] Strict chain  ...  127.0.0.1:1080  ...  www.youtube.com:443 <--socket error or timeout!
    ERROR: Unable to download webpage: <urlopen error [Errno 111] Connection refused> (caused by URLError(ConnectionRefusedError(111, 'Connection refused'),))

and 

    >> proxychains4 --version                                                                                                                                          
    [proxychains] config file found: /etc/proxychains.conf
    [proxychains] preloading /usr/lib64/libproxychains4.so
    proxychains can't load process....: No such file or directory

So what is the problem?

BTW:
openSUSE Tumbleweed 64-bit

The version is the latest version in openSUSE Tumbleweed repo.

**Comment by rofl0r** [comment]
try latest git version which is 4.13. does your proxy require user/password?

**Comment by c02y** [comment]
Check my last reply, I updated it.

And my user/password in my in config files for shadowsocksr files which works fine using switchyomega+shadowsocksr in chrome.

And the old version of proxychains (v3) works fine, I only updated it to proxychains-ng, nothing else changes.

**Comment by rofl0r** [comment]
you need to put the username and password into the config

**Comment by c02y** [comment]
I figured it out, I have to change the last line of /etc/proxychains.conf from 

    socks4  127.0.0.1 9050

to 

    socks5  127.0.0.1 1080

which is exactly used by switchyomega. No username/password are needed.

Now it works, thanks.

**Comment by rofl0r** [comment]
ah, so it was PEBKAC after all as i expected. glad you solved it.
