### ISSUE TITLE
Doubt chain proxychains and dante socks proxy

### ISSUE THREAD

**Issue by n1n741** [rofl0r/proxychains-ng#247]
How i could chain proxychains and dante socks proxy with the purpose to redirect the traffic to other server?

I have two remote servers in different networks 

I would like to know if i could chain these programs with a secure connection like ssh 

In proxychains should i add the ip of the public server or only allow proxies ip like socks5 127.0.0.1 9050 ? 

What configuration is needed?

Server1 (use proxychains and it will chains the connection of the server2) - > then i go throught the traffic of the server 2 

Thank you so much

**Comment by rofl0r** [comment]
run ssh on server1 and some socks server on server2 (let's say on port 8080)

then open encrypted ssh conn to server1 like this
`ssh -D 1080 user@server1`
that'll open port 1080 on your localhost as a socks5 tunneled over ssh

then put this into your proxychains.conf
```
[ProxyList]
socks5 127.0.0.1 1080
socks5 ip-of-server2 8080
```

you could also run inside the ssh session on server1 an ssh -D command to connect to server2, like this `ssh -D 2080 user2@server2`

and on your client put into your proxychains.conf
```
[ProxyList]
socks5 127.0.0.1 1080
socks5 127.0.0.1 2080
```

**Comment by n1n741** [comment]
Thank you crack :)
