### ISSUE TITLE
Mac OS X 10.13.6 (17G65) Ruby related program crashes when using proxychains-NG

### ISSUE THREAD

**Issue by DavidHuang61** [rofl0r/proxychains-ng#248]
Mac OS X 10.13.6 (17G65) Ruby related program crashes when using proxychains-NG

[proxychains] config file found: /Users/huangyanpeng/.proxychains/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.dylib
[proxychains] DLL init: proxychains-ng 4.13
[proxychains] DLL init: proxychains-ng 4.13
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17/openssl.bundle: [BUG] Segmentation fault at 0x0000000000000004
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]

[ruby_2018-07-12-192403_huangyanpengdeMacBook-Air.crash.zip](https://github.com/rofl0r/proxychains-ng/files/2190880/ruby_2018-07-12-192403_huangyanpengdeMacBook-Air.crash.zip)

**Comment by rofl0r** [comment]
could you print a backtrace using gdb or lldb ?

**Comment by rofl0r** [comment]
lookup "mac os x lldb print backtrace" in your favorite search engine (baidu?) and follow the instructions. thanks!

**Comment by rofl0r** [comment]
no, this doesnt run proxychains with arguments.
according to https://developer.apple.com/library/archive/documentation/IDEs/Conceptual/gdb_to_lldb_transition_guide/document/lldb-command-examples.html

you need to run
`lldb -- proxychains4 ruby myprog.rb`
and then `run` and when you get the segfault `bt`

**Comment by DavidHuang61** [comment]
> no, this doesnt run proxychains with arguments.
according to https://developer.apple.com/library/archive/documentation/IDEs/Conceptual/gdb_to_lldb_transition_guide/document/lldb-command-examples.html
> you need to run
lldb -- proxychains4 ruby myprog.rb
and then run and when you get the segfault bt

Sorry, I tried my best.

But it doesn't look like any useful output.

(lldb) target create "proxychains4"
Current executable set to 'proxychains4' (x86_64).
(lldb) settings set -- target.run-args  "curl" "cip.cc"
(lldb) run
Process 77926 launched: '/Users/huangyanpeng/Downloads/proxychains-ng/proxychains4' (x86_64)
[proxychains] config file found: /Users/huangyanpeng/.proxychains/proxychains.conf
[proxychains] preloading /Users/huangyanpeng/Downloads/proxychains-ng/libproxychains4.dylib
Process 77926 stopped
* thread #2, stop reason = exec
    frame #0: 0x000000010002f19c dyld`_dyld_start
dyld`_dyld_start:
->  0x10002f19c <+0>: popq   %rdi
    0x10002f19d <+1>: pushq  $0x0
    0x10002f19f <+3>: movq   %rsp, %rbp
    0x10002f1a2 <+6>: andq   $-0x10, %rsp
Target 0: (curl) stopped.
(lldb) bt
* thread #2, stop reason = exec
  * frame #0: 0x000000010002f19c dyld`_dyld_start

![20180713-120242](https://user-images.githubusercontent.com/17465541/42671825-c2356002-8694-11e8-9098-98edc5507f19.png)

**Comment by rofl0r** [comment]
related #211
related #205

probable cause #195

**Comment by DavidHuang61** [comment]
Thank you very mach!

**Comment by rofl0r** [comment]
yeah, i'm not sure how to fix it, sorry.
without spending a lot of time on mac debugging this issue, the only fix for it i can think of is 2-fold:
1) use proxychains4 to proxify accesses of a simple proxy-server software like tinyproxy or microsocks
2) add a "simple" mode to proxychains which doesn't use threads at all and basically works like proxychains 3.11. use this simple mode to proxify ruby to connect to the proxyserver on localhost from (1).

**Comment by DavidHuang61** [comment]
No problem, I will try it.

**Comment by mahong125** [comment]
你好，请问这个问题你有解决吗？ @DavidHuang61

**Comment by noahxinhao** [comment]
你也遇到了么@mahong125

**Comment by DavidHuang61** [comment]
> 你好，请问这个问题你有解决吗？ @DavidHuang61

恢复的有点晚，我现在用ClashX，很方便。
