### ISSUE TITLE
Pass Proxy-Authorization as is in CONNECT request

### ISSUE THREAD

**Issue by aliowka** [rofl0r/proxychains-ng#259]
Hi rofl0r

When connecting to upstream proxy, Proxychains uses credentials which statically defined in 
config file.

But modern proxy providers such as [Luminati](https://luminati.io) use dynamic credentials. 
In fact they have a whole API based on altering a username part of credentials string. 
So in order to manage the pool of proxies, client should be able to change a username on demand.

In case of HTTPS connection the only way to pass Proxy-Authorization headers to proxy provider is with CONNECT request. Proxychains uses static Proxy-Aythoriation header, making application unable to use Luminati.

I understand that the change might be complex, but I think this worth it, since this allows Proxychains
to work in front of most popular modern proxy providers.

**Comment by rofl0r** [comment]
how would such dynamic change look like ?

what would be the prefered way to configure such dynamic change on proxychains side ?

**Comment by aliowka** [comment]
That's a good question. 
I just understood that for this purpose proxychained client itself should send a CONNECT request, which means, it should be aware that it's being proxied, and this is equal to just manage the upstream proxy by it's own. 
Sorry for wasting your time.
