### ISSUE TITLE
It not work for crossover return this.

### ISSUE THREAD

**Issue by yuanbi** [rofl0r/proxychains-ng#262]
[proxychains] DLL init: proxychains-ng 4.13
ERROR: ld.so: object '/usr/local/lib/libproxychains4.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

**Comment by rofl0r** [comment]
dude, your english sucks.
anyway, your problem is that you're trying to proxify a 32bit application with a 64bit shared object. you need to compile proxychains with a 32-bit crosscompiler (or `CC="gcc -m32"` using multilib) and use the 32 bit version for that app.

**Comment by yuanbi** [comment]
> dude, your english sucks.
> anyway, your problem is that you're trying to proxify a 32bit application with a 64bit shared object. you need to compile proxychains with a 32-bit crosscompiler (or `CC="gcc -m32"` using multilib) and use the 32 bit version for that app.


I do it but failed.

**Comment by rofl0r** [comment]
```
make clean
CC="gcc -m32" ./configure
make
./proxychains4 myapp
```

**Comment by yuanbi** [comment]
> ```
> make clean
> CC="gcc -m32" ./configure
> make
> ./proxychains4 myapp
> ```

thank u.dude.
