### ISSUE TITLE
proxychains not worked with curl

### ISSUE THREAD

**Issue by ostapqwert** [rofl0r/proxychains-ng#264]
proxychains4 -f ~/proxchains/proxychains-tor.conf curl https://check-host.net/ip
[proxychains] config file found: /Users/alexander/proxchains/proxychains-tor.conf
[proxychains] preloading /usr/local/lib/libproxychains4.dylib
return my real ip! 
but curl --socks5 127.0.0.1:9050 https://check-host.net/ip
worked correct! 

$ cat proxychains-tor.conf

strict_chain
proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000
socks5 	127.0.0.1 9050

**Comment by rofl0r** [comment]
your config file is invalid.
