### ISSUE TITLE
DLL init not successful

### ISSUE THREAD

**Issue by ykhandler** [rofl0r/proxychains-ng#265]
Hi, i'm trying to compile this project to run it on my Android phone. And it was successful, but when i run it, it seams the dll is not init, because there is no DLL INIT: 4.12 proxychains message.

It appear like this:
# ./proxychains4 busybox wget -qO- https://ipinfo
# [proxychains] config file found: /system/dome/proxychains/lib/proxychains.conf
# [proxychains] preloading ./libproxychains4.so
# wget: note: TLS certificate validation not # implemented
# {
# ...
# }

And the result also shows that the wget not getting into the proxy. Because the result is the same with or without the proxychains. 

Any idea how to resolve this.

**Comment by rofl0r** [comment]
my first guess is that the busybox binary is statically linked, which prevents proxychains from working.

**Comment by ykhandler** [comment]
@rofl0r, yes, you're correct. That is the problem. But another issue came out when i compile the wget dynamically:
 ./proxychains4 ./wget -qO- https://ipinfo.io/geo
[proxychains] config file found: /system/dome/proxychains/proxychains.conf
[proxychains] preloading ./libproxychains4.so
CANNOT LINK EXECUTABLE "./wget": cannot locate symbol "getservbyname_r" referenced by "/system/dome/proxychains/libproxychains4.so"...
Aborted

while the wget can run normally without proxychains.

**Comment by rofl0r** [comment]
i've added a fix, please test with latest git.
