### ISSUE TITLE
centos7 1804 cant configure

### ISSUE THREAD

**Issue by bugmeng** [rofl0r/proxychains-ng#266]
[root@centos7-1804 proxychains-ng-4.13]# ./configure 
checking whether $CC defines __APPLE__ ... ./configure:行32: cc: 未找到命令
no
checking whether $CC defines __FreeBSD__ ... ./configure:行32: cc: 未找到命令
no
checking whether $CC defines __OpenBSD__ ... ./configure:行32: cc: 未找到命令
no
checking whether $CC defines __sun ... ./configure:行32: cc: 未找到命令
no
checking whether we can use -Wl,--no-as-needed ... no
checking what's the option to use in linker to set library name ... 
cannot find an option to set library name

@rofl0r thk

**Comment by bugmeng** [comment]
run 
yum -y install gcc automake autoconf libtool make
success! 

thks

**Comment by rofl0r** [comment]
you don't need any of automake autoconf libtool
