### ISSUE TITLE
proxychains v4.13 swallows errors

### ISSUE THREAD

**Issue by tipu** [rofl0r/proxychains-ng#267]
working as expected:
```
$ proxychains curl google.com                                                                                                                                           [11:56:05]
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
...
```

intentionally sending bad commands:
```
$ proxychains curl2 google.com
proxychains can't load process....: No such file or director

$ proxychains garbageinput
proxychains can't load process....: No such file or directory
```
i expect that the breaking commands would result in more helpful output.

**Comment by rofl0r** [comment]
> i expect that the breaking commands would result in more helpful output.

well, at least you don't **demand** it.

**Comment by tipu** [comment]
what can i say, i'm a reasonable individual.

**Comment by rofl0r** [comment]
so what kind of message would you suggest

**Comment by tipu** [comment]
`"<input>" isn't a valid command` or 
`"<input>" returned an exit code > 0` or something? 

i don't feel strongly about these at all, admittedly i don't have a good intuition as to what would replace the existing message.

**Comment by rofl0r** [comment]
well what you suggest there is misleading... the issue is that the program you typed can't be executed because it can't be found in $PATH (which is pretty much what the existing message suggests, i.e. "error running the process" "cause file does not exist")

**Comment by tipu** [comment]
fair enough. i'll close this out.
