### ISSUE TITLE
Read the proxies from the command line

### ISSUE THREAD

**Issue by WillSing** [rofl0r/proxychains-ng#270]
My company has a lot of servers scattered in different networks (it's a nightmare) and I frequently need to use proxychains to pass through some of the proxies and hop into a different network.

I believe a new parameter allowing the user to pass the list of proxies directly from the command line would be a great feature.

Example:
```
proxychains4 -s http:10.0.1.1:3128,socks5:172.16.0.1:1080 ssh user@172.16.10.30
```

**Comment by rofl0r** [comment]
that can be easily solved with a wrapper script, see
https://github.com/rofl0r/proxychains-ng/issues/246#issuecomment-401019706 for an example.
btw proxychains-ng's config file now supports proxy urls like socks4://ip:port since 1c8f8e4e7e31e64131f5f5e031f216b557f7b5ed
