### ISSUE TITLE
proxychains-ng nmap scan socket error or timeout But agent firefox normal

### ISSUE THREAD

**Issue by ganguoyin** [rofl0r/proxychains-ng#272]
![default](https://user-images.githubusercontent.com/31980393/50395038-8c33ac00-079c-11e9-825b-d28bbb907999.png)

**Comment by rofl0r** [comment]
nmap is too low level to be properly proxified behind its back. try using its built-in proxy functionality instead.

```
# nmap --help | grep prox
  --proxies <url1,[url2],...>: Relay connections through HTTP/SOCKS4 proxies
```
