### ISSUE TITLE
Can proxychains redirect apt update traffic to the proxy sever ?

### ISSUE THREAD

**Issue by ryanhuang1014** [rofl0r/proxychains-ng#277]
I have configured the proxychains correctly, and test it with curl and wget. However, when I use the term 'proxychains sudo apt update', I find that the proxychains will not redirect my traffic. Hence, is it because the proxychains only proxies the certain number of applications ? or other issues ? How can I redirect my traffic when I use 'sudo apt update' ?

**Comment by rofl0r** [comment]
try `sudo bash` and then inside the new root shell `proxychains4 apt update`

**Comment by ryanhuang1014** [comment]
Thanks a lot, it works! 
Actually, I tried 'proxychains bash; sudo apt update', but it did not work.
Anyway, thx for your help.

**Comment by rofl0r** [comment]
the trick is that you need to become root before running proxychains. otherwise the dynlinker will refuse dlopen attempts for security reasons.
