### ISSUE TITLE
Incompatible with dig

### ISSUE THREAD

**Issue by cnrat** [rofl0r/proxychains-ng#280]
- proxychains-ng version: [Release 4.14](https://github.com/rofl0r/proxychains-ng/releases/tag/v4.14)
- operation system: CentOS 7 X86_64 
- kernel version: 5.0.7-1.el7.elrepo.x86_64
- `dig` version: DiG 9.9.4-RedHat-9.9.4-73.el7_6
- path to reproduce the problem

```
proxychains4 dig +tcp +short myip.opendns.com @resolver1.opendns.com
```

- error log output

```
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/local/lib/libproxychains4.so
dig: isc_socket_connect: invalid use of multicast address
```

- expect return (without proxychains4)

> This should return your IP address.

```
60.147.212.23
```

**Comment by rofl0r** [comment]
turn off `proxy_dns`

**Comment by rofl0r** [comment]
or use 8.8.8.8

**Comment by cnrat** [comment]
> turn off `proxy_dns`

Thank you for reply. If I turn off `proxy_dns`, I will risk leaking DNS request to my local DNS server which I'm not willing to.

Can you please explain why the DNS request I send to `resolver1.opendns.com` can not be send through  proxy? I do aware I will get the IP of my proxy server indeed if it works as I thought.

**Comment by rofl0r** [comment]
> dig: isc_socket_connect: invalid use of multicast address

it seems dig has an overzealous piece of code in it that checks whether ip addresses returned by the resolver match specific criteria which its programmer think are incorrect, instead of simply using the address, and therefore preventing proper functioning with the standard remote dns subnet used by proxychains-ng.

maybe you should file a bug with `dig` authors explaining the issue and recommending that they should remove the idiotic check.

**Comment by cnrat** [comment]
> > dig: isc_socket_connect: invalid use of multicast address
> 
> it seems dig has an overzealous piece of code in it that checks whether ip addresses returned by the resolver match specific criteria which its programmer think are incorrect, instead of simply using the address, and therefore preventing proper functioning with the standard remote dns subnet used by proxychains-ng.
> 
> maybe you should file a bug with `dig` authors explaining the issue and recommending that they should remove the idiotic check.

Thank you very much. I have proved `nslookup` worked smoothly with proxychains4. And I have noticed the explain about 'remote_dns_subnet' in conf file.

The 'nslookup' could be a acceptable walk around replacing `dig`.

Thank you again, this is a great help.

**Comment by rofl0r** [comment]
there's also `drill` btw. it's like `dig` but it's written from scratch and without the cruft sticking to `dig`.
i still believe you should file a bug with `dig` authors though, so they become aware of the issue.

**Comment by cnrat** [comment]
For more information, any one want to use `nslookup` should use a `-vc` option force it making TCP request or your request will still leak to local DNS server as proxychains supports TCP only.
