### ISSUE TITLE
Squid only works with `-N`

### ISSUE THREAD

**Issue by blueyed** [rofl0r/proxychains-ng#281]
When using `squid --foreground`, or not `-N` (which skips creating workers) proxychains appears to have no effect.

The README says:

> You can use it with servers, like squid

Am I missing something?  (Squid 4.5)

I've also found https://github.com/haad/proxychains, which appears to be active - what is the relationship?  (it appears to support env vars for example)

**Comment by blueyed** [comment]
It is using `fork()`: https://github.com/squid-cache/squid/blob/63ed43c5e8b0477977f6598ff426295a2bc0e762/src/main.cc#L1860-L1872

**Comment by rofl0r** [comment]
> appears to have no effect.

what makes you think so?

> Am I missing something

it worked when i last tested it like 3 years ago on my musl-libc based distro sabotage linux.

> haad/proxychains

https://github.com/rofl0r/proxychains-ng/wiki/quality-of-haad's-fork,-or-%22reasons-for-the-split%22

> which appears to be active

one commit in 2019, 2 in 2018

**Comment by blueyed** [comment]
> > appears to have no effect.
> 
> what makes you think so?

It does not go through my SOCKS proxy (Tor in a Docker container ("socks4 172.19.X.X 9050")) when using `--foreground`, but only with `-N`.
There is also no output from proxychains in non-quiet mode, which is expected I guess (since it would happen for the childs/workers).

> it worked when i last tested it like 3 years ago on my musl-libc based distro sabotage linux.

I am using Alpine Linux, which also uses musl.

I am using iptables for this now instead.

**Comment by rofl0r** [comment]
> I am using iptables for this now instead.

alright, you apparently solved the issue

**Comment by blueyed** [comment]
Yes, but I only had to dig into iptables because of this issue in the first place.

Fair enough to close it, since I cannot provide more information anyway.
