### ISSUE TITLE
Does proxychains-ng leak?

### ISSUE THREAD

**Issue by t4777sd** [rofl0r/proxychains-ng#283]
Looking at: /src/libproxychains.c

```
if(!((fam  == AF_INET || fam == AF_INET6) && socktype == SOCK_STREAM))
return true_connect(sock, addr, len);
```

My ability with C is very low, but it appears that true_connect is the actual original programs connection. And, this is saying if it is not ip4/ip6 + TCP, then to use that original function.

Theoretically, that means a program could utilize something like UDP to de-anonymize people, correct? If correct, is there any way to stop these leaks?

**Comment by rofl0r** [comment]
right. an evil program could for example detect proxychains by looking at environment vars and then use udp or something to betray you. therefore, you probably shouldn't use evil programs, or at least none that are proprietary and you can't read the sourcecode of (which you'd optimally compile yourself). Thus, the README states:

```
  ALWAYS MAKE SURE THAT PROXYCHAINS WORKS AS EXPECTED
  BEFORE USING IT FOR ANYTHING SERIOUS.
```

and gives instructions on how to do that. additionally, verbose mode is on by default so you can see whether the connections are routed over a proxy or not.
The reason non-TCP connections aren't prevented is that there could also be legit connections using unix sockets and the like. Also if we would start denying access to UDP to stop evil programs from leaking, we'd basically start playing whack-a-mole with the evil developer.

> is there any way to stop these leaks?

yeah, iptables based solutions or a router like @grugq's portal, as the README states as well.

**Comment by t4777sd** [comment]
Okay, it seems this does not seem serious for your use-case. Most people do not have the ability to read every single program line to make sure there is no UDP traffic that de-anonymizes them.

It would be nice if there was an --leak-prevention option. That way it can function similar to torsocks.
