### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by DarthLordMeilodaz** [rofl0r/proxychains-ng#285]
The document could not be saved, as it was not possible to write to /root/proxychains/src/proxychains.conf.
Check that you have write access to this file or that enough disk space is available.
The original file may be lost or damaged. Don't quit the application until the file is successfully written.

**Comment by rofl0r** [comment]
use sudo or su.

**Comment by DarthLordMeilodaz** [comment]
This message is coming from the file proxychains.conf when I try to save it. Do you hvae a youtube channel explaining the function of this program?

**Comment by rofl0r** [comment]
you need to be root to save stuff into /root. and no, there is no youtube channel.
