### ISSUE TITLE
Don't work with Python's webbrowser module

### ISSUE THREAD

**Issue by nlpsuge** [rofl0r/proxychains-ng#287]
How to reproduce:
 1. Open a Terminal for executing command
 2. Execute command: 
```proxychains4 bash```
 3. Execute Python script:
```
import webbrowser
webbrowser.open_new_tab('http://www.python.org')
```

http://www.python.org cannot be opened in browser. 

If I skip step 2, this url can be opened in browver.

**Comment by rofl0r** [comment]
sounds like you misconfigured your config file...

**Comment by nlpsuge** [comment]
@rofl0r I confirm that I'm using the correct configuration... I'v tested...

**Comment by nlpsuge** [comment]
Hi,

Any ideas?

**Comment by nlpsuge** [comment]
I think this issue should be relevant to this issue #45 .

This method ``` webbrowser.open_new_tab ``` will call the default browser. And the default browser is Chrome.

A workaround is set another browser to the default one like Firefox.

**Comment by rofl0r** [comment]
great. so we can close this as a duplicate of #45.
