### ISSUE TITLE
Proxychains-ng denaid

### ISSUE THREAD

**Issue by mne-uzhe-mozhno** [rofl0r/proxychains-ng#288]
Hi rofl0r. You are sorry for my level of English. I am from Ukraine, I am 14 years old and I am a girl. Please be softer with me.
This is problem. I downloaded proxychains-ng and it does not work. My operating system is Kali Linux.
I watched a lot of videos on YouTube and searched for a solution on the Internet. Nothing helps.
```
root@kali:~# proxychains4 wget -qo- wlan0.me
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.14-git-3-gde4460f
[proxychains] Strict chain  ...  192.166.219.46:3128  ...  wlan0.me:80 <--denied


root@kali:~# proxychains4 firefox
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.14-git-3-gde4460f
[proxychains] DLL init: proxychains-ng 4.14-git-3-gde4460f
[proxychains] DLL init: proxychains-ng 4.14-git-3-gde4460f
[proxychains] DLL init: proxychains-ng 4.14-git-3-gde4460f

(firefox-esr:10550): Gtk-WARNING **: 16:27:53.187: Theme parsing error: <data>:1:34: Expected ')' in color definition

(firefox-esr:10550): Gtk-WARNING **: 16:27:53.187: Theme parsing error: <data>:1:77: Expected ')' in color definition
[proxychains] DLL init: proxychains-ng 4.14-git-3-gde4460f
[proxychains] Strict chain  ...  185.62.190.60:8080  ...  2.21.89.57:80 [proxychains] DLL init: proxychains-ng 4.14-git-3-gde4460f
<--denied
[proxychains] Strict chain  ...  185.62.190.60:8080  ...  159.89.27.102:443 [proxychains] DLL init: proxychains-ng 4.14-git-3-gde4460f
[proxychains] DLL init: proxychains-ng 4.14-git-3-gde4460f
<--denied
[proxychains] Strict chain  ...  185.62.190.60:8080  ...  2.21.89.56:80 <--denied
[proxychains] Strict chain  ...  185.62.190.60:8080  ...  52.218.224.8:443 
```

And proxy-dns it disconnected. Everything tried  !!! I tried to be connected to the the different  proxy. Does not work proxychains-ng  ((((
Here my file of configuration.

```
# proxychains.conf  VER 4.x
#
#        HTTP, SOCKS4a, SOCKS5 tunneling proxifier with DNS.


# The option below identifies how the ProxyList is treated.
# only one option should be uncommented at time,
# otherwise the last appearing option will be accepted
#
#dynamic_chain
#
# Dynamic - Each connection will be done via chained proxies
# all proxies chained in the order as they appear in the list
# at least one proxy must be online to play in chain
# (dead proxies are skipped)
# otherwise EINTR is returned to the app
#
strict_chain
#
# Strict - Each connection will be done via chained proxies
# all proxies chained in the order as they appear in the list
# all proxies must be online to play in chain
# otherwise EINTR is returned to the app
#
#round_robin_chain
#
# Round Robin - Each connection will be done via chained proxies
# of chain_len length
# all proxies chained in the order as they appear in the list
# at least one proxy must be online to play in chain
# (dead proxies are skipped).
# the start of the current proxy chain is the proxy after the last
# proxy in the previously invoked proxy chain.
# if the end of the proxy chain is reached while looking for proxies
# start at the beginning again.
# otherwise EINTR is returned to the app
# These semantics are not guaranteed in a multithreaded environment.
#
#random_chain
#
# Random - Each connection will be done via random proxy
# (or proxy chain, see  chain_len) from the list.
# this option is good to test your IDS :)

# Make sense only if random_chain or round_robin_chain
#chain_len = 2

# Quiet mode (no output from library)
#quiet_mode

# Proxy DNS requests - no leak for DNS data
#proxy_dns 

# set the class A subnet number to use for the internal remote DNS mapping
# we use the reserved 224.x.x.x range by default,
# if the proxified app does a DNS request, we will return an IP from that range.
# on further accesses to this ip we will send the saved DNS name to the proxy.
# in case some control-freak app checks the returned ip, and denies to 
# connect, you can use another subnet, e.g. 10.x.x.x or 127.x.x.x.
# of course you should make sure that the proxified app does not need
# *real* access to this subnet. 
# i.e. dont use the same subnet then in the localnet section
#remote_dns_subnet 127 
#remote_dns_subnet 10
remote_dns_subnet 224

# Some timeouts in milliseconds
tcp_read_time_out 15000
tcp_connect_time_out 8000

### Examples for localnet exclusion
## localnet ranges will *not* use a proxy to connect.
## Exclude connections to 192.168.1.0/24 with port 80
# localnet 192.168.1.0:80/255.255.255.0

## Exclude connections to 192.168.100.0/24
# localnet 192.168.100.0/255.255.255.0

## Exclude connections to ANYwhere with port 80
# localnet 0.0.0.0:80/0.0.0.0

## RFC5735 Loopback address range
## if you enable this, you have to make sure remote_dns_subnet is not 127
## you'll need to enable it if you want to use an application that 
## connects to localhost.
# localnet 127.0.0.0/255.0.0.0

## RFC1918 Private Address Ranges
# localnet 10.0.0.0/255.0.0.0
# localnet 172.16.0.0/255.240.0.0
# localnet 192.168.0.0/255.255.0.0

# ProxyList format
#       type  ip  port [user pass]
#       (values separated by 'tab' or 'blank')
#
#       only numeric ipv4 addresses are valid
#
#
#        Examples:
#
#            	socks5	192.168.67.78	1080	lamer	secret
#		http	192.168.89.3	8080	justu	hidden
#	 	socks4	192.168.1.49	1080
#	        http	192.168.39.93	8080	
#		
#
#       proxy types: http, socks4, socks5
#        ( auth types supported: "basic"-http  "user/pass"-socks )
#
[ProxyList]
# add proxy here ...
# meanwile
# defaults set to "tor"
#socks4 	127.0.0.1 9050
http	185.62.190.60	8080``
```

**Comment by rofl0r** [comment]
well, i suppose your proxy doesn't work

**Comment by mne-uzhe-mozhno** [comment]
Well, even if I run tor. Nothing works.

**Comment by rofl0r** [comment]
i'd recommend to enable `proxy_dns`. make sure to put the right proxy for tor into the config.
`socks4 127.0.0.1 9050` should work. use curl to test, not firefox.

**Comment by alfadog32** [comment]
Hey were you able to resolve this? I'm having the same issue

**Comment by rofl0r** [comment]
@alfadog32 use a proxy that works. you can for starters test proxychains with some proxy running on localhost, like microsocks.

**Comment by CCinnovationsUK** [comment]
"use a proxy that works" isn't a fair answer. I'm currently facing the same issue, on a proxy that works, and am trying to figure out a solution.

**Comment by rofl0r** [comment]
and "proxychains doesn't work" isn't a valid question.

**Comment by catchorale** [comment]
You are not alone. I too hate this damn program that randomly works(or not).

**Comment by 911GH** [comment]
i got the same problem. did you sort this proble. i need help too

**Comment by spidy45man** [comment]
> Hi rofl0r. You are sorry for my level of English. I am from Ukraine, I am 14 years old and I am a girl. Please be softer with me. This is problem. I downloaded proxychains-ng and it does not work. My operating system is Kali Linux. I watched a lot of videos on YouTube and searched for a solution on the Internet. Nothing helps.
> 
> ```
> root@kali:~# proxychains4 wget -qo- wlan0.me
> [proxychains] config file found: /etc/proxychains.conf
> [proxychains] preloading /usr/lib/libproxychains4.so
> [proxychains] DLL init: proxychains-ng 4.14-git-3-gde4460f
> [proxychains] Strict chain  ...  192.166.219.46:3128  ...  wlan0.me:80 <--denied
> 
> 
> root@kali:~# proxychains4 firefox
> [proxychains] config file found: /etc/proxychains.conf
> [proxychains] preloading /usr/lib/libproxychains4.so
> [proxychains] DLL init: proxychains-ng 4.14-git-3-gde4460f
> [proxychains] DLL init: proxychains-ng 4.14-git-3-gde4460f
> [proxychains] DLL init: proxychains-ng 4.14-git-3-gde4460f
> [proxychains] DLL init: proxychains-ng 4.14-git-3-gde4460f
> 
> (firefox-esr:10550): Gtk-WARNING **: 16:27:53.187: Theme parsing error: <data>:1:34: Expected ')' in color definition
> 
> (firefox-esr:10550): Gtk-WARNING **: 16:27:53.187: Theme parsing error: <data>:1:77: Expected ')' in color definition
> [proxychains] DLL init: proxychains-ng 4.14-git-3-gde4460f
> [proxychains] Strict chain  ...  185.62.190.60:8080  ...  2.21.89.57:80 [proxychains] DLL init: proxychains-ng 4.14-git-3-gde4460f
> <--denied
> [proxychains] Strict chain  ...  185.62.190.60:8080  ...  159.89.27.102:443 [proxychains] DLL init: proxychains-ng 4.14-git-3-gde4460f
> [proxychains] DLL init: proxychains-ng 4.14-git-3-gde4460f
> <--denied
> [proxychains] Strict chain  ...  185.62.190.60:8080  ...  2.21.89.56:80 <--denied
> [proxychains] Strict chain  ...  185.62.190.60:8080  ...  52.218.224.8:443 
> ```
> 
> And proxy-dns it disconnected. Everything tried !!! I tried to be connected to the the different proxy. Does not work proxychains-ng (((( Here my file of configuration.
> 
> ```
> # proxychains.conf  VER 4.x
> #
> #        HTTP, SOCKS4a, SOCKS5 tunneling proxifier with DNS.
> 
> 
> # The option below identifies how the ProxyList is treated.
> # only one option should be uncommented at time,
> # otherwise the last appearing option will be accepted
> #
> #dynamic_chain
> #
> # Dynamic - Each connection will be done via chained proxies
> # all proxies chained in the order as they appear in the list
> # at least one proxy must be online to play in chain
> # (dead proxies are skipped)
> # otherwise EINTR is returned to the app
> #
> strict_chain
> #
> # Strict - Each connection will be done via chained proxies
> # all proxies chained in the order as they appear in the list
> # all proxies must be online to play in chain
> # otherwise EINTR is returned to the app
> #
> #round_robin_chain
> #
> # Round Robin - Each connection will be done via chained proxies
> # of chain_len length
> # all proxies chained in the order as they appear in the list
> # at least one proxy must be online to play in chain
> # (dead proxies are skipped).
> # the start of the current proxy chain is the proxy after the last
> # proxy in the previously invoked proxy chain.
> # if the end of the proxy chain is reached while looking for proxies
> # start at the beginning again.
> # otherwise EINTR is returned to the app
> # These semantics are not guaranteed in a multithreaded environment.
> #
> #random_chain
> #
> # Random - Each connection will be done via random proxy
> # (or proxy chain, see  chain_len) from the list.
> # this option is good to test your IDS :)
> 
> # Make sense only if random_chain or round_robin_chain
> #chain_len = 2
> 
> # Quiet mode (no output from library)
> #quiet_mode
> 
> # Proxy DNS requests - no leak for DNS data
> #proxy_dns 
> 
> # set the class A subnet number to use for the internal remote DNS mapping
> # we use the reserved 224.x.x.x range by default,
> # if the proxified app does a DNS request, we will return an IP from that range.
> # on further accesses to this ip we will send the saved DNS name to the proxy.
> # in case some control-freak app checks the returned ip, and denies to 
> # connect, you can use another subnet, e.g. 10.x.x.x or 127.x.x.x.
> # of course you should make sure that the proxified app does not need
> # *real* access to this subnet. 
> # i.e. dont use the same subnet then in the localnet section
> #remote_dns_subnet 127 
> #remote_dns_subnet 10
> remote_dns_subnet 224
> 
> # Some timeouts in milliseconds
> tcp_read_time_out 15000
> tcp_connect_time_out 8000
> 
> ### Examples for localnet exclusion
> ## localnet ranges will *not* use a proxy to connect.
> ## Exclude connections to 192.168.1.0/24 with port 80
> # localnet 192.168.1.0:80/255.255.255.0
> 
> ## Exclude connections to 192.168.100.0/24
> # localnet 192.168.100.0/255.255.255.0
> 
> ## Exclude connections to ANYwhere with port 80
> # localnet 0.0.0.0:80/0.0.0.0
> 
> ## RFC5735 Loopback address range
> ## if you enable this, you have to make sure remote_dns_subnet is not 127
> ## you'll need to enable it if you want to use an application that 
> ## connects to localhost.
> # localnet 127.0.0.0/255.0.0.0
> 
> ## RFC1918 Private Address Ranges
> # localnet 10.0.0.0/255.0.0.0
> # localnet 172.16.0.0/255.240.0.0
> # localnet 192.168.0.0/255.255.0.0
> 
> # ProxyList format
> #       type  ip  port [user pass]
> #       (values separated by 'tab' or 'blank')
> #
> #       only numeric ipv4 addresses are valid
> #
> #
> #        Examples:
> #
> #            	socks5	192.168.67.78	1080	lamer	secret
> #		http	192.168.89.3	8080	justu	hidden
> #	 	socks4	192.168.1.49	1080
> #	        http	192.168.39.93	8080	
> #		
> #
> #       proxy types: http, socks4, socks5
> #        ( auth types supported: "basic"-http  "user/pass"-socks )
> #
> [ProxyList]
> # add proxy here ...
> # meanwile
> # defaults set to "tor"
> #socks4 	127.0.0.1 9050
> http	185.62.190.60	8080``
> ```

first remove the comment '#' on dynamic_chain 
second add the comment on strict_chain
set the socks5 proxy has default like socks4 then just save the file .
if you are using firefox then go the firefox setting search network put the ip that you have set in proxychain 
eg 127.0.0.1 port 8080/9050
then save it and run the command on the terminal 
service tor start
proxychains firefox google.com
bing go you have done now

**Comment by rofl0r** [comment]
ok, this is an issue of 2019, the OP never responded, and i'm tired of having it popping up almost every week in my notifications. locking this now. feel free to open a new issue if you think there's a problem with proxychains-ng (but it's most certainly PEBKAC).
