### ISSUE TITLE
proxychains-ng not working with loopback vs. curl

### ISSUE THREAD

**Issue by brianwoo** [rofl0r/proxychains-ng#289]
In my proxychains.conf:

```
[ProxyList]
# add proxy here ...
# meanwile
# defaults set to "tor"
# socks4     127.0.0.1 9050
http     192.168.0.182 31337
```

Where 192.168.0.182 is my squid proxy server.  On the same host, I have a web server running on port 8080.

I am able to access the webserver through the proxy server and through the loopback interface with curl:
```
curl -x http://192.168.0.182:31337 http://127.0.0.1:8080
<html>...</html>...
```

However, if I use proxychains with curl:
```
proxychains4 -f proxychains.conf curl http://127.0.0.1:8080
[proxychains] config file found: proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.14-git-3-gde4460f
curl: (7) Failed to connect to 127.0.0.1 port 8080: Connection refused
```

I am quite new to proxychains, is this a bug in proxychains or am I not doing it correctly?

Thanks.

**Comment by rofl0r** [comment]
works for me. you seem to miss the line `[proxychains] Strict chain  ... 192.168.0.182:31337 ... http://127.0.0.1:8080` in your output, so i assume something in your config is wrong.

**Comment by brianwoo** [comment]
I actually have strict_chain in the file above the [proxychains] section.  

```
# cat proxychains.conf | grep -v ^#

strict_chain
proxy_dns 
localnet 127.0.0.0/255.255.255.0
tcp_read_time_out 15000
tcp_connect_time_out 8000

[ProxyList]
http 	192.168.0.182 31337
```

**Comment by rofl0r** [comment]
your localnet directive prevents all request to 127.0.0.0 endpoints to circumvent proxifying.

**Comment by brianwoo** [comment]
I have removed the localnet and proxy_dns directives from my config file but I am still getting the same error:

```
strict_chain
tcp_read_time_out 15000
tcp_connect_time_out 8000

[ProxyList]
http 	192.168.0.182 31337
```

```
proxychains4 -f proxychains.conf curl http://127.0.0.1:8080
[proxychains] config file found: proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.14-git-3-gde4460f
[proxychains] Strict chain  ...  192.168.0.182:31337  ...  127.0.0.1:8080 <--denied
curl: (7) Couldn't connect to server
```

**Comment by rofl0r** [comment]
127.0.0.1:8080 will point to the proxy server's localhost after connecting, not yours. anyway, i tested the scenario and it works. if you don't get it working look at the traffic with wireshark/tcpdump on the .182 host.
