### ISSUE TITLE
UDP support /IPv6 support

### ISSUE THREAD

**Issue by tony-mak** [rofl0r/proxychains-ng#29]
proxychain does not support UDP and ipv6, how about proxychain-ng.
Actually, is there any document about the change from original proxychain to proxychain-ng. Thank you :)

**Comment by baptx** [comment]
proxychains4 works well for IPv6 . But proxychains3 is still useful if we want want to force IPv4 usage. I don't think proxychains4 has an option to force IPv4 usage.
