### ISSUE TITLE
change proxy with command

### ISSUE THREAD

**Issue by mtalhagaoglu** [rofl0r/proxychains-ng#291]
i can't change my proxy with a terminal command. it change itself when a new connection request come. there is any option for changing proxy manuel?

**Comment by rofl0r** [comment]
"it change itself" -hmm what ?

please try to come up with a better, detailed description of what happens and what you wanna do.
http://www.catb.org/~esr/faqs/smart-questions.html

**Comment by mtalhagaoglu** [comment]
I'm trying to test some informations. To test this I have to login the site with these informations but the site doesn't give permission me to try 500 time in a row. So everytime I tried 450 times I have to wait 50 minutes but I don't want to do that. You know it's very boring situation so if I change my proxy every 450 trying, I will be successful. But there isn't any command for that or I don't know. Proxychains change proxy every connection request. I hope I can explain the situation. If I can't and if you want to help me about that you can contact me with direct message so I can send you screenshots

**Comment by rofl0r** [comment]
you can "script" proxychains by generating a config file on the fly such as in this example: https://github.com/rofl0r/proxychains-ng/issues/246#issuecomment-401019706 . so you simply generate a new config file after 450 password crack attempts.

**Comment by mtalhagaoglu** [comment]
There is any tutorial for make my custom config file?

**Comment by rofl0r** [comment]
yes, the example config file is full of descriptive text. you simply need to read it.
