### ISSUE TITLE
Proxychains forcing bind to 0.0.0.0 by default in ssh

### ISSUE THREAD

**Issue by shellster** [rofl0r/proxychains-ng#292]
Hi, we just ran across a non-intuitive "feature" of proxychains and proxychains-ng, that is a potential security nightmare if users are not aware.  I'm inclined to consider it a bug.

Normally if I run the following command, ssh will bind my dynamic proxy to localhost by default:
```
# ssh -fND 6666 root@<whatever>
# netstat -lpnt
 ...
 tcp     0     0     127.0.0.1:6666     0.0.0.0:*     LISTEN     20300/ssh
```

However, if I run the same command through proxychains-ng, my tunnel is bound to 0.0.0.0 instead:
```
# proxychains ssh -fND 6666 root@<whatever>
# netstat -lpnt
 ...
 tcp     0     0     0.0.0.0:6666     0.0.0.0:*     LISTEN     20306/ssh
```

It should be noted that proxychains does honor the localhost bind if you explicitly set it like so:
```
# proxychains ssh -fND 127.0.0.1:6666 root@<whatever>
# netstat -lpnt
 ...
 tcp     0     0     127.0.0.1:6666     0.0.0.0:*     LISTEN     10403/ssh
```

I think this is a serious bug.  If a user is unaware of this quirk and does a tunnel from a publicly accessible host, they are potentially opening that tunnel to the world without realizing it.

**Comment by rofl0r** [comment]
> It should be noted that proxychains does honor the localhost bind

yes, proxychains doesn't intercept bind() calls.

can you show the logic in openssh source that sets up the default bind (or not) ?

**Comment by shellster** [comment]
I think the relevant logic is in this file, though I'm not sure what the actual problem is: https://github.com/openssh/openssh-portable/blob/4d28fa78abce2890e136281950633fae2066cc29/sshconnect.c

**Comment by rofl0r** [comment]
this seems the place for outgoing connections. none the less, you could try to turn on debug output in ssh and look where the output differs between hooked/plain use.

**Comment by shellster** [comment]
You are right.  Sorry about that.  I'll look a little more closely when I get a chance.  For what it is worth, however tsocks does their similar proxying, is not triggering the above incorrect binding to the public IP.

**Comment by rofl0r** [comment]
i could imagine that the results of getnameinfo/getaddrinfo are slightly different. adding some debug printfs in that area could give clues.

**Comment by jephthai** [comment]
I played around with this a bit, and believe I figured it out.  SSH issues a `getaddrinfo()` prior to creating a socket to bind the port forward.  When it does this, if the forward spec does not contain a host or `:`, it will send a NULL pointer to `getaddrinfo()`.  Per the man page, I believe this case is not handled:

    If the AI_PASSIVE flag is not set in hints.ai_flags, then the  returned
    socket  addresses  will be suitable for use with connect(2), sendto(2),
    or sendmsg(2).  If node is NULL, then the network address will  be  set
    to  the loopback interface address (INADDR_LOOPBACK for IPv4 addresses,
    IN6ADDR_LOOPBACK_INIT for IPv6 address); this is used  by  applications
    that intend to communicate with peers running on the same host.

In my testing, the `AI_PASSIVE` flag is not set, but the code in `src/core.c` for `proxy_getaddrinfo()` does not recognize that it needs to fill in `127.0.0.1`.  Its call to `my_inet_aton` leaves the address portion all zeros, leading to a case where SSH will bind to `0.0.0.0`.  

I am not sure how the code should best handle this, otherwise I'd just submit a PR.  For me, this change is working correctly, though:

    $ git diff
    diff --git a/src/core.c b/src/core.c
    index a6f39df..b1d92ce 100644
    --- a/src/core.c
    +++ b/src/core.c
    @@ -879,7 +879,10 @@ int proxy_getaddrinfo(const char *node, const char *service, const struct addrin
                            goto err2;
            } else if(node) {
                    af = ((struct sockaddr_in *) &space->sockaddr_space)->sin_family;
    +       } else if(!(hints->ai_flags & AI_PASSIVE)) {
    +           inet_aton("127.0.0.1", &((struct sockaddr_in *)&space->sockaddr_space)->sin_addr);
            }
    +
            if(service) mygetservbyname_r(service, NULL, &se_buf, buf, sizeof(buf), &se);
     
            port = se ? se->s_port : htons(atoi(service ? service : "0"));

**Comment by rofl0r** [comment]
@jephthai good find and correct analysis.
your patch isn't correct though:
1) your new branch is also taken when my_inet_aton succeeded. it needs to check explicitly for node == NULL and !passive.
2) the sockaddr thing will have the right IP set, but not the right address family. to fix that
you need to pass it to either my_inet_aton which does that, or, preferably, put the binary values directly into the struct, like `memcpy(&...->sin_addr, "\x7f\0\0\1", 4);` or `memcpy(&...->sin_addr, (unsigned char[]){127,0,0,1}, 4);` plus setting both af and ...->sin_family to AF_INET.

**Comment by shellster** [comment]
Thanks to both of you for the quick turn-around.  I've pulled the latest and tested and confirmed that the issue is resolved.
