### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by anonu1** [rofl0r/proxychains-ng#293]
Hello, I'm having an issue with proxychains: I'm trying to connect a laptop to another laptop that is on VPN. Using an SSH proxy (-D) and firefox, I'm able to browse resources that are only available on the network; however, with proxychains, I'm not able to ping the same resources. I've set the proxy_dns, strict_chain, remote_dns_subnet, localnet and tcp_read/connect_time_out and set the socks4 proxy to be 127.0.0.1 and the port I used with -D. 

I'm guessing my problem has to do with my /etc/resolv.conf file. I'm not sure what nameserver to set in there. I would like for it to use the one that's only available internally on the VPN, is that possible?

I'm not able to ping the internal addresses I can browse on firefox, so I'm not sure what the issue is .

**Comment by rofl0r** [comment]
disable localnet

**Comment by anonu1** [comment]
@rofl0r that didn't change anything:
```strict_chain
proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000
[ProxyList]
socks4 127.0.0.1 8000
```

**Comment by anonu1** [comment]
Thank you, so a `wget` works, but it seems like git and docker do not; maybe I misunderstood what I can use this for. I was hoping to be able to route all traffic through socks5. I now see in the first few lines of the README that I was mistaken

**Comment by rofl0r** [comment]
git should work (at least it does here) unless your openssh binaries are static linked. programs written in go (such as docker) use static linking, so it's not possible to hook them.

**Comment by anonu1** [comment]
`git` does indeed work. Thankfully `docker` and `helm` support an optional socks5 proxy argument.
