### ISSUE TITLE
Some applications only work inside a debugger (gdb)

### ISSUE THREAD

**Issue by jsrobson10** [rofl0r/proxychains-ng#297]
When I try to open an app like discord or minecraft, it fails to open, but when I open it using `gdb` it works.

This works:
```
gdb proxychains4 --args /opt/minecraft-launcher
```

This hangs:
```
proxychains4 /opt/minecraft-launcher
```

**Comment by rofl0r** [comment]
why did you close this ? has the issue been resolved ?
