### ISSUE TITLE
Use proxychains only for certain networks

### ISSUE THREAD

**Issue by ivanilvescmp** [rofl0r/proxychains-ng#298]
Hello,

I would like to know is there any configuration file directive that would allow proxy tunneling for certain destinations only?

It's `localnet` vice versa - I want to specify only list of special networks I want to use with proxychains and not use proxies by default. 😄 

Is that somehow possible?

Thank U!

**Comment by rofl0r** [comment]
not directly, but U can use tinyproxy's upstream directive to select different upstream proxies per directive (those could, in turn, point to a proxychained microsocks server, in case you need several hops), which you then set as your system proxy, or with proxychains. funnily enough, this was asked a week ago in #296

**Comment by ivanilvescmp** [comment]
OK! Will try. 

Thank you!
