### ISSUE TITLE
Doesn't work with any Java programs

### ISSUE THREAD

**Issue by kb-1000** [rofl0r/proxychains-ng#299]
I tried this on a _lot_ of java programs, not a single one seems to have ever used it. I have Fedora 30 and tried it with Java 8. Maybe Java unloads the .so or something?

**Comment by rofl0r** [comment]
it probably either uses static linked libc, or no libc at all. but that's all in the README.

**Comment by kb-1000** [comment]
I'm pretty sure that this isn't the case. I can't verify this just now, though.
