### ISSUE TITLE
Socket error or timeoute! 127.0.0.1

### ISSUE THREAD

**Issue by flexxit** [rofl0r/proxychains-ng#30]
Hello.
I want try to connect to tor with vip72 client (socks5). This two application use this same ip 127.0.0.1, tor use port 9050, and vip72client 9951 for socks5 or 9953 for http proxy.
I have this error when i want to connect:
 Strict chain ... 127.0.0.1:9050 ... 127.0.0.1:9953 <--socket error or timeout!

I have add loopback adress in proxychains.conf:
# ' localnet 127.0.0.0/255.0.0.0

localnet 127.0.0.0/255.0.0.0

remote_dns_subnet 224

**Comment by nileshanand2** [comment]
please help | socket error or timeout!

my config files 
[ProxyList]
# add proxy here ...
# meanwile
# defaults set to "tor"
#socks4 	127.0.0.1 9050
socks5	101.200.168.93	1080
socks5	182.18.57.5	1080
