### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by idabwifbawf** [rofl0r/proxychains-ng#300]
$ ./configure --prefix=/usr --sysconfdir=/etc

checking whether we have GNU-style getservbyname_r() ... no
checking whether we have pipe2() and O_CLOEXEC ... no
checking whether $CC defines __APPLE__ ... no
checking whether $CC defines __FreeBSD__ ... no
checking whether $CC defines __OpenBSD__ ... no
checking whether $CC defines __sun ... no
checking whether we can use -Wl,--no-as-needed ... no
checking what's the option to use in linker to set library name ... 
cannot find an option to set library name

What should I do? I have installed gcc on my system. Any other dependencies I need?

**Comment by rofl0r** [comment]
you need "build-essential" (eventually build-essentials) package. it contains gcc, binutils, libc headers
