### ISSUE TITLE
git clone with proxychains failed on linux

### ISSUE THREAD

**Issue by mightbxg** [rofl0r/proxychains-ng#304]
Because of the GFW, cloning repositories from github is very slow for me. So I tried boosting the speed of cloning with proxychains and it used to work quite well.
However, an error occurs when I clone with proxychains in recent months:
```
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] Strict chain  ...  127.0.0.1:1080  ...  github.com:443  ...  OK
[proxychains] DLL init: proxychains-ng 4.14
remote: Enumerating objects: 72, done.
remote: Counting objects: 100% (72/72), done.
remote: Compressing objects: 100% (63/63), done.
[proxychains] DLL init: proxychains-ng 4.14
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: unpack-objects failed
```
I searched about the error on the Internet and all answers suggest configing git with larger `http.postBuffer` or just cloning with `--depth 1`, but these don't work for me (while indeed some small repositories can be cloned without this problem).
So I doubt the problem may have something to do with proxychains.

This problem happens on my linux OS (both Ubuntu16.04 and Manjaro), but does't on my Windows OS (WSL - Ubuntu16.04).

Any help or suggestion is appreciated.

**Comment by rofl0r** [comment]
in case wifi is involved, changing mtu might help.
try downloading big files from github (e.g. releases of palemoon or something comparable) with curl with and without proxychains. is the WSL curl version different ?
if you have ssh access to the proxy you might also run tcpdump and look at the packet capture to see which end of the connection causes the interruption.

**Comment by mightbxg** [comment]
1. Wire cable is used, not wifi.
2. The curl on Ubuntu and WSL have the same version: curl 7.47.0 (x86_64-pc-linux-gnu).
3. I tried downloading with curl:
```
proxychains curl -LO https://github.com/PointCloudLibrary/pcl/releases/download/pcl-1.9.1/PCL-1.9.1-AllInOne-msvc2017-win32.exe
```
It works fine on WSL, but problem occurs on Ubuntu:
```
  0  437M    0  493k    0     0   103k      0  1:12:20  0:00:04  1:12:16  207k
curl: (56) GnuTLS recv error (-9): A TLS packet with unexpected length was received.
```
Also, doing curl directly on Ubuntu have no problem (just very slow).

Unfortunately, I have no ssh access to the proxy and know little about tcpdump. Maybe curl with "--verbose" can provide some useful information?

**Comment by rofl0r** [comment]
> curl: (56) GnuTLS recv error (-9): A TLS packet with unexpected length was received.

maybe an issue with gnutls version. or the socks server software does something unexpected/buggy under certain conditions. it would be interesting to see a pcap (made with wireshark / tcpdump) when this happens. since it would probably contain sensitive information, i'd suggest you come to the IRC channel mentioned in README after you produced it.

**Comment by mightbxg** [comment]
I have produced the pcap file and visited the IRC channel, but I don't know how to transfer it to you securely.

**Comment by mightbxg** [comment]
Sorry I didn't check the post last night. Maybe we can communicate with email? My address is mightbxg@hotmail.com.
Thanks for your time.

**Comment by rofl0r** [comment]
> Maybe we can communicate with email

nope, only IRC.

**Comment by mightbxg** [comment]
ok, I'm online this time.

**Comment by mightbxg** [comment]
I find that the encryption method of proxy (ShadowSocks) may be the cause of this problem.

If encryption method "aes-256-cfb" is used, all works fine. But if changed to "aes-256-gcm", problem occurs. Tested with curl.
BTW, wget with proxychains can work on both encryption methods. This may be a bug of curl, which explains why git clone fails.
