### ISSUE TITLE
Proxychains waits for client input before returning server data

### ISSUE THREAD

**Issue by DrDisrespect2** [rofl0r/proxychains-ng#309]
the original proxychains has this problem too.
use telnet to connect to NNTP.
server is expected to return server's hello message upon client connect.
that doesn't happen with proxychains.
you have to send at least one line of data to the server.
why this is a problem? because lynx and other nntp clients hang waiting for server helo.

**Comment by rofl0r** [comment]
please provide some addresses so i can take a look.

**Comment by DrDisrespect2** [comment]
nntp.aioe.org:119

eg I enter "help" after significant delay(after server timeouts client connection):

Connected to nntp.aioe.org.
Escape character is '^]'.
help
200 nntp.aioe.org InterNetNews NNRP server INN 2.5.4 ready (posting ok)
Connection closed by foreign host.

**Comment by rofl0r** [comment]
i just tested on both ubuntu and sabotage hosts (with socks5 and http proxies), works for me (lynx, netcat, etc) with latest git.

**Comment by DrDisrespect2** [comment]
is this smth about proxy configuration then? because I have seen only one proxy which forwards NNTP helo.
I grabbed first random HTTPS proxy and tried connecting to nntp.aioe.org and it doesn't do anything until I send some line to server. Even when TOR proxy is removed.

**Comment by rofl0r** [comment]
> is this smth about proxy configuration then?

it works with proxies hat i set up and contol (e.g. microsocks / tinyproxy). so it's just a problem of the the random proxy you use.

> I grabbed first random HTTPS proxy

https proxy is not supported. that is probably why it didn't work. in future, please try with more than one proxy before opening issues here.
