### ISSUE TITLE
gnutls_handshake() failed: The TLS connection was non-properly terminated

### ISSUE THREAD

**Issue by goldcome** [rofl0r/proxychains-ng#312]
`proxychains4 git clone https://github.com/MattesGroeger/vim-bookmarks.git`

result is 
```
fatal: unable to access 'https://github.com/MattesGroeger/vim-bookmarks.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
```

but when i use proxychains , and it is work. only proxychains4 not work.

**Comment by rofl0r** [comment]
paste full output (especially version number string of proxychains-ng)

**Comment by goldcome** [comment]
```
ubuntu18.04
git version 2.24.0

proxychains4 git clone https://github.com/MattesGroeger/vim-bookmarks.git
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/local/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.12
正克隆到 'vim-bookmarks'...
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] Strict chain  ...  116.8.34.159:8261  ...  116.8.34.159:8261  ...  OK
fatal: unable to access 'https://github.com/MattesGroeger/vim-bookmarks.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
```

**Comment by goldcome** [comment]
```
proxychains git clone https://github.com/MattesGroeger/vim-bookmarks.git
+ proxychains git clone https://github.com/MattesGroeger/vim-bookmarks.git
ProxyChains-3.1 (http://proxychains.sf.net)
正克隆到 'vim-bookmarks'...
|S-chain|-<>-116.8.34.159:8261-<><>-116.8.34.159:8261-<><>-OK
|DNS-request| github.com
|S-chain|-<>-116.8.34.159:8261-<><>-4.2.2.2:53-<><>-OK
|DNS-response| github.com is 140.82.118.3
|S-chain|-<>-116.8.34.159:8261-<><>-116.8.34.159:8261-<><>-OK
remote: Enumerating objects: 829, done.
remote: Total 829 (delta 0), reused 0 (delta 0), pack-reused 829
接收对象中: 100% (829/829), 1.32 MiB | 63.00 KiB/s, 完成.
处理 delta 中: 100% (392/392), 完成.
```

proxychains work.

**Comment by rofl0r** [comment]
> [proxychains] DLL init: proxychains-ng 4.12

this is a pretty old version. maybe you should update.

**Comment by goldcome** [comment]
I've tried v4.12 to v4.14，and master branch，all not working

```
proxychains4 git clone https://github.com/MattesGroeger/vim-bookmarks.git
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.14-git-8-gb8fa2a7
正克隆到 'vim-bookmarks'...
[proxychains] DLL init: proxychains-ng 4.14-git-8-gb8fa2a7
[proxychains] Strict chain  ...  116.8.34.159:8261  ...  116.8.34.159:8261  ...  OK
fatal: unable to access 'https://github.com/MattesGroeger/vim-bookmarks.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
```

**Comment by rofl0r** [comment]
it would be interesting to figure out what happens there with gnutls... but i guess for now you can get it to work if you turn off proxy_dns setting in config.

**Comment by goldcome** [comment]
thank you，it works when turn off proxy dns

**Comment by rofl0r** [comment]
@imxys 
in proxychains.conf, put a `#` sign in front of `proxy_dns`.
if you use latest master you could also try instead `proxy_dns_old` which could fix the issue

**Comment by linguawork** [comment]
> @imxys
> in proxychains.conf, put a `#` sign in front of `proxy_dns`.
> if you use latest master you could also try instead `proxy_dns_old` which could fix the issue

I have got the same issue, I can not push a file to my git, it gives me the message: gnutls_handshake() failed: The TLS connection was non-properly terminated., 
Can you, please, be more specific on how to turn off proxy dns(where to go and what commands to enter)? Can I turn off proxy dns somewhere else except bash command line? I am new to git, I am still researching it. 
Thank you

**Comment by rofl0r** [comment]
> I am new to git, I am still researching it.

but you know how to use a text editor hopefully? then open the tinyproxy.conf file that is used (often /etc/tinyproxy.conf, but you see which exact one by the proxychains debug output) look for the line containing proxy_dns and make it a comment by putting a `#` sign in front of it, then save. you might need root powers to do so, in which case usage of `sudo` or `su` would be appropriate.
