### ISSUE TITLE
git-lfs is not proxied

### ISSUE THREAD

**Issue by xuefer** [rofl0r/proxychains-ng#315]
net-misc/proxychains-4.14

proxychains -q git lfs fetch
lsof -np `pidof git-lfs` shows  ip of gitlab.opengapps.org instead of my proxy server ip

**Comment by rofl0r** [comment]
which language is git-lfs written in? is it statically linked ?

**Comment by xuefer** [comment]
https://git-lfs.github.com/

dev-vcs/git-lfs-2.9.1

$ ldd /usr/bin/git-lfs
        linux-vdso.so.1 (0x00007ffff7fd2000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ffff7f8c000)
        libc.so.6 => /lib64/libc.so.6 (0x00007ffff7db7000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ffff7fd3000)

it's written in go, which mean it's static-linked. too bad

**Comment by rofl0r** [comment]
> it's written in go, which mean it's static-linked. too bad

yes. a bad idea generally to use google's proprietary language, but even more so when the project doing it targets a project written in C.
