### ISSUE TITLE
annoying rolling infinite output...

### ISSUE THREAD

**Issue by adaaaaaa** [rofl0r/proxychains-ng#318]
after command:
proxychains make -j1 V=s
the terminal display infinite thing like this...
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
...
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
...

how to hide or stop these infinite output???

**Comment by rofl0r** [comment]
by killing the process which keeps spawning new processes in a loop.

hint: you shouldn't build proxychains-ng with `proxychains` command.
