### ISSUE TITLE
proxychains ssh issue: connection closed by remote host

### ISSUE THREAD

**Issue by YinianFan** [rofl0r/proxychains-ng#319]
When using proxychains to ssh my remote server, can't connect.

`$ proxychains4 ssh -p 22200 root@myserver`
`[proxychains] config file found: /etc/proxychains4.conf`
`[proxychains] preloading /usr/lib/x86_64-linux-gnu/libproxychains.so.4`
`[proxychains] DLL init: proxychains-ng 4.12`
`[proxychains] Strict chain  ...  127.0.0.1:7891  ...  45.32.137.160:22200  ...  OK`
`ssh_exchange_identification: Connection closed by remote host`

And I tried "sudo", doesn't work neither.

**Comment by rofl0r** [comment]
maybe the proxy's ip is blocked ? check your firewall

**Comment by YinianFan** [comment]
You are so good, mate. 
My remote server's firewalld failed to start somehow. Restart firewalld, problem solved.
Thank you very much and wish you have a nice day!
