### ISSUE TITLE
ERROR:ld.so:object 'usr/lib/libproxychains4.so'from LD_PRELOAD cannot be preloaded.

### ISSUE THREAD

**Issue by StevenJokes** [rofl0r/proxychains-ng#321]
sudo proxychains -q /bin/zsh

Then I uninstalled it ,because I can't use yay in archlinux.

ERROR:ld.so:object 'usr/lib/libproxychains4.so'from LD_PRELOAD cannot
be preloaded.

How can I solve it without reinstalling proxychains-ng?

**Comment by StevenJokes** [comment]
$ unset LD_PRELOAD
I have try it.
Will it influence other softwares?

**Comment by rofl0r** [comment]
just close your zsh instance and everything will be OK.
