### ISSUE TITLE
when make && make install, there is wrong

### ISSUE THREAD

**Issue by freemagicfan** [rofl0r/proxychains-ng#322]
emex@UAV:~/proxychains-ng$ make && make install
make: Nothing to be done for 'all'.
./tools/install.sh -D -m 644 libproxychains4.so /usr/local/lib/libproxychains4.so
./tools/install.sh: 53: ./tools/install.sh: cannot create /usr/local/lib/libproxychains4.so.tmp.9404: Permission denied
Makefile:61: recipe for target '/usr/local/lib/libproxychains4.so' failed
make: *** [/usr/local/lib/libproxychains4.so] Error 2

**Comment by rofl0r** [comment]
use sudo or su to switch to root
