### ISSUE TITLE
 proxychains-ng doesn't work with ssh 

### ISSUE THREAD

**Issue by zyfneverforget** [rofl0r/proxychains-ng#324]
Hello: 
my system is  mac os 10.15 and turn off the SIP
my logs:
 proxychains4 ssh git@github.com
[proxychains] config file found: /usr/local/etc/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.14/lib/libproxychains4.dylib
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] Strict chain  ...  127.0.0.1:1080  ...  github.com:22  ...  OK
ssh_exchange_identification: Connection closed by remote host

ssh git@github.com
PTY allocation request failed on channel 0
Hi zyf! You've successfully authenticated, but GitHub does not provide shell access.
Connection to github.com closed.

and when I git clont git@github.com:zxxxxxxt/xxxx.git some problem.

how can I fix this problem ? thanks a lot!

**Comment by rofl0r** [comment]
you cannot ssh to github directly, you need to use the git interface
