### ISSUE TITLE
use xdg dir for config

### ISSUE THREAD

**Issue by soredake** [rofl0r/proxychains-ng#325]
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
`$XDG_CONFIG_HOME/proxychains/proxychains.conf`

**Comment by rofl0r** [comment]
is proxychains-ng a desktop app ?

**Comment by soredake** [comment]
Not only desktop apps use this specification.

**Comment by barsnick** [comment]
> Not only desktop apps use this specification.

Indeed, at least common distributions have managed to move many programs from their own home-dot files and directories to ```$XDG_CONFIG_HOME``` / ```~/config```. On Fedora, I have _many_ more programs using ```~/config``` than my home dir.

@soredake's suggestion was the first thing that came to my mind when configuring proxychains-ng for the first time.

I modified it like this:
```
--- proxychains-ng-4.14/src/common.c    2019-03-17 00:04:36.000000000 +0100
+++ proxychains-ng-4.14-xdg/src/common.c        2020-06-14 01:34:33.159708617 +0200
@@ -79,6 +79,20 @@
        if(check_path(path))
                goto have;
 
+       // priority 3b; $XDG_CONFIG_HOME/proxychains/proxychains.conf
+       path = getenv("XDG_CONFIG_HOME");
+       snprintf(pbuf, bufsize, "%s/proxychains/%s", path, PROXYCHAINS_CONF_FILE);
+       path = pbuf;
+       if(check_path(path))
+               goto have;
+
+       // priority 3b; $HOME/.config/proxychains/proxychains.conf
+       path = getenv("HOME");
+       snprintf(pbuf, bufsize, "%s/.config/proxychains/%s", path, PROXYCHAINS_CONF_FILE);
+       path = pbuf;
+       if(check_path(path))
+               goto have;
+
        // priority 4: $SYSCONFDIR/proxychains.conf
        path = SYSCONFDIR "/" PROXYCHAINS_CONF_FILE;
        if(check_path(path))
```
"Works for me."(TM)

(Motivation for two additional paths: ["If ```$XDG_CONFIG_HOME`` is either not set or empty, a default equal to ```$HOME/.config``` should be used."](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html))

Yes, it's dirty, due to undefined behavior of (sn)printf()ing a potential NULL value - I need to fix that. But same with the original code, in case $HOME happens not to be defined.

(That said, proxychains-ng is an essential and valuable program, regardless of minor suggestions like this! Thanks!)

**Comment by soredake** [comment]
@rofl0r if you against this please close this issue.
