### ISSUE TITLE
HTTPS proxy support

### ISSUE THREAD

**Issue by Daniel15** [rofl0r/proxychains-ng#337]
Hi! Is it possible to support HTTPS proxies in addition to HTTP? Right now it just seems to say "<--socket error or timeout!" if I try to use a HTTP proxy running on port 443.

**Comment by Daniel15** [comment]
Duplicate of #186

Not currently possible, but I got it working using `socat` to create a tunnel:
```
socat TCP-LISTEN:24351,bind=127.0.0.1,fork,reuseaddr OPENSSL:proxy.example.com:443
```

Then in the proxychains config:
```
http 127.0.0.1 24351
```

**Comment by ddor254** [comment]
@Daniel15  how do you pass username and password for the proxy server?

**Comment by Daniel15** [comment]
@ddor254  You just need to include them in that line in the proxychains config, for example:
```
http 127.0.0.1 24351 username password
```

**Comment by ddor254** [comment]
alright, thanks @Daniel15
