### ISSUE TITLE
MAKE fails with: src/main.c:120:19: error: use of undeclared identifier 'dli'

### ISSUE THREAD

**Issue by anoduck** [rofl0r/proxychains-ng#338]
Upon compilation running `gmake` with clang providing compiler received the following errors:

```bash
src/main.c:119:2: error: use of undeclared identifier 'Dl_info'
        Dl_info dli;
        ^
src/main.c:120:2: warning: implicit declaration of function 'dladdr' is invalid in C99 [-Wimplicit-function-declaration]
        dladdr(own_dir, &dli);
        ^
src/main.c:120:19: error: use of undeclared identifier 'dli'
        dladdr(own_dir, &dli);
                         ^
src/main.c:121:14: error: use of undeclared identifier 'dli'
        set_own_dir(dli.dli_fname);
                    ^
```

Then upon compiling with gcc providing compiler received the following errors:

```bash
src/main.c: In function 'main':
src/main.c:119: error: 'Dl_info' undeclared (first use in this function)
src/main.c:119: error: (Each undeclared identifier is reported only once
src/main.c:119: error: for each function it appears in.)
src/main.c:119: error: expected ';' before 'dli'
src/main.c:120: warning: implicit declaration of function 'dladdr'
src/main.c:120: error: 'dli' undeclared (first use in this function)
gmake: *** [Makefile:82: src/main.o] Error 1
```

Appears source code relies on compiler that is too new for OpenBSD and is not compatible.

**Comment by rofl0r** [comment]
can you pastebin the contents of openbsd's dlfcn.h ?

**Comment by anoduck** [comment]
Sure thing!  
For reference, dlfcn.h is located in `/usr/include`.  
Link to pastebin: [https://pastebin.com/SX8j1fgA](https://pastebin.com/SX8j1fgA)

**Comment by rofl0r** [comment]
you see, the stuff we need is available under `#if __BSD_VISIBLE`.
we got to find the right feature test macros in sys/cdefs.h or sys/features.h to make it visible. something like `_BSD_SOURCE` or `_XOPEN_SOURCE=xxx`. can you figure out which macro enables it ?

**Comment by danger89** [comment]
I have the same problem with anther project. I does not build under MacOS:

```
error: use of undeclared identifier 'Dl_info'
error: implicit declaration of function 'dladdr' is invalid in C99
```

Did you found any solution?

**Comment by rofl0r** [comment]
in main.c, we have:

```c
#define _DEFAULT_SOURCE
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <sys/types.h>
#include <sys/wait.h>

#ifdef IS_MAC
#define _DARWIN_C_SOURCE
#endif
#include <dlfcn.h>
```
so i think `#define _DARWIN_C_SOURCE` before including dlfcn.h should fix it.

**Comment by anoduck** [comment]
Agreed, time to close.
