### ISSUE TITLE
Using domain socket instead of IP PORT as proxy

### ISSUE THREAD

**Issue by amosbird** [rofl0r/proxychains-ng#341]
Hello. I'm using ssh -R to forward a local running socks proxy to remote. However using tcp port might lead to port conflicts. I wonder if proxychains-ng could support domain socket so that it can build a better workflow.

**Comment by rofl0r** [comment]
> However using tcp port might lead to port conflicts.

i don't think so. linux is pretty smart about assigning non-conflicting ports for outgoing connections, and it usually uses high port numbers > 20000.

> I wonder if proxychains-ng could support domain socket so that it can build a better workflow.

i didn't deeply research domain sockets but this has never before been requested in the past so i think  it wouldn't be really useful.
