### ISSUE TITLE
Documentation Request: proxychains.conf examples

### ISSUE THREAD

**Issue by greycubesgav** [rofl0r/proxychains-ng#344]
Hi;
I've been trying out proxychains-ng but can't seem to find any documentation on the structure and commands to be set in the proxychains.conf file.
I've found some examples in various issue tickets but nothing that explains what is what.
Am I missing something?
Thanks

**Comment by rofl0r** [comment]
>  Am I missing something?

yes, you're missing https://github.com/rofl0r/proxychains-ng/blob/master/src/proxychains.conf which is full of comments and examples explaining what the options do.
