### ISSUE TITLE
Is it possible to configure different proxies for different servers?

### ISSUE THREAD

**Issue by dclong** [rofl0r/proxychains-ng#345]
For example, if I have a server S1 which must be visited through proxy P1 and a server S2 which must be visited through proxy P2. Is it possible to configure proxychains so that it works for both S1 and S2?

**Comment by rofl0r** [comment]
not directly, but tinyproxy can be configured to use different upstream proxies for different destinations, so you can run tinyproxy on localhost and put its address into your proxychains config.

**Comment by dclong** [comment]
Thank you, @rofl0r !
