### ISSUE TITLE
localnet feature not working as expected with Genymotion android emulator

### ISSUE THREAD

**Issue by shllwrld** [rofl0r/proxychains-ng#347]
I'm trying to start Genymotion Android Emulator via proxychains on Ubuntu Linux 18.04. 

Some explanations: Genymotion is based on VirtualBox, so it uses vboxnet interface, which in my case called vboxnet0 (ip 192.168.56.1), Genymotion starts virtual device and takes ip address in 192.168.56.1/24 range (192.168.56.101 in my case) and bind port 25000 (possibly) to interact with it. Without proxychains it's working well.

My proxychains.conf

> strict_chain
> proxy_dns
> remote_dns_subnet
> tcp_read_time_out 15000
> tcp_connect_time_out 8000
> localnet 192.168.0.0/255.255.0.0
> socks4 	127.0.0.1 9050

If i start it, i get black screen in emulator and loop in console:

> ./proxychains4 -f /etc/proxychains4.conf /opt/genymobile/genymotion/player -n test -s
> [proxychains] config file found: /etc/proxychains4.conf
> [proxychains] preloading ./libproxychains4.so
> [proxychains] DLL init: proxychains-ng 4.14-git-25-g486f820
> [proxychains] Strict chain  ...  127.0.0.1:9050  ...  cloud.genymotion.com:443 [proxychains] Strict chain  ...  127.0.0.1:9050  ...  192.168.56.101:25000 <--denied
> [proxychains] Strict chain  ...  127.0.0.1:9050  ...  192.168.56.101:25000 <--denied
> [proxychains] Strict chain  ...  127.0.0.1:9050  ...  192.168.56.101:25000 <--denied
>  ...  OK
> [proxychains] Strict chain  ...  127.0.0.1:9050  ...  192.168.56.101:25000 <--denied
> [proxychains] Strict chain  ...  127.0.0.1:9050  ...  192.168.56.101:25000 <--denied
> [proxychains] Strict chain  ...  127.0.0.1:9050  ...  192.168.56.101:25000 <--denied
> [proxychains] Strict chain  ...  127.0.0.1:9050  ...  192.168.56.101:25000 <--denied
> [proxychains] Strict chain  ...  127.0.0.1:9050  ...  192.168.56.101:25000 <--denied
> [proxychains] Strict chain  ...  127.0.0.1:9050  ...  192.168.56.101:25000 <--denied
> [proxychains] Strict chain  ...  127.0.0.1:9050  ...  192.168.56.101:25000 <--denied
> [proxychains] Strict chain  ...  127.0.0.1:9050  ...  192.168.56.101:25000 <--denied
> [proxychains] Strict chain  ...  127.0.0.1:9050  ...  192.168.56.101:25000 <--denied

As you can see, it's trying to connect 192.168.56.101:25000 via proxy inspite of localnet param in config file.

I started nmap via proxychains to demonstrate - port really open and proxychains localnet feature working well in nmap:

> ./proxychains4 -f /etc/proxychains4.conf nmap 192.168.56.101 -p25000,25001
> [proxychains] config file found: /etc/proxychains4.conf
> [proxychains] preloading ./libproxychains4.so
> [proxychains] DLL init: proxychains-ng 4.14-git-25-g486f820
> 
> Starting Nmap 7.60 ( https://nmap.org ) at 2020-10-26 12:02 +08
> Nmap scan report for 192.168.56.101
> Host is up (0.00036s latency).
> 
> PORT      STATE  SERVICE
> 25000/tcp open   icl-twobase1
> 25001/tcp closed icl-twobase2
> 
> Nmap done: 1 IP address (1 host up) scanned in 0.50 seconds

I know it is very simple research and full mechanism of emulator work is unknown, but 
> [proxychains] Strict chain  ...  127.0.0.1:9050  ...  192.168.56.101:25000 <--denied

seems like proxychains bug?

...or maybe my misunderstandig

**Comment by rofl0r** [comment]
it works here.

```
remote_dns_subnet
```
this option requires a parameter, maybe it causes the issue ?

**Comment by rofl0r** [comment]
oh, it also seems you're missing the `[ProxyList]` block in your config

**Comment by shllwrld** [comment]
Sorry, there was some mistakes in first post, full config here, same issue

```
# proxychains.conf  VER 4.x
#
#        HTTP, SOCKS4a, SOCKS5 tunneling proxifier with DNS.


# The option below identifies how the ProxyList is treated.
# only one option should be uncommented at time,
# otherwise the last appearing option will be accepted
#
# dynamic_chain
#
# Dynamic - Each connection will be done via chained proxies
# all proxies chained in the order as they appear in the list
# at least one proxy must be online to play in chain
# (dead proxies are skipped)
# otherwise EINTR is returned to the app
#
strict_chain
#
# Strict - Each connection will be done via chained proxies
# all proxies chained in the order as they appear in the list
# all proxies must be online to play in chain
# otherwise EINTR is returned to the app
#
#round_robin_chain
#
# Round Robin - Each connection will be done via chained proxies
# of chain_len length
# all proxies chained in the order as they appear in the list
# at least one proxy must be online to play in chain
# (dead proxies are skipped).
# the start of the current proxy chain is the proxy after the last
# proxy in the previously invoked proxy chain.
# if the end of the proxy chain is reached while looking for proxies
# start at the beginning again.
# otherwise EINTR is returned to the app
# These semantics are not guaranteed in a multithreaded environment.
#
#random_chain
#
# Random - Each connection will be done via random proxy
# (or proxy chain, see  chain_len) from the list.
# this option is good to test your IDS :)

# Make sense only if random_chain or round_robin_chain
#chain_len = 2

# Quiet mode (no output from library)
#quiet_mode

# Proxy DNS requests - no leak for DNS data
proxy_dns 

# set the class A subnet number to use for the internal remote DNS mapping
# we use the reserved 224.x.x.x range by default,
# if the proxified app does a DNS request, we will return an IP from that range.
# on further accesses to this ip we will send the saved DNS name to the proxy.
# in case some control-freak app checks the returned ip, and denies to 
# connect, you can use another subnet, e.g. 10.x.x.x or 127.x.x.x.
# of course you should make sure that the proxified app does not need
# *real* access to this subnet. 
# i.e. dont use the same subnet then in the localnet section
#remote_dns_subnet 127 
#remote_dns_subnet 10
remote_dns_subnet 224

# Some timeouts in milliseconds
tcp_read_time_out 15000
tcp_connect_time_out 8000

### Examples for localnet exclusion
## localnet ranges will *not* use a proxy to connect.
## Exclude connections to 192.168.1.0/24 with port 80
# localnet 192.168.1.0:80/255.255.255.0

## Exclude connections to 192.168.100.0/24
# localnet 192.168.100.0/255.255.0.0

## Exclude connections to ANYwhere with port 80
# localnet 0.0.0.0:80/0.0.0.0

## RFC5735 Loopback address range
## if you enable this, you have to make sure remote_dns_subnet is not 127
## you'll need to enable it if you want to use an application that 
## connects to localhost.
#localnet 127.0.0.0/255.0.0.0

## RFC1918 Private Address Ranges
#localnet 10.0.0.0/255.0.0.0
#localnet 172.16.0.0/255.240.0.0
localnet 192.168.0.0/255.255.0.0

# ProxyList format
#       type  ip  port [user pass]
#       (values separated by 'tab' or 'blank')
#
#       only numeric ipv4 addresses are valid
#
#
#        Examples:
#
#            	socks5	192.168.67.78	1080	lamer	secret
#		http	192.168.89.3	8080	justu	hidden
#	 	socks4	192.168.1.49	1080
#	        http	192.168.39.93	8080	
#		
#
#       proxy types: http, socks4, socks5
#        ( auth types supported: "basic"-http  "user/pass"-socks )
#
[ProxyList]
# add proxy here ...
# meanwile
# defaults set to "tor"
socks4 	127.0.0.1 9050

```

**Comment by rofl0r** [comment]
as i said, it works here. what's the OS you running there ? with version number pls.

also try `proxychains4 -f /etc/proxychains4.conf curl https://192.168.56.101:25000`
whether or not something listens on that IP/port is irrelevant, if proxychains does the right thing you shouldnt get any `[proxychains] Strict chain ... ` output.

oh, and make sure you actually point to the right config file. /etc/proxychains4.conf vs /etc/proxychains.conf

**Comment by shllwrld** [comment]
Okay, once again step by step

```
linux@linux:~$ cd proxychains-ng/
linux@linux:~/proxychains-ng$ uname -a
Linux linux 4.15.0-122-generic #124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
linux@linux:~/proxychains-ng$ cat /etc/proxychains4.conf 
# proxychains.conf  VER 4.x
#
#        HTTP, SOCKS4a, SOCKS5 tunneling proxifier with DNS.


# The option below identifies how the ProxyList is treated.
# only one option should be uncommented at time,
# otherwise the last appearing option will be accepted
#
# dynamic_chain
#
# Dynamic - Each connection will be done via chained proxies
# all proxies chained in the order as they appear in the list
# at least one proxy must be online to play in chain
# (dead proxies are skipped)
# otherwise EINTR is returned to the app
#
strict_chain
#
# Strict - Each connection will be done via chained proxies
# all proxies chained in the order as they appear in the list
# all proxies must be online to play in chain
# otherwise EINTR is returned to the app
#
#round_robin_chain
#
# Round Robin - Each connection will be done via chained proxies
# of chain_len length
# all proxies chained in the order as they appear in the list
# at least one proxy must be online to play in chain
# (dead proxies are skipped).
# the start of the current proxy chain is the proxy after the last
# proxy in the previously invoked proxy chain.
# if the end of the proxy chain is reached while looking for proxies
# start at the beginning again.
# otherwise EINTR is returned to the app
# These semantics are not guaranteed in a multithreaded environment.
#
#random_chain
#
# Random - Each connection will be done via random proxy
# (or proxy chain, see  chain_len) from the list.
# this option is good to test your IDS :)

# Make sense only if random_chain or round_robin_chain
#chain_len = 2

# Quiet mode (no output from library)
#quiet_mode

# Proxy DNS requests - no leak for DNS data
proxy_dns 

# set the class A subnet number to use for the internal remote DNS mapping
# we use the reserved 224.x.x.x range by default,
# if the proxified app does a DNS request, we will return an IP from that range.
# on further accesses to this ip we will send the saved DNS name to the proxy.
# in case some control-freak app checks the returned ip, and denies to 
# connect, you can use another subnet, e.g. 10.x.x.x or 127.x.x.x.
# of course you should make sure that the proxified app does not need
# *real* access to this subnet. 
# i.e. dont use the same subnet then in the localnet section
#remote_dns_subnet 127 
#remote_dns_subnet 10
remote_dns_subnet 224

# Some timeouts in milliseconds
tcp_read_time_out 15000
tcp_connect_time_out 8000

### Examples for localnet exclusion
## localnet ranges will *not* use a proxy to connect.
## Exclude connections to 192.168.1.0/24 with port 80
# localnet 192.168.1.0:80/255.255.255.0

## Exclude connections to 192.168.100.0/24
# localnet 192.168.100.0/255.255.0.0

## Exclude connections to ANYwhere with port 80
# localnet 0.0.0.0:80/0.0.0.0

## RFC5735 Loopback address range
## if you enable this, you have to make sure remote_dns_subnet is not 127
## you'll need to enable it if you want to use an application that 
## connects to localhost.
#localnet 127.0.0.0/255.0.0.0

## RFC1918 Private Address Ranges
#localnet 10.0.0.0/255.0.0.0
#localnet 172.16.0.0/255.240.0.0
localnet 192.168.0.0/255.255.0.0

# ProxyList format
#       type  ip  port [user pass]
#       (values separated by 'tab' or 'blank')
#
#       only numeric ipv4 addresses are valid
#
#
#        Examples:
#
#            	socks5	192.168.67.78	1080	lamer	secret
#		http	192.168.89.3	8080	justu	hidden
#	 	socks4	192.168.1.49	1080
#	        http	192.168.39.93	8080	
#		
#
#       proxy types: http, socks4, socks5
#        ( auth types supported: "basic"-http  "user/pass"-socks )
#
[ProxyList]
# add proxy here ...
# meanwile
# defaults set to "tor"
socks4 	127.0.0.1 9050

linux@linux:~/proxychains-ng$ ./proxychains4 -f /etc/proxychains4.conf curl https://192.168.56.101:25000
[proxychains] config file found: /etc/proxychains4.conf
[proxychains] preloading ./libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.14-git-25-g486f820
curl: (7) Failed to connect to 192.168.56.101 port 25000: Connection timed out.
linux@linux:~/proxychains-ng$ ./proxychains4 -f /etc/proxychains4.conf /opt/genymobile/genymotion/player -n test -s
[proxychains] config file found: /etc/proxychains4.conf
[proxychains] preloading ./libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.14-git-25-g486f820
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  cloud.genymotion.com:443  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  192.168.56.101:25000 <--denied
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  192.168.56.101:25000 <--denied
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  192.168.56.101:25000 <--denied
^C

```

**Comment by rofl0r** [comment]
ok so proxychains does The Right Thing (TM) with curl, but not with genymotion. maybe it's actually looking up a hostname that translates to 192.168.56.101, maybe using /etc/hosts? an strace run could clarify that.

**Comment by rofl0r** [comment]
4.15.0-122-generic #124-Ubuntu - is that ubuntu 18.04 ?

**Comment by shllwrld** [comment]
4.15.0-122-generic #124-Ubuntu - is that ubuntu 18.04 ? - yes

**Comment by rofl0r** [comment]
ok could you run genymotion with strace -f pls and grep stderr for etc

**Comment by shllwrld** [comment]
so?
```
linux@linux:~/proxychains-ng$ strace -f /opt/genymobile/genymotion/player -n test -s 2>.output 
linux@linux:~/proxychains-ng$ cat .output | grep etc > .out
```

[out.txt](https://github.com/rofl0r/proxychains-ng/files/5442602/out.txt)

**Comment by rofl0r** [comment]
more or less, but we need a few lines of context around accessing the hosts/resolv.conf files to see what's actually being read. however if geny has a static VM config it could be sufficient to just look inside the file and check whether there's an entry for that ip

**Comment by shllwrld** [comment]
Ok. I understood - problem somewhere in hostname resolving. So, comment  #proxy_dns solves issue, VM running and no ```[proxychains] Strict chain ..``` output. I guess your localnet feature working well ^)

Sadly, but traffic from inside of VM going from my real ip. I think it's because geny uses host-only vbox interface and make geny + proxychains friends now looks not so easy.

**Comment by rofl0r** [comment]
> Ok. I understood - problem somewhere in hostname resolving. So, comment #proxy_dns solves issue

ok. is there actually an entry in /etc/hosts? i got to revise where the localnet check is applied so it works even after name resolving.

**Comment by shllwrld** [comment]
> > Ok. I understood - problem somewhere in hostname resolving. So, comment #proxy_dns solves issue
> 
> ok. is there actually an entry in /etc/hosts? i got to revise where the localnet check is applied so it works even after name resolving.

No. I quickly looked /etc/resolv.conf, /etc/hosts, geny log and *.vbox config file - no any valid entries. If you need some more research from me i can help

**Comment by rofl0r** [comment]
yes, that would be helpful. could you compile proxychains-ng in debug mode and paste the output when running it with proxy_dns on on geny?

```
make clean
CFLAGS=-DDEBUG ./configure
make
```

**Comment by shllwrld** [comment]
done

[debug.txt](https://github.com/rofl0r/proxychains-ng/files/5449743/debug.txt)

**Comment by rofl0r** [comment]
thanks, with the log i found the bug. could you please confirm whether your issue is fixed with git master? (with proxy_dns on)

**Comment by shllwrld** [comment]
yes, it's worked.

**Comment by rofl0r** [comment]
thanks. does that mean it even works with tor now? regarding your earlier comment

> Sadly, but traffic from inside of VM going from my real ip.

**Comment by shllwrld** [comment]
No. Network traffic generates inside VM OS and proxychains can not rule it. It was wrong way
