### ISSUE TITLE
Do not proxify requests to local network names when proxy_dns is enabled

### ISSUE THREAD

**Issue by galleyworm** [rofl0r/proxychains-ng#352]
Hello.

I deployed the service. The local network does not have direct access to the Internet. So the service works over proxychains. The critical point is that a service must interact with several other services on the same local network. The services can only be accessed by domain names. They cannot be accessed through a proxy server. The proxy server restricts access to the Internet by destination domain names.

- When I enable the proxy_dns option, all requests go to the proxy server. There is no connection to local services.
- When I disable the proxy_dns option, the service names are resolved locally and can be accessed. But in HTTP requests to outside hosts, names are also changed to IP addresses. The proxy server does not allow such requests (becouse it filter requests by names, not by IP addresses).

It is possible to set in config file a list of "local" names that must be resolved only by local network dns service (even if proxy_dns is enabled)?

Thank you.

**Comment by rofl0r** [comment]
> I deployed the service.

which service

> It is possible to set in config file a list of "local" names that must be resolved only by local network dns service (even if proxy_dns is enabled)?

via /etc/hosts

**Comment by galleyworm** [comment]
> which service
Just one proprietary python2 service.

> via /etc/hosts
Unfortunatily IP addresses may change. Names must be resolved by local network DNS server.

**Comment by rofl0r** [comment]
i guess the easiest hack to do this is to use proxy_dns_old and put the addresses into the proxyresolv script, use dig/drill for everything else.

**Comment by galleyworm** [comment]
With this approach, the CONNECT request will contain the IP address. Thus, the proxy will block the connection (access is allowed only for the list of domain names).

**Comment by liyinxin** [comment]
hello,i meet the same problem with you,can you tell me how to solve this problem?
i just uncomment the proxy_dns

**Comment by galleyworm** [comment]
Hi,
I solved this by using a dirty hack. I just cloned the git repo and hardcode my names in src/libproxychains.c:

```c
// This function detect names that need to be resolved by local DNS service
int is_local_host(const char *node) {
	const char *local_names[3];
	local_names[0] = "myservice";
	local_names[1] = "redis";
	local_names[2] = "postgresdb";

        int i;
        for(i = 0; i < 3; i++) {
                if (strcmp(node, local_names[i]) == 0) {
			PDEBUG("host %s is local\n", node);
			return 1; 
		}
        }
	PDEBUG("host %s is not local\n", node);
	return 0;
}

int getaddrinfo(const char *node, const char *service, const struct addrinfo *hints, struct addrinfo **res) {
	INIT();
	PDEBUG("getaddrinfo: %s %s\n", node ? node : "null", service ? service : "null");
	
	// Add new condition for detecting "local" names. 
	// In such cases we need to use true_getaddrinfo function
	if(proxychains_resolver != DNSLF_LIBC && (!node || is_local_host(node) == 0))
		return proxy_getaddrinfo(node, service, hints, res);
	else
		return true_getaddrinfo(node, service, hints, res);
}
```
Then i did build and install proxychains. After that i have enabled proxy_dns in configuration file. In my environment such method work fine.
