### ISSUE TITLE
Installation error on solus

### ISSUE THREAD

**Issue by TonyTomCat** [rofl0r/proxychains-ng#353]
```
tomy@solus ~/Downloads/proxychains-ng $ ./configure
checking whether we have GNU-style getservbyname_r() ... no
checking whether we have pipe2() and O_CLOEXEC ... no
checking whether we have SOCK_CLOEXEC ... no
checking whether $CC defines __APPLE__ ... no
checking whether $CC defines __FreeBSD__ ... no
checking whether $CC defines __OpenBSD__ ... no
checking whether $CC defines __sun ... no
checking whether $CC defines __HAIKU__ ... no
checking whether we can use -Wl,--no-as-needed ... no
checking what's the option to use in linker to set library name ... 
cannot find an option to set library name
```

Are there any other dependencies i need to install ??

**Comment by rofl0r** [comment]
> Are there any other dependencies i need to install ??

you need a C compiler and C library.

> cannot find an option to set library name

in case you already have the above, then you need to figure out how to set library name on solus. read the configure script, ask solus developers, and when you found out report it back so we can add support.

**Comment by TonyTomCat** [comment]
Its working now as I have reinstalled glibc ,gcc ,g++ ,make and git.
