### ISSUE TITLE
Not Work in BigSur

### ISSUE THREAD

**Issue by C4o** [rofl0r/proxychains-ng#355]
Seem not work in BigSur...

**Comment by rofl0r** [comment]
provide more details. i dont even know what big sur is.

**Comment by C4o** [comment]
so sorry...recently meet many bugs in bigsur..
BigSur is latest version of macos..

**Comment by C4o** [comment]
so sorry...recently meet many bugs in bigsur..
BigSur is latest version of macos..

**Comment by iamwwc** [comment]
@rofl0r  same problem, not working in latest mac os x os [big sur](https://www.apple.com/macos/big-sur/)

**Comment by rofl0r** [comment]
is that on intel or new M1 chip? ( #357 )

**Comment by iamwwc** [comment]
> is that on intel or new M1 chip? ( #357 )

intel chip :)
2019 macbook pro

**Comment by iamwwc** [comment]
@rofl0r it only hook first process. But when process forks new children processes, proxychains don't hook it

**Comment by rofl0r** [comment]
> @rofl0r it only hook first process.

ah, so essentially it works, i.e. you don't have any toolchain/binary format issues. that's already good to know. can you confirm a basic `proxychains4 curl ifconfig.me` does work ?

**Comment by iamwwc** [comment]
> > @rofl0r it only hook first process.
> 
> ah, so essentially it works, i.e. you don't have any toolchain/binary format issues. that's already good to know. can you confirm a basic `proxychains4 curl ifconfig.me` does work ?

It works, but nodemon(a nodejs program) doesn't😭

**Comment by rofl0r** [comment]
> It works, but nodemon(a nodejs program) doesn't

that seems to be an unrelated problem, it is long known that backgrounding tasks loose LD_PRELOAD'ed hooks (reason unknown so far).

**Comment by iamwwc** [comment]
> > It works, but nodemon(a nodejs program) doesn't
> 
> that seems to be an unrelated problem, it is long known that backgrounding tasks loose LD_PRELOAD'ed hooks (reason unknown so far).

But why there no problem in linux?

I found this, no sure whether is has helpness for you http://www.proxifier.com/new/mac.html

**Comment by rofl0r** [comment]
> But why there no problem in linux?

i've never seen this working in linux either.

> I found this, no sure whether is has helpness for you http://www.proxifier.com/new/mac.html

this is a closed-source product, so i can't actually see what changes they made - although they seem to use a different mac-specific technique to achieve the same outcome.

**Comment by iamwwc** [comment]
> > But why there no problem in linux?
> 
> i've never seen this working in linux either.
> 
> > I found this, no sure whether is has helpness for you http://www.proxifier.com/new/mac.html
> 
> this is a closed-source product, so i can't actually see what changes they made - although they seem to use a different mac-specific technique to achieve the same outcome.

sorry，I say proxychains works in linux, not proxychains-ng. That's my fault. proxychains and proxychains-ng is not same project

**Comment by rofl0r** [comment]
> I say proxychains works in linux

you're saying that proxychains 3.1 works even with backgrounded tasks ?

**Comment by iamwwc** [comment]
> > I say proxychains works in linux
> 
> you're saying that proxychains 3.1 works even with backgrounded tasks ?

I don‘t want to talk about proxychains on Linux too much. But proxychains-ng works on Mac OS X catalina except Mac OS X big sur. This issue is focusing proxychains-ng broken on big sur :)

**Comment by rofl0r** [comment]
> But proxychains-ng works on Mac OS X catalina except Mac OS X big sur.

didn't you say

> It works, but nodemon(a nodejs program) doesn't

if it really doesn't work at all, it would be interesting to test with proxychains-ng built on older OSX works on big sur, in which case it would hint at a toolchain issue.

**Comment by seajean** [comment]
I have the same problem,even `proxychains4 curl ifconfig.me` not work.

**Comment by rofl0r** [comment]
> I have the same problem,even proxychains4 curl ifconfig.me not work.

on x86_64 or M1 chip ?

**Comment by C4o** [comment]
I found why proxychains-ng not work..
I tested first with curl of MacOS but it actually cannot be hooked with SIP..It works when I hook processes that I installed..

**Comment by CaledoniaProject** [comment]
I won't work with MacOS platform binaries, you will need to install everything with homebrew

**Comment by Nadroid** [comment]
I have the same problem,even proxychains4 curl ifconfig.me not work.
