### ISSUE TITLE
Proxychains ignored config file after the config file been configurated

### ISSUE THREAD

**Issue by EVINK** [rofl0r/proxychains-ng#362]
Hi, my config file not working with proxychains, I`m pretty sure that the proxy prot and ip are correct (course my browser is using it now)

Version: 4.14
Platform: Darwin arm64 (M1 mac)

Console log:

```log
$ curl -L ip.tool.lu
IP: 113.57.174.178

$ proxychains4 curl -L ip.tool.lu
[proxychains] config file found: /opt/homebrew/etc/proxychains.conf
[proxychains] preloading /opt/homebrew/Cellar/proxychains-ng/4.14/lib/libproxychains4.dylib
IP: 113.57.174.178  # should be my proxy ip

```

in /opt/homebrew/etc/proxychains.conf:

```conf
[ProxyList]
socks5 127.0.0.1 1086
```

**Comment by rofl0r** [comment]
read the pinned issue about mac os troubles. you need to enable SIP **and** can only proxify apps that are not shipped in OS X system. so you need to use curl binary from e.g. homebrew.
