### ISSUE TITLE
Failed to CURL a https site over proxychain4

### ISSUE THREAD

**Issue by timxzz** [rofl0r/proxychains-ng#365]
Hello,

- OS: Ubuntu 16.04 LTS
- OpenSSL: 1.1.1g
- proxychain-ng version: 4.14

I was trying to curl the following site over proxy from China, 
```
proxychain4 curl 'https://api.binance.com/api/v3/exchangeInfo'
```
and it returned
```
curl: (51) SSL: certificate subject name (*.secure.facebook.com) does not match target host name 'api.binance.com'
```
where ` (*.secure.facebook.com) ` can sometimes be some other domains.

I am wondering if there is anything I can do to fix it? It seems to be problem relating to DNS?
(p.s. proxychain4 works fine so far for other tasks.)

Thanks a lot!

**Comment by rofl0r** [comment]
is that using some random free proxy ? looks like the proxy redirects you to a different target.

**Comment by timxzz** [comment]
Thanks for the quick reply! No, it's not random free proxy. It my own VPS. So the problem is within the proxy server?

**Comment by timxzz** [comment]
Also, if I use Chrome to open that link, it's accessible. And my Chrome is using proxy SwitchOmega to connect to my local SS client.

**Comment by rofl0r** [comment]
well, it's possible that the DNS requests are being tampered with. is api.binance.com something GFW would like to block ? the VPS is outside china ?

**Comment by timxzz** [comment]
It turns out to be the problem of DNS proxy, I manage to fix it using the method 3 in the config file. Thanks for the help!
