### ISSUE TITLE
proxychains

### ISSUE THREAD

**Issue by Csapii** [rofl0r/proxychains-ng#367]
(Sorry if i make any mistake in my english conversation)

Hi everyone !
i would try some new stuff, but sometimes i get back these from proxychains:
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/x86_64-linux-gnu/libproxychains.so.4
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14

...And then not happen anything :/
(ofc I have started "tor" service)
Sometimes it's workin' but sometimes not...

if i try with "curl", i get back these : 
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/x86_64-linux-gnu/libproxychains.so.4
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  127.0.0.1:9050 <--denied
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  whatismyipaddress.com:80  ...  OK

What should I do ?
Thank you in advance for all the help ! :)

My conf file: 
```
# proxychains.conf  VER 3.1
#
#        HTTP, SOCKS4, SOCKS5 tunneling proxifier with DNS.
#	

# The option below identifies how the ProxyList is treated.
# only one option should be uncommented at time,
# otherwise the last appearing option will be accept
dynamic_chain
#
# Dynamic - Each connection will be done via chained proxies
# all proxies chained in the order as they appear in the list
# at least one proxy must be online to play in chain
# (dead proxies are skipped)
# otherwise EINTR is returned to the app
#
#strict_chain
#
# Strict - Each connection will be done via chained proxies
# all proxies chained in the order as they appear in the list
# all proxies must be online to play in chain
# otherwise EINTR is returned to the app
#
#random_chain
#
# Random - Each connection will be done via random proxy
# (or proxy chain, see  chain_len) from the list.
# this option is good to test your IDS :)

# Make sense only if random_chain
#chain_len = 2

# Quiet mode (no output from library)
#quiet_mode

# Proxy DNS requests - no leak for DNS data
proxy_dns 

# Some timeouts in milliseconds
tcp_read_time_out 15000
tcp_connect_time_out 8000

# ProxyList format
#       type  host  port [user pass]
#       (values separated by 'tab' or 'blank')
#
#
#        Examples:
#
#            	socks5	192.168.67.78	1080	lamer	secret
#		http	192.168.89.3	8080	justu	hidden
#	 	socks4	192.168.1.49	1080
#	        http	192.168.39.93	8080	
#		
#
#       proxy types: http, socks4, socks5
#        ( auth types supported: "basic"-http  "user/pass"-socks )
#
[ProxyList]
# add proxy here ...
# meanwile
# defaults set to "tor"
# socks4 127.0.0.1 9050
socks4 127.0.0.1 9050
socks5 127.0.0.1 9050
```

**Comment by rofl0r** [comment]
> socks4 127.0.0.1 9050
> socks5 127.0.0.1 9050

that's wrong. you only need tor once, and the right setting for it is socks4.

**Comment by Csapii** [comment]
> > socks4 127.0.0.1 9050
> > socks5 127.0.0.1 9050
> 
> that's wrong. you only need tor once, and the right setting for it is socks4.

Now perfectly workin' !
That means it was my fault... hehe
Very thank your really fast reply for my issue ! <3
