### ISSUE TITLE
`Makefile` uses `USER_LDFLAGS` instead of LDFLAGS, which doesn't pass `LDFLAGS`

### ISSUE THREAD

**Issue by enedil** [rofl0r/proxychains-ng#368]
I'm not sure if it is intended or not, but I wanted to compile a version for 32 bits while on 64 bit Linux. I edited `config.mak`, to include `-m32` in `CFLAGS` and `LDFLAGS`, but it didn't build and I observed that the final link step uses `USER_LDFLAGS` instead of `LDFLAGS`. Is it intended? If not, then maybe the USER version should be removed alltogether?

**Comment by rofl0r** [comment]
the intended way to create config.mak is via configure.
`LDFLAGS="-Wl,-whatever" ./configure ....`
