### ISSUE TITLE
DLL init

### ISSUE THREAD

**Issue by Csapii** [rofl0r/proxychains-ng#369]
So few days ago I had same problem with proxychains-ng.
Some times workin' perfectly just once, but after if I would to use proxychains-ng just write these on terminal screen : 
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/local//lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.14-git-39-g918855d
[proxychains] DLL init: proxychains-ng 4.14-git-39-g918855d
[proxychains] DLL init: proxychains-ng 4.14-git-39-g918855d

My config file is perfectly configured, but I don't know why i get back these all time...
Someone can help me in this?

**Comment by rofl0r** [comment]
probably depends on the proxified app. which one is it ?

**Comment by Csapii** [comment]
I tried with Firefox :fox_face:

**Comment by rofl0r** [comment]
firefox has its own proxy configuration, you dont need to use proxychains for it.
if you want to do it anyway, make sure to use the proxychains4-daemon for dns resolution (description in src/proxychains.conf in this repo).
generally, the more complex a program, the harder it is to proxify correctly, and there's little software existing that's more complex than a modern webbrowser.

**Comment by Csapii** [comment]
hmm, I tried with Nmap..., but I think not workin' perfectly. I got the same issues, sometimes DDL inits, socket error or timeout, denied the request... It might be this the TOR fault?

**Comment by rofl0r** [comment]
well, just think about it. nmap is a portscanner. one uses it in order to find out which ports are open, so it will test connections to all ports in the specified range, and naturally some are closed and some open. when a port is closed, proxychains reports error.
also when in addition to that tor is in the mix, then that complicates things even more.

**Comment by Csapii** [comment]
sorry for I wasn't reply to you ! I had to make some research and learn in this theme and I could handle my problem perfectly, I haven't meet any error in your program, have a nice day ! :)
