### ISSUE TITLE
Failed to compile ripgrep with proxychains-ng

### ISSUE THREAD

**Issue by hongyi-zhao** [rofl0r/proxychains-ng#371]
On Ubuntu 20.04, I try to compile [ripgrep](https://github.com/BurntSushi/ripgrep#building) but failed. See following for more info:
```
$ proxychains4 -f /path/to/proxychains.conf  RUSTFLAGS="-C target-cpu=native" cargo build --release --features 'simd-accel' --features 'pcre2'
proxychains can't load process....: No such file or directory
```
Any hints for this problem?

Regards,
HY

**Comment by rofl0r** [comment]
RUSTFLAGS is not a command. put it in front of proxychains4.

**Comment by hongyi-zhao** [comment]
Thanks a lot, it does the trick.
