### ISSUE TITLE
There is no proxychains4-daemon for homebrew version of proxychains-ng.

### ISSUE THREAD

**Issue by hongyi-zhao** [rofl0r/proxychains-ng#372]
On Macintosh Catalina, I installed the proxychains-ng via homebrew, and I find that there is no proxychains4-daemon:

```
 % pwd
/usr/local/Cellar/proxychains-ng/4.14
 % ls bin 
proxychains4
```
Any hints for this problem?

Regards,
Hy

**Comment by rofl0r** [comment]
the daemon is a new feature that's only available in git. you need to checkout the sources and build it yourself, or ask homebrew folks to add a proxychains-ng-git package that always points to latest master.

**Comment by hongyi-zhao** [comment]
Thank you for telling me this.
