### ISSUE TITLE
Compile failed with  aarch64-linux-android-gcc 

### ISSUE THREAD

**Issue by fuqiangleon** [rofl0r/proxychains-ng#379]
Hey Sir

I am trying to compile and run Proxychains on Android, but there are some errors below when run the "make" command.
Is there any method to fix this?

Seems "ld" of NDK toolchains does not support " -lpthread" , when  I change it to  "-pthread", the "make" command is passed. but I don't know if it is successful, could you give some help, please?

Thx

/Users/Username/android-toolchain/arm64/bin/aarch64-linux-android-gcc -fPIC -Wl,--no-as-needed -ldl -lpthread -Wl,--soname,libproxychains4.so  \
		-shared -o libproxychains4.so src/nameinfo.o src/version.o src/core.o src/common.o src/libproxychains.o src/allocator_thread.o src/rdns.o src/hostsreader.o src/hash.o src/debug.o
/Users/Username/android-toolchain/arm64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find -lpthread
clang90: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by rofl0r** [comment]
i pushed a commit addressing this, please try with current master and report back.

**Comment by fuqiangleon** [comment]
@rofl0r  It is passed and successful with the current master, thx.

**Comment by fuqiangleon** [comment]
one more question, do you know any commands which support Proxychains on android ?  :)

**Comment by rofl0r** [comment]
i'd think everything inside termux environment should work with it.
