### ISSUE TITLE
Under the ssh terminal, Emacs started from within proxychains-ng can't find the correct X11 display device.

### ISSUE THREAD

**Issue by hongyi-zhao** [rofl0r/proxychains-ng#388]
I'use the following command to log in to my ssh server from the pve virtual machine:

![image](https://user-images.githubusercontent.com/11155854/127619954-219f6ad5-0351-4db4-af8f-49a1f90c4633.png)

After I've logged in to, I run the `xlogo' to confirm the X11 forwarding works as shown below:

![image](https://user-images.githubusercontent.com/11155854/127620286-c8eff3ef-000d-4b9c-8cb3-19590139f6b9.png)

And Emacs will also work in X11 mode if I run it directly:

![image](https://user-images.githubusercontent.com/11155854/127620451-cc3efded-a86a-40e2-aeda-df06eb76913a.png)

But if I run Emacs through `proxychains-ng`, it won't find the correct X11 display device, and as a result, it will work with `--no-window-system` option enabled:

![image](https://user-images.githubusercontent.com/11155854/127621095-337a7a41-f9d5-4bcd-a0cd-7ba5c99e73ba.png)

![image](https://user-images.githubusercontent.com/11155854/127619571-7ed2fef7-9a72-4fb0-ba2b-4977c795fd08.png)

I also discussed the problem [here](https://groups.google.com/g/comp.unix.shell/c/7Y6_ISexpzU/m/kocVK7Y9BwAJ).

Any hints for this problem?

Regards,
HY

**Comment by rofl0r** [comment]
yes, you can use the local_net directive to turn off proxification for 127.* subnet, maybe it also works instead to set DISPLAY=:0

**Comment by hongyi-zhao** [comment]
Thank you. It does the trick. I also give some additional comments as following.

> you can use the local_net directive to turn off proxification for 127.* subnet, 

The directive name is `localnet`, and I use the following ones now (uncomment them):
```
 localnet 127.0.0.0/255.0.0.0
 localnet 10.0.0.0/255.0.0.0
 localnet 172.16.0.0/255.240.0.0
 localnet 192.168.0.0/255.255.0.0
```
> maybe it also works instead to set DISPLAY=:0

The local value of this variable DISPLAY is `:1' on my machine:

```
werner@X10DAi:~$ echo $DISPLAY 
:1
```
So, I should use something like: `DISPLAY=:1 ...`.

**Comment by rofl0r** [comment]
> So, I should use something like: DISPLAY=:1 proxychains4 ....

that or just `proxychains4 bash` and then use a proxified shell and e.g. `export DISPLAY=:1`  , `emacs`, whatever

**Comment by hongyi-zhao** [comment]
> that or just `proxychains4 bash` and then use a proxified shell and e.g. `export DISPLAY=:1` , `emacs`, whatever

Do you mean:

```
$ proxychains4 bash
$ export DISPLAY=:1
$ emacs
```
On my side, I want to use them in shell script, it seems that `DISPLAY=:1 proxychains4 ....` is a more concise and convenient way.
