### ISSUE TITLE
Environment variable inheritance for processes started by proxychains-ng.

### ISSUE THREAD

**Issue by hongyi-zhao** [rofl0r/proxychains-ng#389]
When I'm using `proxychains-ng` to start a process, say, foo, what is the exact situation of environment variable inheritance? For example, when I run `foo` in bash as follows:

`$ proxychains4 foo ...`

In the above command, which environment variables will be seen by `foo`?

Regards,
HY

**Comment by rofl0r** [comment]
you can easily check by doing
```
$ bash
$ export FOO=BAR
$ export
$ proxychains4 bash
$ export
```
in short, all environment vars are inherited.
