### ISSUE TITLE
Proxychains not working

### ISSUE THREAD

**Issue by zipp420** [rofl0r/proxychains-ng#390]
Hello evryone,

I ve been facing with this error for 2 days now and i need to ask for help. Hope you guys will help me.

Well i was edditing my proxychains4.conf and did evrything as usual... removed # from dynamic and put it on static, i ve puted some proxys on the bottom and i keep getting this error. Already tried to change tons of proxys but it keeps coming to this error.

<pre>[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/x86_64-linux-gnu/libproxychains.so.4
error: no valid proxy found in config
</pre>

**Comment by zipp420** [comment]
So this is my proxychains.conf

<pre>
# proxychains.conf  VER 4.x
#
#        HTTP, SOCKS4a, SOCKS5 tunneling proxifier with DNS.


# The option below identifies how the ProxyList is treated.
# only one option should be uncommented at time,
# otherwise the last appearing option will be accepted
#
dynamic_chain
#
# Dynamic - Each connection will be done via chained proxies
# all proxies chained in the order as they appear in the list
# at least one proxy must be online to play in chain
# (dead proxies are skipped)
# otherwise EINTR is returned to the app
#
#strict_chain
#
# Strict - Each connection will be done via chained proxies
# all proxies chained in the order as they appear in the list
# all proxies must be online to play in chain
# otherwise EINTR is returned to the app
#
#round_robin_chain
#
# Round Robin - Each connection will be done via chained proxies
# of chain_len length
# all proxies chained in the order as they appear in the list
# at least one proxy must be online to play in chain
# (dead proxies are skipped).
# the start of the current proxy chain is the proxy after the last
# proxy in the previously invoked proxy chain.
# if the end of the proxy chain is reached while looking for proxies
# start at the beginning again.
# otherwise EINTR is returned to the app
# These semantics are not guaranteed in a multithreaded environment.
#
#random_chain
#
# Random - Each connection will be done via random proxy
# (or proxy chain, see  chain_len) from the list.
# this option is good to test your IDS :)

# Make sense only if random_chain or round_robin_chain
#chain_len = 2

# Quiet mode (no output from library)
#quiet_mode

## Proxy DNS requests - no leak for DNS data
proxy_dns 

# set the class A subnet number to use for the internal remote DNS mapping
# we use the reserved 224.x.x.x range by default,
# if the proxified app does a DNS request, we will return an IP from that range.
# on further accesses to this ip we will send the saved DNS name to the proxy.
# in case some control-freak app checks the returned ip, and denies to 
# connect, you can use another subnet, e.g. 10.x.x.x or 127.x.x.x.
# of course you should make sure that the proxified app does not need
# *real* access to this subnet. 
# i.e. dont use the same subnet then in the localnet section
#remote_dns_subnet 127 
#remote_dns_subnet 10
remote_dns_subnet 224

# Some timeouts in milliseconds
tcp_read_time_out 15000
tcp_connect_time_out 8000

### Examples for localnet exclusion
## localnet ranges will *not* use a proxy to connect.
## Exclude connections to 192.168.1.0/24 with port 80
# localnet 192.168.1.0:80/255.255.255.0

## Exclude connections to 192.168.100.0/24
# localnet 192.168.100.0/255.255.255.0

## Exclude connections to ANYwhere with port 80
# localnet 0.0.0.0:80/0.0.0.0

## RFC5735 Loopback address range
## if you enable this, you have to make sure remote_dns_subnet is not 127
## you'll need to enable it if you want to use an application that 
## connects to localhost.
# localnet 127.0.0.0/255.0.0.0

## RFC1918 Private Address Ranges
# localnet 10.0.0.0/255.0.0.0
# localnet 172.16.0.0/255.240.0.0
# localnet 192.168.0.0/255.255.0.0

# ProxyList format
#       type  ip  port [user pass]
#       (values separated by 'tab' or 'blank')
#
#       only numeric ipv4 addresses are valid
#
#
#        Examples:
#
#            	socks5	192.168.67.78	1080	lamer	secret
#		http	192.168.89.3	8080	justu	hidden
#	 	socks4	192.168.1.49	1080
#	        http	192.168.39.93	8080	
#		
#
#       proxy types: http, socks4, socks5
#        ( auth types supported: "basic"-http  "user/pass"-socks )
#
[ProxyList]
# add proxy here ...
# meanwile
# defaults set to "tor"
socks5 	127.0.0.1 9050
</pre>

**Comment by rofl0r** [comment]
you have tor running ?
if so, end of /etc/proxychains.conf should look like
```
[ProxyList]
socks4 127.0.0.1 9050
```

**Comment by zipp420** [comment]
Tor is running, and  i put default proxy(that u writen) on the bottom, but still not working.. same error applay.

**Comment by rofl0r** [comment]
execute `cat /etc/proxychains.conf | grep -v '^#' | base64` and paste the output of the command here

**Comment by zipp420** [comment]
<pre><font color="#5EBDAB">┌──(</font><font color="#277FFF"><b>kalizipp㉿kalizipp</b></font><font color="#5EBDAB">)-[</font><b>~</b><font color="#5EBDAB">]</font>
<font color="#5EBDAB">└─</font><font color="#277FFF"><b>$</b></font> <font color="#5EBDAB">cat</font> <u style="text-decoration-style:single">/etc/proxychains4.conf</u> <font color="#277FFF"><b>|</b></font> <font color="#5EBDAB">grep</font> <font color="#9755B3">-v</font> <font color="#FEA44C">&apos;^#&apos;</font> <font color="#277FFF"><b>|</b></font> <font color="#5EBDAB">base64</font>
CgpkeW5hbWljX2NoYWluCgoKCnByb3h5X2RucyAKCnJlbW90ZV9kbnNfc3VibmV0IDIyNAoKdGNw
X3JlYWRfdGltZV9vdXQgMTUwMDAKdGNwX2Nvbm5lY3RfdGltZV9vdXQgODAwMAoKCgoKCgpbUHJv
eHlMaXN0XQpzb2NrczQJMTI3LjAuMC4xIDkwNTAKCg==
</pre>

**Comment by zipp420** [comment]
This is what i get from it...

**Comment by rofl0r** [comment]
there's no
```
[ProxyList]
socks4 127.0.0.1 9050
```
at the end.

**Comment by zipp420** [comment]
I've had it but the problem was that proxychains.conf was empty and it was not abel to find any proxys so i copyed evrything from proxychains4.conf and put it inside proxychains.conf. Now its working, ty bro.

**Comment by Oussamabenali4** [comment]
try closing all firefox pages of the problem consistent and try again
