### ISSUE TITLE
add proxy

### ISSUE THREAD

**Issue by JKKSI** [rofl0r/proxychains-ng#392]
there is a method that maybe you can recommend me or maybe you add for me and i guess much people we be abble to add file of proxys to the proxychains?, i ask because is lazy add 1 per 1 proxy, a option for add it automatic from a txt file would be great i guess, would be great too that you add default dns cloudflare 1.1.1.1

**Comment by rofl0r** [comment]
use a script that does something like 
```
cat EOF > temp.conf
strict_chain
[ProxyList]
EOF
head -n 20 < leet_proxy_list.txt >> temp.conf
proxychains4 -f temp.conf curl whatsmyip.com
```
