### ISSUE TITLE
proxychains.conf documentation / does it support `include` statements?

### ISSUE THREAD

**Issue by xanoni** [rofl0r/proxychains-ng#395]
Couldn't find the `proxychains.conf` syntax documented ... quick question, does it support `include` statements? E.g. `include some_extra_proxies_proxychains.conf`? (Obviously I tried this syntax and it didn't work.)

If it's not possible, don't worry, I'll find another way.

**Comment by rofl0r** [comment]
not built-in, but you can use the C preprocessor to achieve it:
foo.conf
```
...
[ProxyList]
#include "another.conf"
```

    cpp -P < foo.conf > tmp.conf
    proxychains4 -f tmp.conf myapp

**Comment by xanoni** [comment]
Alrighty
