### ISSUE TITLE
support docker command

### ISSUE THREAD

**Issue by willzhang** [rofl0r/proxychains-ng#397]
is it possible support docker 
```
[root@localhost ~]# proxychains4 docker pull k8s.gcr.io/metrics-server/metrics-server
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.15
Using default tag: latest
Error response from daemon: Get "https://k8s.gcr.io/v2/": dial tcp 108.177.125.82:443: i/o timeout
```

**Comment by rofl0r** [comment]
as far as i know docker is written in go, and go programs are usually statically linked - that means LD_PRELOAD hacks don't work. iirc someone here on a related issue mentioned there's a possibility to link go programs dynamically (was it using gcc-go frontend) ? you might want to look into that and recompile docker in that manner. (search issues here for "go")
