### ISSUE TITLE
Cann't link when compling proxychains on Apple M1 chips

### ISSUE THREAD

**Issue by CharesFang** [rofl0r/proxychains-ng#400]
Hello, I'm get a bit confusedly that when I was going to compile `proxychains` on my M1 chips MacBook Pro. When I was tying to excute the `make` command, I got the erro messages as follows.

```shell
cc -DSUPER_SECURE -DHAVE_CLOCK_GETTIME -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe  -DIS_MAC=1 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/nameinfo.o src/nameinfo.c
printf '#define VERSION "%s"\n' "$(sh tools/version.sh)" > src/version.h
cc -DSUPER_SECURE -DHAVE_CLOCK_GETTIME -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe  -DIS_MAC=1 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/version.o src/version.c
cc -DSUPER_SECURE -DHAVE_CLOCK_GETTIME -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe  -DIS_MAC=1 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/core.o src/core.c
cc -DSUPER_SECURE -DHAVE_CLOCK_GETTIME -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe  -DIS_MAC=1 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/common.o src/common.c
cc -DSUPER_SECURE -DHAVE_CLOCK_GETTIME -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe  -DIS_MAC=1 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/libproxychains.o src/libproxychains.c
cc -DSUPER_SECURE -DHAVE_CLOCK_GETTIME -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe  -DIS_MAC=1 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/allocator_thread.o src/allocator_thread.c
src/allocator_thread.c:327:9: warning: 'PTHREAD_STACK_MIN' macro redefined [-Wmacro-redefined]
#define PTHREAD_STACK_MIN 64*1024
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/limits.h:115:9: note: previous definition is here
#define PTHREAD_STACK_MIN               16384
        ^
1 warning generated.
cc -DSUPER_SECURE -DHAVE_CLOCK_GETTIME -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe  -DIS_MAC=1 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/rdns.o src/rdns.c
cc -DSUPER_SECURE -DHAVE_CLOCK_GETTIME -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe  -DIS_MAC=1 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/hostsreader.o src/hostsreader.c
cc -DSUPER_SECURE -DHAVE_CLOCK_GETTIME -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe  -DIS_MAC=1 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/hash.o src/hash.c
cc -DSUPER_SECURE -DHAVE_CLOCK_GETTIME -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe  -DIS_MAC=1 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/debug.o src/debug.c
cc -fPIC -Wl,--no-as-needed -ldl -lpthread -Wl,--soname,libproxychains4.dylib  \
		-shared -o libproxychains4.dylib src/nameinfo.o src/version.o src/core.o src/common.o src/libproxychains.o src/allocator_thread.o src/rdns.o src/hostsreader.o src/hash.o src/debug.o 
ld: unknown option: --no-as-needed
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libproxychains4.dylib] Error 1
```

It seems that the linker `ld` dosen't own option ` --no-as-needed` . I also find an another issue that found there were some incompatitions on M1 platform. This is the issue [link](https://github.com/rofl0r/proxychains-ng/issues/357)  but I did'nt met the same trouble as his, can you give me some help? Thank you guys! 

Version: 

`proxychain`:`4.15`

`clang`:`clang-1205.0.22.9`

`os`: `Mac OS Big Sur 11.5.2`

**Comment by rofl0r** [comment]
did you run ./configure first ?

**Comment by CharesFang** [comment]
I have chekced again that I do run the ./configure command, but still got the same result.
Here is the ./configure outputs, and the command I ran is `./configure --prefix=/usr/local --bindir=/usr/local/bin --libdir=/usr/local/lib`

```shell

checking whether C compiler works ... yes
checking whether we have GNU-style getservbyname_r() ... no
checking whether we have pipe2() and O_CLOEXEC ... no
checking whether we have SOCK_CLOEXEC ... no
checking whether we have clock_gettime ... yes
checking whether $CC defines __APPLE__ ... yes
checking whether $CC defines __x86_64__ ... no
checking whether $CC defines __FreeBSD__ ... no
checking whether $CC defines __OpenBSD__ ... no
checking whether $CC defines __sun ... no
checking whether $CC defines __HAIKU__ ... no
checking whether we can use -Wl,--no-as-needed ... yes
checking what's the option to use in linker to set library name ... --soname
checking checking whether we can use -lpthread ... yes
Done, now run make && make install


```

**Comment by rofl0r** [comment]
that's not a different output, you need to run make again after having executed ./configure.

**Comment by franktz** [comment]
i have the same error. "ld: unknown option: --no-as-needed" or "ld: unknown option: --soname". any idea?

**Comment by franktz** [comment]
> i have the same error. "ld: unknown option: --no-as-needed" or "ld: unknown option: --soname". any idea?

i modify config.mak to "LD_SET_SONAME = -Wl,-install_name", and modify Makefile from "NO_AS_NEEDED = -Wl,--no-as-needed" to "NO_AS_NEEDED = ", do "make", everything works fine!

**Comment by CharesFang** [comment]
Thank you very much! I just successfully installed proxychain on my M1 chips MacBook by your instructions. But I thought you may need explicitly  state that someone should firstly run commnad `./configure` and then modify the `config.mak` file to  "LD_SET_SONAME = -Wl,-install_name," . I got a littel confusedly at first.

**Comment by franktz** [comment]
> Thank you very much! I just successfully installed proxychain on my M1 chips MacBook by your instructions. But I thought you may need explicitly state that someone should firstly run commnad `./configure` and then modify the `config.mak` file to "LD_SET_SONAME = -Wl,-install_name," . I got a littel confusedly at first.

OK.I update it.

**Comment by franktz** [comment]
> > First run "./configure" to generate config.mak, then modify config.mak from "LD_SET_SONAME = -Wl,-soname" to "LD_SET_SONAME = -Wl,-install_name", and modify Makefile from "NO_AS_NEEDED = -Wl,--no-as-needed" to "NO_AS_NEEDED = ", do "make", everything works fine!
> 
> the problem here is that apparently configure script misdetects the right options. can you run `sh -x ./configure` and paste the output ?

Sure. This's ouput:

$ /bin/sh -x ./configure
+ prefix=/usr/local
+ OUR_CPPFLAGS=
+ i=0
+ set -C
+ :
+ i=1
+ tmpc=./conf735-647-1.c
+ break
+ set +C
+ trap 'rm "$tmpc"' EXIT INT QUIT TERM HUP
+ fat_binary=
+ ignore_cve=no
+ true
+ case $1 in
+ break
+ '[' -z '' ']'
+ exec_prefix=/usr/local
+ '[' -z '' ']'
+ libdir=/usr/local/lib
+ '[' -z '' ']'
+ includedir=/usr/local/include
+ '[' -z '' ']'
+ sysconfdir=/usr/local/etc
+ '[' -z '' ']'
+ bindir=/usr/local/bin
+ '[' -z '' ']'
+ CC=cc
+ echo
+ bsd_detected=false
+ mac_detected=false
+ mac_64=false
+ solaris_detected=false
+ haiku_detected=false
+ check_compile 'whether C compiler works' '' 'int main() {return 0;}'
+ printf 'checking %s ... ' 'whether C compiler works'
checking whether C compiler works ... + printf 'int main() {return 0;}'
+ local res=0
+ cc ./conf735-647-1.c -o ./conf735-647-1.c.out
+ test x0 = x0
+ printf 'yes\n'
yes
+ test x = x
+ rm -f ./conf735-647-1.c.out
+ return 0
+ check_compile 'whether we have GNU-style getservbyname_r()' -DHAVE_GNU_GETSERVBYNAME_R '#define _GNU_SOURCE\n#include <netdb.h>\nint main() {\nstruct servent *se = 0;struct servent se_buf;char buf[1024];\ngetservbyname_r("foo", (void*) 0, &se_buf, buf, sizeof(buf), &se);\nreturn 0;}'
+ printf 'checking %s ... ' 'whether we have GNU-style getservbyname_r()'
checking whether we have GNU-style getservbyname_r() ... + printf '#define _GNU_SOURCE\n#include <netdb.h>\nint main() {\nstruct servent *se = 0;struct servent se_buf;char buf[1024];\ngetservbyname_r("foo", (void*) 0, &se_buf, buf, sizeof(buf), &se);\nreturn 0;}'
+ local res=0
+ cc -DHAVE_GNU_GETSERVBYNAME_R ./conf735-647-1.c -o ./conf735-647-1.c.out
+ res=1
+ test x1 = x0
+ printf 'no\n'
no
+ rm -f ./conf735-647-1.c.out
+ return 1
+ check_compile 'whether we have pipe2() and O_CLOEXEC' -DHAVE_PIPE2 '#define _GNU_SOURCE\n#include <fcntl.h>\n#include <unistd.h>\nint main() {\nint pipefd[2];\npipe2(pipefd, O_CLOEXEC);\nreturn 0;}'
+ printf 'checking %s ... ' 'whether we have pipe2() and O_CLOEXEC'
checking whether we have pipe2() and O_CLOEXEC ... + printf '#define _GNU_SOURCE\n#include <fcntl.h>\n#include <unistd.h>\nint main() {\nint pipefd[2];\npipe2(pipefd, O_CLOEXEC);\nreturn 0;}'
+ local res=0
+ cc -DHAVE_PIPE2 ./conf735-647-1.c -o ./conf735-647-1.c.out
+ res=1
+ test x1 = x0
+ printf 'no\n'
no
+ rm -f ./conf735-647-1.c.out
+ return 1
+ check_compile 'whether we have SOCK_CLOEXEC' -DHAVE_SOCK_CLOEXEC '#define _GNU_SOURCE\n#include <sys/socket.h>\nint main() {\nreturn socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC, 0);}'
+ printf 'checking %s ... ' 'whether we have SOCK_CLOEXEC'
checking whether we have SOCK_CLOEXEC ... + printf '#define _GNU_SOURCE\n#include <sys/socket.h>\nint main() {\nreturn socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC, 0);}'
+ local res=0
+ cc -DHAVE_SOCK_CLOEXEC ./conf735-647-1.c -o ./conf735-647-1.c.out
+ res=1
+ test x1 = x0
+ printf 'no\n'
no
+ rm -f ./conf735-647-1.c.out
+ return 1
+ check_compile 'whether we have clock_gettime' -DHAVE_CLOCK_GETTIME '#define _GNU_SOURCE\n#include <time.h>\nint main() {\nstruct timespec now;clock_gettime(CLOCK_REALTIME, &now);\nreturn now.tv_sec ^ now.tv_nsec;}'
+ printf 'checking %s ... ' 'whether we have clock_gettime'
checking whether we have clock_gettime ... + printf '#define _GNU_SOURCE\n#include <time.h>\nint main() {\nstruct timespec now;clock_gettime(CLOCK_REALTIME, &now);\nreturn now.tv_sec ^ now.tv_nsec;}'
+ local res=0
+ cc -DHAVE_CLOCK_GETTIME ./conf735-647-1.c -o ./conf735-647-1.c.out
+ test x0 = x0
+ printf 'yes\n'
yes
+ test x-DHAVE_CLOCK_GETTIME = x
+ OUR_CPPFLAGS=' -DHAVE_CLOCK_GETTIME'
+ rm -f ./conf735-647-1.c.out
+ return 0
+ check_define __APPLE__
+ printf 'checking whether $CC defines %s ... ' __APPLE__
checking whether $CC defines __APPLE__ ... + local res=1
+ cc -DHAVE_CLOCK_GETTIME -dM -E -
+ grep __APPLE__
+ res=0
+ test x0 = x0
+ printf 'yes\n'
yes
+ return 0
+ mac_detected=true
+ check_define __x86_64__
+ printf 'checking whether $CC defines %s ... ' __x86_64__
checking whether $CC defines __x86_64__ ... + local res=1
+ cc -DHAVE_CLOCK_GETTIME -dM -E -
+ grep __x86_64__
+ res=0
+ test x0 = x0
+ printf 'yes\n'
yes
+ return 0
+ mac_64=true
+ check_define __FreeBSD__
+ printf 'checking whether $CC defines %s ... ' __FreeBSD__
checking whether $CC defines __FreeBSD__ ... + local res=1
+ cc -DHAVE_CLOCK_GETTIME -dM -E -
+ grep __FreeBSD__
+ test x1 = x0
+ printf 'no\n'
no
+ return 1
+ check_define __OpenBSD__
+ printf 'checking whether $CC defines %s ... ' __OpenBSD__
checking whether $CC defines __OpenBSD__ ... + local res=1
+ cc -DHAVE_CLOCK_GETTIME -dM -E -
+ grep __OpenBSD__
+ test x1 = x0
+ printf 'no\n'
no
+ return 1
+ check_define __sun
+ printf 'checking whether $CC defines %s ... ' __sun
checking whether $CC defines __sun ... + local res=1
+ cc -DHAVE_CLOCK_GETTIME -dM -E -
+ grep __sun
+ test x1 = x0
+ printf 'no\n'
no
+ return 1
+ check_define __HAIKU__
+ printf 'checking whether $CC defines %s ... ' __HAIKU__
checking whether $CC defines __HAIKU__ ... + local res=1
+ cc -DHAVE_CLOCK_GETTIME -dM -E -
+ grep __HAIKU__
+ test x1 = x0
+ printf 'no\n'
no
+ return 1
+ echo CC=cc
+ '[' -z '' ']'
+ '[' -z '' ']'
+ '[' -z '' ']'
+ echo prefix=/usr/local
+ echo exec_prefix=/usr/local
+ echo bindir=/usr/local/bin
+ echo libdir=/usr/local/lib
+ echo includedir=/usr/local/include
+ echo sysconfdir=/usr/local/etc
+ '[' no = no ']'
+ echo 'CPPFLAGS+= -DSUPER_SECURE'
+ '[' -z ' -DHAVE_CLOCK_GETTIME' ']'
+ echo 'CPPFLAGS+=  -DHAVE_CLOCK_GETTIME'
+ check_link 'whether we can use -Wl,--no-as-needed' -Wl,--no-as-needed 'int main() { return 0; }'
+ printf 'checking %s ... ' 'whether we can use -Wl,--no-as-needed'
checking whether we can use -Wl,--no-as-needed ... + local res=0
+ check_link_silent -Wl,--no-as-needed 'int main() { return 0; }'
+ printf 'int main() { return 0; }'
+ cc -DHAVE_CLOCK_GETTIME -Wl,--no-as-needed ./conf735-647-1.c -o ./conf735-647-1.c.out
+ rm -f ./conf735-647-1.c.out
+ test x0 = x0
+ printf 'yes\n'
yes
+ return 0
+ LD_SONAME_FLAG=
+ printf 'checking what'\''s the option to use in linker to set library name ... '
checking what's the option to use in linker to set library name ... + for o in --soname -h -soname -install_name
+ check_link_silent '-shared -Wl,--soname,libconftest.so' 'void test_func(int a) {}'
+ printf 'void test_func(int a) {}'
+ cc -DHAVE_CLOCK_GETTIME -shared -Wl,--soname,libconftest.so ./conf735-647-1.c -o ./conf735-647-1.c.out
+ rm -f ./conf735-647-1.c.out
+ LD_SONAME_FLAG=--soname
+ break
+ '[' -z --soname ']'
+ echo --soname
--soname
+ echo 'LD_SET_SONAME = -Wl,--soname,'
+ check_link 'checking whether we can use -lpthread' -lpthread 'int main(){return 0;}'
+ printf 'checking %s ... ' 'checking whether we can use -lpthread'
checking checking whether we can use -lpthread ... + local res=0
+ check_link_silent -lpthread 'int main(){return 0;}'
+ printf 'int main(){return 0;}'
+ cc -DHAVE_CLOCK_GETTIME -lpthread ./conf735-647-1.c -o ./conf735-647-1.c.out
+ rm -f ./conf735-647-1.c.out
+ test x0 = x0
+ printf 'yes\n'
yes
+ return 0
+ echo 'PTHREAD = -lpthread'
+ make_cmd=make
+ ismac
+ true
+ echo LDSO_SUFFIX=dylib
+ echo MAC_CFLAGS+=-DIS_MAC=1
+ ismac64
+ true
+ '[' '' = 1 ']'
+ echo 'Done, now run make && make install'
Done, now run make && make install
+ rm ./conf735-647-1.c

**Comment by rofl0r** [comment]
thanks, the commit just before the 4.15 release apparently caused this new issue - misdetecting linker flags.
