### ISSUE TITLE
Find the pid of the application launched by proxychains-ng.

### ISSUE THREAD

**Issue by hongyi-zhao** [rofl0r/proxychains-ng#401]
See the following example: 
```
$ proxychains-ng-http google-chrome >/dev/null 2>&1 &
[1] 2226205
$ wmctrl -lp | grep 'Google Chrome'
0x00400020  0 1458872 X10DAi-00 New Tab - Google Chrome
```
What's the relationship between `2226205` and `1458872`? Is it possible to find the PID of the application, i.e., `1458872`, launched by `proxychains-ng` based on the background `proxychains-ng` PID, i.e., `2226205`? See [here](https://groups.google.com/g/comp.unix.shell/c/dVV8rtQUJEI) for the relevant discussion.

Regards,
HY

**Comment by rofl0r** [comment]
proxychains-ng exec's the application so there's only one pid involved - proxychains' pid becomes that of the app. what your script wrapper does is unclear though, maybe you should use `exec proxychains-ng whatever` in your script.

**Comment by hongyi-zhao** [comment]
The wrapper is rather simple as follows according to your advice above:
```
#!/usr/bin/env bash
exec proxychains4-daemon >/dev/null 2>&1 &
exec proxychains4 -q -f $proxychains_conf "$@"
```
But still obtain the similar result I've posted before:
```
$ proxychains-ng-http google-chrome >/dev/null 2>&1 &
[1] 2412604
$ wmctrl -lp |grep -i 'chrome'
0x0040003e  0 16948  X10DAi-00 New Tab - Google Chrome
```

**Comment by rofl0r** [comment]
you can't exec 2 things - only the first one will be executed

**Comment by hongyi-zhao** [comment]
How can the script be adjusted to suit the current situation?

**Comment by rofl0r** [comment]
you remove the proxychains-daemon line and start it by hand if it isn't already running. optimally you just start it on system boot by your service supervisor.

**Comment by hongyi-zhao** [comment]
Done according to your above suggestion:

The proxychains4-daemon script:
```
#!/usr/bin/env bash
if type -fp proxychains4-daemon >/dev/null && ! ps h -o cmd | grep -q '^proxychains4-daemon\b'; then
  proxychains4-daemon >/dev/null 2>&1 &
fi
```

The wrapper script:
```
#!/usr/bin/env bash
proxychains_conf=/path/to/proxychains-ng-http.conf
if type -fp proxychains4-daemon >/dev/null && ! ps h -o cmd | grep -q '^proxychains4-daemon\b'; then
  proxychains4-daemon >/dev/null 2>&1 &
fi
```
But still obtain the similar result I've posted before:
```
$ proxychains-ng-http google-chrome >/dev/null 2>&1 &
[2] 1780767
$ wmctrl -lp |grep -i 'chrome'
0x00400029  0 2775241 X10DAi-00 New Tab - Google Chrome
```

**Comment by rofl0r** [comment]
maybe you try with something simpler than chrome.

e.g. proxy-foo-wrapper sleep 1000
then you can ps aux | grep sleep and check the whether the pid matches.

**Comment by hongyi-zhao** [comment]
Yes, it confirms your conclusion:
```
werner@X10DAi-00:~$ proxychains-ng-http sleep 1000 >/dev/null 2>&1 &
[1] 885077
werner@X10DAi-00:~$ ps -o pid,cmd | grep 'sleep 1000$'
 885077 sleep 1000
```
