### ISSUE TITLE
Running inside a container show localhost

### ISSUE THREAD

**Issue by kerenskybr** [rofl0r/proxychains-ng#402]
Hi,
I'm trying to run proxychains from a docker container. I'm using the script given here: https://github.com/rofl0r/proxychains-ng/issues/246 but inside container, it's showing localhost:
```
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  timeout
curl: (7) Couldn't connect to server
```
It's working nicely outside of container. What i missing?

**Comment by rofl0r** [comment]
is the container running tor ?

**Comment by kerenskybr** [comment]
The "issue" was my fault. I changed to use vars `(PROXY_DNS=$1, PROXY_PORT=$2)` and forget to change `$@` to the next variable `($3)`. Silly mistake. Then `proxychains` was failing and using default config.

Now everything is working as expected
