### ISSUE TITLE
Possible to exclude certain addresses or ports

### ISSUE THREAD

**Issue by ashokfernandez** [rofl0r/proxychains-ng#41]
I'm using proxychains-ng around a node.js script, however I don't want connections to my database to be proxied. My database isn't hosted locally, it's remotely hosted on AWS, will the localnet rules work for this? 

I've tried `localnet 0.0.0.0:3306/0.0.0.0` to exclude connections to port 3306 (the port I connect to my AWS database over) but it seems to have no affect.

**Comment by a7903** [comment]
@ashokfernandez  have solve this problem? now i have the same problem,can you give me some suggestion?
