### ISSUE TITLE
Only first IP returned by getaddrinfo() is used, which may cause connection failures

### ISSUE THREAD

**Issue by i-rinat** [rofl0r/proxychains-ng#415]
In configurations with `proxy_dns` enabled, only first IP address is used by proxychains, while others are discarded.
If for some reason a server behind the first IP address is down, then despite other addresses having working servers behind them, connections through proxychains will fail. A proxied application has no idea there are other addresses, so it doesn't try them.

A possible workaround is to disable `proxy_dns`, but that's less than ideal solution.

**Comment by i-rinat** [comment]
Say, remote name `site.com` resolves to a list of IP addresses: `11.22.33.1`, `11.22.33.2`, and `11.22.33.3`. Then when an application tries to resolve `site.com`, proxychains remembers that `site.com` corresponds to `11.22.33.1` and returns to the application address `224.0.0.1`. When the application tries to connect to `224.0.0.1`, proxychains connects to `11.22.33.1`, right?

Then, let's assume that `11.22.33.1` is down, but `11.22.33.2` and `11.22.33.3` are up and running. Then an application, say `curl`, when connecting directly to `site.com` first will try `11.22.33.1`. That will not be successful, but the application (`curl`) will immediately try connecting to `11.22.33.2`, and will succeed. User will perceive a delay, not fail-to-connect. But if `curl` is proxied by proxychains, it will see only `224.0.0.1`. Connecting to that address will be unsuccessful, because `11.22.33.1` is down.

**Comment by rofl0r** [comment]
this is not a bug report, but a question that's already been answered in my reply, which you apparently didnt understand, and instead continued to reason about your imagined fault scenario. besides, the question was entirely unnecessary as a simple test would already have provided the answer.

**Comment by i-rinat** [comment]
I did not imagine the scenario. I experienced the scenario. The only thing I changed was specific site name and its IP addresses.

**Comment by rofl0r** [comment]
that's not possible, because when `proxy_dns` is active, no DNS lookup is done *at all* by proxychains. what the target proxy does with the DNS name is outside our control. so the issue lies either on proxy end or you mistakenly though proxy_dns is active when it wasn't.

**Comment by i-rinat** [comment]
> no DNS lookup is done at all by proxychains. what the target proxy does with the DNS name

Okay. I now see I'm wrong.
I was under the impression that proxychains does the name resolution by connecting to some (public) DNS servers. Don't know where it came from.
