### ISSUE TITLE
CMake will write proxychains inject log into makefiles

### ISSUE THREAD

**Issue by shirok1** [rofl0r/proxychains-ng#418]
This happened when I was trying to install MikTeX on Manjaro using pikaur.
![image](https://user-images.githubusercontent.com/12044683/146940598-91e8918a-ea94-4659-bb09-fb7730b63eb2.png)

**Comment by rofl0r** [comment]
well, in that case use the "quiet" switch -q for proxychains. or even better dont use the PoS cmake.
