### ISSUE TITLE
doesn't work in macos 12.1 (x86_64)

### ISSUE THREAD

**Issue by 1amfine2333** [rofl0r/proxychains-ng#419]
Environment: macOS 112.1 x86_64, SIP disabled
![image](https://user-images.githubusercontent.com/24676292/147636233-2b170e2e-8c3c-4ff0-ba43-68c74095622a.png)

**Comment by rofl0r** [comment]
paste your config.mak

you need to use curl from homebrew, not from system path

**Comment by alemens** [comment]
# Environment 
- Shell `zsh 5.8 (x86_64-apple-darwin21.0)`
- macOS Monterey Version 12.1 x86_64 
- SIP disabled

# Steps to reproduce 
## By compiling from source 
- `wget -P ~/Downloads https://github.com/rofl0r/proxychains-ng/archive/refs/heads/master.zip`
- `unzip ~/Downloads/master.zip -d ~/Downloads`
- `cd ~/Downloads/proxychains-ng-master`
- `sh configure`
- `make && make install` 
  - at this point your app created a mess into file system, so rather than "paste your config.mak" could we avoid to let people mess up with the file-system by changing [proxychains-ng.rb](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/proxychains-ng.rb) and paste you @rofl0r some response with a cleaner result management? 
  - Also what do you mean by saying "you need to use curl from homebrew, not from system path"?

## By using Homebrew
- Install proxychains with **Homebrew**  
```bash
➜  ~ brew install proxychains-ng                                                           
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 2 formulae.

==> Downloading https://ghcr.io/v2/homebrew/core/proxychains-ng/manifests/4.15
Already downloaded: /Users/stack/Library/Caches/Homebrew/downloads/9ae1b765cd32b5e9af00b18aef3babed1a6d0b4cad6c6a4de2e8506b544b1832--proxychains-ng-4.15.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/proxychains-ng/blobs/sha256:c1c7e76c78d7f5e0917a17605caf2f4109491df05322faa7a056d65f72a928cd
Already downloaded: /Users/stack/Library/Caches/Homebrew/downloads/1961bb086bed8fe18144ccbef059b5e6cb3cbd70e1ee8effd707ffd4328d505e--proxychains-ng--4.15.monterey.bottle.tar.gz
==> Pouring proxychains-ng--4.15.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/proxychains-ng/4.15: 10 files, 207KB
==> Running `brew cleanup proxychains-ng`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
➜  ~   
```

- Run Tor **successfully**
```bash
➜  ~ brew services run tor
==> Successfully ran `tor` (label: homebrew.mxcl.tor)
➜  ~ 
```

- Try proxychains **fail** 
```bash 
➜  ~ proxychains4 curl https://check.torproject.org/api/ip
[proxychains] config file found: /usr/local/etc/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.15/lib/libproxychains4.dylib
[proxychains] DLL init: proxychains-ng 4.15
{"IsTor":false,"IP":"xx.xx.xx.xxx"}%  
```

**Comment by 1amfine2333** [comment]
> paste your config.mak
> 
> you need to use curl from homebrew, not from system path

No problem with the config, i use curl installed through brew, but it doesn’t work。
![image](https://user-images.githubusercontent.com/24676292/147715665-fcccd588-0053-476a-86d0-b68c6e29e1f7.png)

**Comment by alemens** [comment]
# By compiling from source _it works !_

## Environment 
- Shell Version zsh 5.8 (x86_64-apple-darwin21.0)
- macOS Monterey Version 12.1 x86_64 
- SIP disabled

## Steps to reproduce 
- `wget -P ~/Downloads https://github.com/rofl0r/proxychains-ng/archive/refs/heads/master.zip`
- `unzip ~/Downloads/master.zip -d ~/Downloads`
- `cd ~/Downloads/proxychains-ng-master`
- `sh configure`
- `make && make install` 
  
> paste your config.mak
> @rofl0r 

```bash
➜  ~ cat ~/Downloads/proxychains-ng-master/config.mak 

CC=cc
CPPFLAGS=-I/usr/local/opt/zlib/include
USER_LDFLAGS=-L/usr/local/opt/zlib/lib
prefix=/usr/local
exec_prefix=/usr/local
bindir=/usr/local/bin
libdir=/usr/local/lib
includedir=/usr/local/include
sysconfdir=/usr/local/etc
CPPFLAGS+= -DSUPER_SECURE
CPPFLAGS+=  -DHAVE_CLOCK_GETTIME
NO_AS_NEEDED=
LD_SET_SONAME = -Wl,-install_name,
LIBDL = -ldl
PTHREAD = -lpthread
LDSO_SUFFIX=dylib
MAC_CFLAGS+=-DIS_MAC=1
CFLAGS+=-DMONTEREY_HOOKING
➜  ~ 
```

- Compiling from source created the following utility paths 
  - `/usr/local/lib/libproxychains4.dylib`
  - `/usr/local/bin/proxychains4-daemon`                                            
  - `/usr/local/bin/proxychains4`      

- Configuration looks like this 
```bash
➜  ~ cat /usr/local/etc/proxychains.conf
# proxychains.conf  VER 4.x
dynamic_chain
proxy_dns
tcp_read_time_out 15000
tcp_connect_time_out 8000
[ProxyList]
socks4 	127.0.0.1 9050
socks5 	127.0.0.1 9050
➜  ~ 
```                                            

# **It works !**
```bash
➜  ~ /usr/local/bin/proxychains4 curl https://check.torproject.org/api/ip 
[proxychains] config file found: /usr/local/etc/proxychains.conf
[proxychains] preloading /usr/local/lib/libproxychains4.dylib
[proxychains] DLL init: proxychains-ng 4.15
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  127.0.0.1:9050 <--denied
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  check.torproject.org:443  ...  OK
{"IsTor":true,"IP":"xxx.xx.xxx.xx"}%                                                                                                                                                ➜  ~ 
```

**Comment by 1amfine2333** [comment]
> # By compiling from source _it works !_
> ## Environment
> * Shell Version zsh 5.8 (x86_64-apple-darwin21.0)
> * macOS Monterey Version 12.1 x86_64
> * SIP disabled
> 
> ## Steps to reproduce
> ```shell
> ➜  ~ wget -P ~/Downloads https://github.com/rofl0r/proxychains-ng/archive/refs/heads/master.zip
> ```
> 
> ```shell
> ➜  ~ unzip ~/Downloads/master.zip -d ~/Downloads
> ```
> 
> ```shell
> ➜  ~ cd ~/Downloads/proxychains-ng-master
> ```
> 
> ```shell
> ➜  ~ sh configure
> ```
> 
> ```shell
> ➜  ~ make && make install
> ```
> 
> > paste your config.mak
> > @rofl0r
> 
> ```shell
> ➜  ~ cat ~/Downloads/proxychains-ng-master/config.mak 
> 
> CC=cc
> CPPFLAGS=-I/usr/local/opt/zlib/include
> USER_LDFLAGS=-L/usr/local/opt/zlib/lib
> prefix=/usr/local
> exec_prefix=/usr/local
> bindir=/usr/local/bin
> libdir=/usr/local/lib
> includedir=/usr/local/include
> sysconfdir=/usr/local/etc
> CPPFLAGS+= -DSUPER_SECURE
> CPPFLAGS+=  -DHAVE_CLOCK_GETTIME
> NO_AS_NEEDED=
> LD_SET_SONAME = -Wl,-install_name,
> LIBDL = -ldl
> PTHREAD = -lpthread
> LDSO_SUFFIX=dylib
> MAC_CFLAGS+=-DIS_MAC=1
> CFLAGS+=-DMONTEREY_HOOKING
> ➜  ~ 
> ```
> 
> * Compiling from source created the following utility paths
>   
>   * `/usr/local/lib/libproxychains4.dylib`
>   * `/usr/local/bin/proxychains4-daemon`
>   * `/usr/local/bin/proxychains4`
> * Configuration looks like this
> 
> ```shell
> ➜  ~ cat /usr/local/etc/proxychains.conf
> # proxychains.conf  VER 4.x
> dynamic_chain
> proxy_dns
> tcp_read_time_out 15000
> tcp_connect_time_out 8000
> [ProxyList]
> socks4 	127.0.0.1 9050
> socks5 	127.0.0.1 9050
> ➜  ~ 
> ```
> 
> # **It works !**
> * Run Tor **successfully**
> 
> ```shell
> ➜  ~ brew services run tor
> ==> Successfully ran `tor` (label: homebrew.mxcl.tor)
> ➜  ~ 
> ```
> 
> * Run proxychains **successfully**
> 
> ```shell
> ➜  ~ /usr/local/bin/proxychains4 curl https://check.torproject.org/api/ip
> [proxychains] config file found: /usr/local/etc/proxychains.conf
> [proxychains] preloading /usr/local/lib/libproxychains4.dylib
> [proxychains] DLL init: proxychains-ng 4.15
> [proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  127.0.0.1:9050 <--denied
> [proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  check.torproject.org:443  ...  OK
> {"IsTor":true,"IP":"xxx.xxx.xxx.xxx"}%                                                                                                                                              ➜  ~ 
> ```

 It works ! Add ```CFLAGS+=-DMONTEREY_HOOKING```at the end of config.mak,thanks!
![image](https://user-images.githubusercontent.com/24676292/147718075-8ae5fcf1-5811-424b-895b-42a121912858.png)

**Comment by alemens** [comment]
# By using Homebrew **it fail !**

## Environment 
- Shell `zsh 5.8 (x86_64-apple-darwin21.0)`
- macOS Monterey Version 12.1 x86_64 
- SIP disabled

## Steps to reproduce  
- Install proxychains with **Homebrew**  
```bash
➜  ~ brew install proxychains-ng                                                           
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 2 formulae.

==> Downloading https://ghcr.io/v2/homebrew/core/proxychains-ng/manifests/4.15
Already downloaded: /Users/stack/Library/Caches/Homebrew/downloads/9ae1b765cd32b5e9af00b18aef3babed1a6d0b4cad6c6a4de2e8506b544b1832--proxychains-ng-4.15.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/proxychains-ng/blobs/sha256:c1c7e76c78d7f5e0917a17605caf2f4109491df05322faa7a056d65f72a928cd
Already downloaded: /Users/stack/Library/Caches/Homebrew/downloads/1961bb086bed8fe18144ccbef059b5e6cb3cbd70e1ee8effd707ffd4328d505e--proxychains-ng--4.15.monterey.bottle.tar.gz
==> Pouring proxychains-ng--4.15.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/proxychains-ng/4.15: 10 files, 207KB
==> Running `brew cleanup proxychains-ng`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
➜  ~   
```
- Homebrew installation created the following utility paths 
  - `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/proxychains-ng.rb`
  - `/usr/local/var/homebrew/locks/proxychains-ng.formula.lock`
  - `/usr/local/etc/proxychains.conf`

- Run Tor **ok**
```bash
➜  ~ brew services run tor
==> Successfully ran `tor` (label: homebrew.mxcl.tor)
➜  ~ 
```

- Proxychains **fail** 
```bash 
➜  ~ proxychains4 curl https://check.torproject.org/api/ip
[proxychains] config file found: /usr/local/etc/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.15/lib/libproxychains4.dylib
[proxychains] DLL init: proxychains-ng 4.15
{"IsTor":false,"IP":"xx.xx.xx.xxx"}%  
➜  ~ 
```

**Comment by alemens** [comment]
# Waiting the merge 
## After compiling from source, `brew doctor` generate this _warning_ of course: 
```zsh
Warning: Unbrewed dylibs were found in /usr/local/lib.

Unexpected dylibs:
  /usr/local/lib/libproxychains4.dylib
```
