### ISSUE TITLE
Critical regeression: Proxychains no longer uses local DNS, even when told so

### ISSUE THREAD

**Issue by ShadowOfHarbringer** [rofl0r/proxychains-ng#42]
Sometimes i need my proxychains to use local dns instead the remote one (i put an entry into my /etc/hosts so i don't have to write remote server IP every time). That works with proxychains 4.2.0, but not later versions.

Tried the same command with both versions 4.2.0 and 4.7. The version 4.8.1 has the same bug.
Reproductible: ALWAYS

My proxychains.conf:
random_chain
chain_len = 1
# proxy_dns

remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000
localnet 127.0.0.0/255.0.0.0

[ProxyList]
socks5         10.XX.XX.XX      45671
socks5         10.XX.XX.XX      45672
socks5         10.XX.XX.XX      45673
socks5         10.XX.XX.XX      45674
socks5         10.XX.XX.XX      45675
socks5         10.XX.XX.XX      45676
socks5         10.XX.XX.XX      45677
socks5         10.XX.XX.XX      45678

Version 4.2.0 Output:
$ proxychains -f /path/to/proxychains-test.conf ssh root@REMOTE.SERVER.IP.ADDRESS

[proxychains] preloading /usr/lib/libproxychains.so.4.2.0
[proxychains] DLL init
[proxychains] Random chain  ...  10.XX.XX.XX  ...  REMOTE.SERVER.IP.ADDRESS:22  ...  OK

$ proxychains -f /path/to/proxychains-test.conf ssh root@LOCAL.ETC.HOSTS.NAME

[proxychains] preloading /usr/lib/libproxychains.so.4.2.0
[proxychains] DLL init
[proxychains] Random chain  ...  10.XX.XX.XX  ...  REMOTE.SERVER.IP.ADDRESS:22  ...  OK
# 

Version 4.7.0 Output:

$ proxychains -f /path/to/proxychains-test.conf ssh root@REMOTE.SERVER.IP.ADDRESS

[proxychains] preloading /usr/lib64/libproxychains.so.4.7
[proxychains] DLL init
[proxychains] Random chain  ...  10.XX.XX.XX  ...  REMOTE.SERVER.IP.ADDRESS:22  ...  OK

$ proxychains -f /path/to/proxychains-test.conf ssh root@LOCAL.ETC.HOSTS.NAME

[proxychains] config file found: /freak/crypt/safe0/etc.conf/proxychains-test.conf
[proxychains] preloading /usr/lib64/libproxychains.so.4.7
[proxychains] DLL init
ssh-noproxy: Could not resolve hostname LOCAL.ETC.HOSTS.NAME: No address associated with hostname
# 

As you can see, when i specify remote host's IP, it works. It does not work when i tell it to resolve a local host.
I suspect it always uses remote host DNS instead local one's, even when it's turned off in the config file.

SYSTEM: Gentoo Linux 64Bit
Kernel: 3.10.41

**Comment by myfingerhurt** [comment]
I have similar issues. The remote DNS seems not working.
The remote DNS results only got 224.0.0.1 or 127.0.0.1 were same as what I had set remoteaa_dns _subnet in CONFIG file.

-------------------------MY CONFIG 1--------------------
strict_chain
proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000
localnet 192.168.1.0/255.255.255.0
http 192.168.1.2 3128
--------------------------------------------------------------

--------------------------WHY THE GOOGLE DNS RESULT GOT 224.0.0.1 ????----------------------------

$ ./proxychains-ng/proxychains4 -f ./proxychains-ng/src/proxychains.conf wget google.com
[proxychains] config file found: ./proxychains-ng/src/proxychains.conf
[proxychains] preloading ./proxychains-ng/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.11
--2016-05-13 01:43:39--  http://google.com/
Resolving google.com (google.com)... 224.0.0.1
Connecting to google.com (google.com)|224.0.0.1|:80... [proxychains] Strict chain  ...  192.168.1.2:3128  ...  google.com:80 <--denied
failed: Connection refused.
------------------------------------------------------------------------------

-------------------------MY CONFIG 2--------------------
strict_chain
#proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000
localnet 192.168.1.0/255.255.255.0
http 192.168.1.2 3128
-------------------------------------------------------------------

--------------------------------MY LOCAL DNS  DIDN'T RESOVLE GOOGLE ---------------------------------

$ ./proxychains-ng/proxychains4 -f ./proxychains-ng/src/proxychains.conf wget google.com
[proxychains] config file found: ./proxychains-ng/src/proxychains.conf
[proxychains] preloading ./proxychains-ng/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.11
--2016-05-13 01:10:59--  http://google.com/
Resolving google.com (google.com)... failed: Name or service not known.
wget: unable to resolve host address ‘google.com’

-----------------------------MY LOCAL DNS ONLY RESOLVE COMPANY DOMAINS------------------------

$ ./proxychains-ng/proxychains4 -f ./proxychains-ng/src/proxychains.conf wget http://my.company.co.jp
[proxychains] config file found: ./proxychains-ng/src/proxychains.conf
[proxychains] preloading ./proxychains-ng/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.11
--2016-05-13 01:13:30--  http://my.company.co.jp/
Resolving my.company.co.jp (my.company.co.jp)... 192.168.1.13
Connecting to my.company.co.jp (my.company.co.jp)|192.168.1.13|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 129 [text/html]
Saving to: ‘index.html’

index.html                  100%[==========================================>]     129  --.-KB/s    in 0s

2016-05-13 01:13:31 (12.6 MB/s) - ‘index.html’ saved [129/129]
------------------------------------------------------------------------------------------------------------------------------------

Problem is REMOTE DNS do not working.

**Comment by rofl0r** [comment]
well if your proxy doesnt support DNS lookup, you need to turn off remote_dns.
