### ISSUE TITLE
Mac macOS 12.1 Monterey x86_64 | Proxychains terminal session do not remain active while navigating the web in a gui Browser Safari Chromium Google Chrome Firefox

### ISSUE THREAD

**Issue by alemens** [rofl0r/proxychains-ng#420]
# _Issue:_ Proxychains terminal session do not remain active while navigating the web in a gui Browser e.g. Safari, Chromium, Google Chrome or Firefox

## Environment 
- Shell Version zsh 5.8 (x86_64-apple-darwin21.0)
- macOS Monterey Version 12.1 x86_64 
- SIP disabled
- Safari Version 15.2

## Steps to reproduce 
- Get proxychains [by compiling from source](https://github.com/rofl0r/proxychains-ng/issues/419)
- Run proxychains4 to open the browser app 
```bash
➜  ~ /usr/local/bin/proxychains4 open /Applications/Safari.app
[proxychains] config file found: /usr/local/etc/proxychains.conf
[proxychains] preloading /usr/local/lib/libproxychains4.dylib
[proxychains] DLL init: proxychains-ng 4.15
➜  ~ 
```

## Expected behaviour 
- As you see in this you [tube video tutorial](https://youtu.be/NN9fQwiomAU?t=423)
- Proxychains should remain active in the terminal 
- Instead while Browser session opened the terminal session close  

## Achievement 
- let a proxychains terminal session remain active while navigating in the Browser

**Comment by rofl0r** [comment]
look for other chrome-related issues. the tl;dr is: use proxy_dns_daemon mode.

**Comment by alemens** [comment]
> look for other chrome-related issues. the tl;dr is: use proxy_dns_daemon mode.

Hi @rofl0r this works
```bash
proxychains4 chromium check.torproject.org/api/ip
```

#### But DNS leak it does **fail** !
```bash 
proxychains4 chromium dnsleaktest.com
```

Should I add some line to config?  
###### Now looks like this 
```c
dynamic_chain
proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000
[ProxyList]
socks4 	127.0.0.1 9050
socks5 	127.0.0.1 9050
```

**Comment by alemens** [comment]
> look for other chrome-related issues. the tl;dr is: use proxy_dns_daemon mode.

Hi @rofl0r after `brew install --cask chromium` this works
```bash
proxychains4 chromium check.torproject.org/api/ip
```

#### But DNS leak it does **fail** !
```bash 
proxychains4 chromium dnsleaktest.com
```

Should I add some line to config?  
###### Now looks like this 
```c
dynamic_chain
proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000
[ProxyList]
socks4 	127.0.0.1 9050
socks5 	127.0.0.1 9050
```

**Comment by rofl0r** [comment]
read commit message 7fe813949644b115b0127279517dc7c0ee2d63b9 and use that
