### ISSUE TITLE
Proxychains works wrong.

### ISSUE THREAD

**Issue by KINGANDll** [rofl0r/proxychains-ng#421]
My system is CentOS7.9 in the 192.168.1.12 LAN address. I need to do a proxy from another computer in 192.168.1.11 in the same local area network. I have alread test that proxy is success on my phone. 
The problem is, I tried proxychains and proxychains-ng, no matter how i edit the proxychains.conf, it doesn't work. It always stop at here:

`and@kingdom 14:30:16 /usr/local/stow$ proxychains4 curl cip.cc  

[proxychains] config file found: /etc/proxychains.conf  

[proxychains] preloading /usr/local/lib/libproxychains4.so  

[proxychains] DLL init: proxychains-ng 4.15  

[proxychains] Dynamic chain  ...  192.168.1.11:10808  ...  192.168.1.11:10809  ...  cip.cc:80 ^C  
`

It stop here no matter how long i wait. Sometimes it would tell me timeout....
In the 192.168.1.11, the proxy PC, the V2Ray show me this:

`14:49:09 tcp:192.168.1.12:51540 accepted tcp:192.168.1.11:10809 [proxy]`

This is my proxychains.conf:

`dynamic_chain

proxy_dns

remote_dns_subnet 224

tcp_read_time_out 15000

tcp_connect_time_out 8000

[ProxyList]

socks5 	192.168.1.11 10808

http	192.168.1.11 10809`

That's all my problem. I tried annotation the "#proxy_dns", "#remote_dns_subnet", no work. I also tried to add "https 192.168.1.11 10808" or 10809 port. No work.

_By the way, it works when i set the proxy PC' v2ray to direct, of course i can only connect the direct website.....
Proxychains-ng is the first pack i installed. I remove /usr/bin/proxy...   and /usr/lib/proxy... and /etc/proxychains.conf to uninstall it.
I've tormented by this problem two days. 
Very very thank you!_

**Comment by rofl0r** [comment]
what you write is too confusing to follow. if you want help, describe with fewest words possible your scenario, all the IPs involved, which proxy sw, etc. maybe then someone came make sense out of it.

**Comment by KINGANDll** [comment]
I need to deploy a server A at 192.168.1.12. It would use the proxychains to connect another PC B in 192.168.1.11. The B has installed V2rayN and i have tested it, works well on my phone and vmware.
But proxychains-ng can not work well on the server, it always stop at here:

`$ proxychains4 curl cip.cc`
`[proxychains] config file found: /etc/proxychains.conf`
`[proxychains] preloading /usr/local/lib/libproxychains4.so`
`[proxychains] DLL init: proxychains-ng 4.15`
`[proxychains] Dynamic chain  ...  192.168.1.11:10808  ...  192.168.1.11:10809  ...  cip.cc:80 ^C`

The system of server A is CentOS7. Here is proxychains.conf:

`dynamic_chain`
`proxy_dns`
`remote_dns_subnet 224`
`tcp_read_time_out 15000`
`tcp_connect_time_out 8000`
`[ProxyList]`
`socks5 192.168.1.11 10808`
`http 192.168.1.11 10809`

I'm really sorry that i caused some inconvenience to you.

**Comment by rofl0r** [comment]
so why do you have 2 proxies there ?
```
socks5 192.168.1.11 10808
http 192.168.1.11 10809
```

**Comment by KINGANDll** [comment]
Because V2ray has 2 ports to accept different request. I've tried that set both socks and http to 10808 port or 10809. No work.

And my server'git can use proxy by global config proxy setting. It works well, it's very strange.
The git global setting is here:

    git config --global proxy.http 'socks5://192.168.1.1:10808'

Oh no, i get it, i dont know why that it works when i delete the line of "http 192.16....".
Why only socks5 can works well.

Anyway thanks for your respond, really really thank you.

**Comment by rofl0r** [comment]
if you put 2 proxies in config with `dynamic_chain` or `strict_chain` then both will be used in specified order one after another. please read config file comments in src/proxychains.conf to understand what they do.
anyway, since you solved the issue, closing.
