### ISSUE TITLE
Let `proxychains-ng` temporarily use the proxy server passed from the command line environment variable instead of through the conf file.

### ISSUE THREAD

**Issue by hongyi-zhao** [rofl0r/proxychains-ng#425]
Is this possible: Let `proxychains-ng` temporarily use the proxy server passed from the command line environment variable instead of through the conf file.

Regards,
HZ

**Comment by rofl0r** [comment]
duplicate of https://github.com/rofl0r/proxychains-ng/issues/270

**Comment by hongyi-zhao** [comment]
A specific example is given [here](https://github.com/rofl0r/proxychains-ng/issues/246#issuecomment-401019706).
