### ISSUE TITLE
How can I update any browser (like Chrome or Firefox) with proxychains4 as a proxy?

### ISSUE THREAD

**Issue by Hyper-glitch** [rofl0r/proxychains-ng#444]
I mean in /etc/proxychains.conf I have my own proxies for proxychains, but I need to interact with proxychains via ip:port like a service from remote server.
I also tried start browser with proxychains like
```bash
proxychains4 firefox
```
but then I checked ip, it wasn't the last proxy from proxychains

**Comment by rofl0r** [comment]
> but I need to interact with proxychains via ip:port like a service from remote server.

i don't get what you mean with that


basically to run any modern, hyper-complex browser through proxychains, you have to use the proxydns_daemon method added in 4.15. everything else is known to either not work or even cause issues.

**Comment by Hyper-glitch** [comment]
I mean that we can use tor service as a proxy, I also can update browser with selenium, because tor has 127.0.0.1:9050 ip:port, but proxychains4 has not any port which I can use as a proxy. Has any ideas to solve this issue?
How can I run proxychains4 on any port like tor service?)

**Comment by rofl0r** [comment]
> proxychains4 has not any port which I can use as a proxy

that's because proxychains is a proxy client, not a proxy server. 
however it's possible to use proxychains in combination with a proxycserver: e.g. `proxychains4 microsocks` will run microsocks socks5 server and have all its connection going through proxychains.

**Comment by Hyper-glitch** [comment]
Thank you so much!! It works for me as I have expected ))
