### ISSUE TITLE
abnormal proxy action under Squid

### ISSUE THREAD

**Issue by 2605759123** [rofl0r/proxychains-ng#448]
Thank you for your works!
My machine controlled by my network provider using `Squid` and only allow some website access in white list. When I visit any other website, it shows:
<img width="947" alt="image" src="https://user-images.githubusercontent.com/43004851/166234322-ea611c7c-69d1-4c22-9186-7ca533bcd421.png">
The white list include at least:
```
archive.ubuntu.com
https://mirrors.tuna.tsinghua.edu.cn/help/pypi/
```
```
$ curl archive.ubuntu.com
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
 <head>
  <title>Index of /</title>
 </head>
 <body>
<h1>Index of /</h1>
  <table>
   <tr><th valign="top"><img src="/icons/blank.gif" alt="[ICO]"></th><th><a href="?C=N;O=D">Name</a></th><th><a href="?C=M;O=A">Last modified</a></th><th><a href="?C=S;O=A">Size</a></th></tr>
   <tr><th colspan="4"><hr></th></tr>
<tr><td valign="top"><img src="/icons/folder.gif" alt="[DIR]"></td><td><a href="ubuntu/">ubuntu/</a></td><td align="right">2022-05-02 12:24  </td><td align="right">  - </td></tr>
   <tr><th colspan="4"><hr></th></tr>
</table>
<address>Apache/2.4.29 (Ubuntu) Server at archive.ubuntu.com Port 80</address>
</body></html>
```
dns test:  
```
$ nslookup archive.ubuntu.com
;; connection timed out; no servers could be reached
$ nslookup archive.ubuntu.com 114.114.114.114
;; connection timed out; no servers could be reached
```
When I download file from `archive.ubuntu.com`, `netstat -anp` shows I is establishing connnection with `172.23.4.59:3928`:
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 10.42.12.130:55292      172.23.4.59:3928        ESTABLISHED xxxxxx
```
I don't fully understand the working principle of `Squid`, but it seems like to seize all traffic to `172.23.4.59:3928`, including DNS. 
Now, I want to use shadowsocks + proxychains4 to bypass this limit. The `shadowsocks` listen 1080 port and it seems to be Working:
```
$ curl --socks5 127.0.0.1:1080 1.1.1.1
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
```
However, it don't work when I use hostname rather than ip:
```
$ curl --socks5 127.0.0.1:1080 ipinfo.io
curl: (6) Could not resolve host: ipinfo.io
```
When I use proxychains4, it doesn't seem to work:
```
$ proxychains4 curl ipinfo.io
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/local/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.16-git-4-g04023d3
[proxychains] Strict chain  ...  127.0.0.1:1080  ...  172.23.4.59:3928  ...  OK
curl: (52) Empty reply from server
$ proxychains4 curl 1.1.1.1
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/local/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.16-git-4-g04023d3
[proxychains] Strict chain  ...  127.0.0.1:1080  ...  172.23.4.59:3928  ...  OK
curl: (52) Empty reply from server
```
According to the log, why `proxychains4` try to connect `172.23.4.59:3928`?
it should be:
```
[proxychains] Strict chain  ...  127.0.0.1:1080  ...  ipinfo.io:80  ...  OK
(I test in my other machine)
```

I based on the latest version for testing and my config file is:
> \# add proxy here ...
\# meanwile
\# defaults set to "tor"
\# socks4        127.0.0.1 9050
socks5  127.0.0.1       1080

**Comment by rofl0r** [comment]
> I based on the latest version for testing and my config file is:

that certainly is not your config file, as it would not work. you need at least a [proxylist] section header.

**Comment by 2605759123** [comment]
> > 我基于最新版本进行测试，我的配置文件是：
> 
> 那肯定不是您的配置文件，因为它不起作用。您至少需要一个 [proxylist] 部分标题。

 Sorry, I only show the where I modify.

**Comment by rofl0r** [comment]
then show the entire file, with lines starting with `#` removed

**Comment by 2605759123** [comment]
```
strict_chain

proxy_dns

remote_dns_subnet 224

tcp_read_time_out 15000
tcp_connect_time_out 8000

localnet 127.0.0.0/255.0.0.0

[ProxyList]
socks5  127.0.0.1       1080
```

**Comment by 2605759123** [comment]
it also don't work:
```
strict_chain

proxy_dns

remote_dns_subnet 224

tcp_read_time_out 15000
tcp_connect_time_out 8000

# localnet 127.0.0.0/255.0.0.0    <--- Comment

[ProxyList]
socks5  127.0.0.1       1080
```

**Comment by rofl0r** [comment]
do you have something in your /etc/hosts ?

**Comment by 2605759123** [comment]
> do you have something in your /etc/hosts ?

```
# Kubernetes-managed hosts file.
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
fe00::0 ip6-mcastprefix
fe00::1 ip6-allnodes
fe00::2 ip6-allrouters
10.42.12.130    xxxxxxxxxxxx
```

**Comment by rofl0r** [comment]
well, in that case i'm clueless as to where proxychains pulls `172.23.4.59:3928`.

according to your log
``$ proxychains4 curl 1.1.1.1
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/local/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.16-git-4-g04023d3
[proxychains] Strict chain  ...  127.0.0.1:1080  ...  172.23.4.59:3928  ...  OK
curl: (52) Empty reply from server`
```

the only possible explanation left is that curl is configured to use that proxy.
for example, it might be set as http_proxy environment variable

**Comment by 2605759123** [comment]
Wow! You are right. 
It works perfectly:
```
proxychains4 curl --noproxy "*" ipinfo.io
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/local/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.16-git-4-g04023d3
[proxychains] Strict chain  ...  127.0.0.1:1080  ...  ipinfo.io:80  ...  OK
```
I checked `$HTTP_PROXY` and `$HTTPS_PROXY` before, not `$http_proxy`.
Thank you for your explanation. 
Great Works!
