### ISSUE TITLE
Operation timed out when I use git

### ISSUE THREAD

**Issue by Rainsheep** [rofl0r/proxychains-ng#454]
when I set  
`git config --global http.proxy 'socks5://127.0.0.1:1089'`
git clone is success.

but
```
$ proxychains4 git clone https://github.com/Rainsheep/vue-mall.git
[proxychains] config file found: /usr/local/etc/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.16/lib/libproxychains4.dylib
[proxychains] DLL init: proxychains-ng 4.16
Cloning into 'vue-mall'...
fatal: unable to access 'https://github.com/Rainsheep/vue-mall.git/': LibreSSL SSL_read: error:02FFF03C:system library:func(4095):Operation timed out, errno 60

# rainsheep @ yuyang in ~/1 [1:57:52] C:128
$ proxychains4 curl www.github.com
[proxychains] config file found: /usr/local/etc/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.16/lib/libproxychains4.dylib
[proxychains] DLL init: proxychains-ng 4.16
[proxychains] Strict chain  ...  127.0.0.1:1089  ...  www.github.com:80  ...  OK
```

it's my config
```

strict_chain
proxy_dns 
remote_dns_subnet 224

tcp_read_time_out 15000
tcp_connect_time_out 8000

[ProxyList]
socks5 	127.0.0.1 1089


```

**Comment by rofl0r** [comment]
try latest master which has a fix for an issue that recently affected SSH

**Comment by Rainsheep** [comment]
I tried it, but still the same @rofl0r

**Comment by rofl0r** [comment]
did you try with higher timeouts ?

**Comment by Rainsheep** [comment]
My local proxy cannot receive requests when I use proxychains4 git clone @rofl0r

**Comment by rofl0r** [comment]
can you use wireshark to compare with git config proxy what happens differently ?

**Comment by Rainsheep** [comment]
I would not use wireshare, can you help me analyze it?
 http_proxy file: https://oss.rainsheep.cn/temp/http_proxy.pcapng (command: git clone https://github.com/Rainsheep/vue-mall.git)
 proxychains file: https://oss.rainsheep.cn/temp/proxychains.pcapng (command: proxychains4 git clone https://github.com/Rainsheep/vue-mall.git)
 
 192.168.50.41 is my local ip address.
 173.82.219.9 is my vpn ip address.
 
 I'm sure, it is not proxied when I use proxychains.   Thanks you
 @rofl0r

**Comment by rofl0r** [comment]
thanks for providing these, but you need to sniff on `lo` interface, to see communications with socks5 on localhost

**Comment by Rainsheep** [comment]
http_proxy : https://oss.rainsheep.cn/temp/new/http_proxy.pcapng
proxychains: https://oss.rainsheep.cn/temp/new/proxychains.pcapng

my v2ray port: 1089
test command: git clone https://github.com/Rainsheep/vue-mall.git

**Comment by rofl0r** [comment]
in proxychains.pcapng there is no single packet going to socks5, you can see using `tcp.srcport == 1089 || tcp.dstport == 1089` as filter

**Comment by rofl0r** [comment]
what distro is that, btw ? i see it's using libressl, which is not that common these days

**Comment by Rainsheep** [comment]
by the filters you provide
http_proxy: https://rainsheep.oss-cn-beijing.aliyuncs.com/temp/http_proxy_new.pcapng

when use proxychains4, wireshark is empty. @rofl0r

**Comment by Rainsheep** [comment]
about LibreSSL, i know nothing

**Comment by Rainsheep** [comment]
it successfully uses the proxy when I set `git config --global http.sslBackend "openssl"`.

**Comment by rofl0r** [comment]
> about LibreSSL, i know nothing

yes, but you do know which linux distro you're using, i hope

**Comment by Rainsheep** [comment]
Can you help me see it through the remote control. Or just close this issues, I can use git in some other way. My English is not good, which affects our communication efficiency. @rofl0r

**Comment by Rainsheep** [comment]
$ openssl version
LibreSSL 2.8.3

**Comment by Rainsheep** [comment]
I test this problem.
in centos,  it is successful to use `git clone`.
```
[root@yuyang ~]# openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017
```

but in mac.  Can't go through proxy
```
$ openssl version
LibreSSL 2.8.3
```

**Comment by rofl0r** [comment]
ah. i didn't realize you were using a mac. did you follow all the csrutil instructions to disable the system protection stuff ? also, you need to use a git from homebrew, or copied to a user directory, not the system provided one.

**Comment by Rainsheep** [comment]
I'm very sorry for not describing my system clearly.
when I use git from homebrew, it goes through the proxy successfully.
Thanks for your help, I didn't find in the readme that I can't use the git that comes with the system, I hope you can add it.

**Comment by Rainsheep** [comment]
`proxychains4 git clone https://github.com/Rainsheep/vue-mall.git` is successful.
but `proxychains4 git clone git@github.com:Rainsheep/vue-mall.git` is failed

**Comment by rofl0r** [comment]
> proxychains4 git clone git@github.com:Rainsheep/vue-mall.git is failed

need more detail

**Comment by Rainsheep** [comment]
# rainsheep @ yuyang in ~/1 [22:42:34]
$ proxychains4 git clone https://github.com/Rainsheep/vue-mall.git
[proxychains] config file found: /usr/local/etc/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.16/lib/libproxychains4.dylib
[proxychains] DLL init: proxychains-ng 4.16
正克隆到 'vue-mall'...
[proxychains] DLL init: proxychains-ng 4.16
[proxychains] DLL init: proxychains-ng 4.16
[proxychains] Strict chain  ...  127.0.0.1:1089  ...  github.com:443  ...  OK
remote: Enumerating objects: 235, done.
[proxychains] DLL init: proxychains-ng 4.16
remote: Counting objects: 100% (235/235), done.
remote: Compressing objects: 100% (171/171), done.
remote: Total 235 (delta 40), reused 229 (delta 40), pack-reused 0
接收对象中: 100% (235/235), 258.06 KiB | 390.00 KiB/s, 完成.
处理 delta 中: 100% (40/40), 完成.
[proxychains] DLL init: proxychains-ng 4.16

# rainsheep @ yuyang in ~/1 [22:42:55]
$ proxychains4 git clone git@github.com:Rainsheep/vue-mall.git
[proxychains] config file found: /usr/local/etc/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.16/lib/libproxychains4.dylib
[proxychains] DLL init: proxychains-ng 4.16
正克隆到 'vue-mall'...
[proxychains] DLL init: proxychains-ng 4.16


always waiting

**Comment by rofl0r** [comment]
`git@` protocol starts `ssh` program as an intermediary, so maybe you need to install that one also from homebrew. if that doesnt work either, try git master of proxychains-ng

**Comment by Rainsheep** [comment]
when I use ssh from system, ssl is LibreSSL 2.8.3.   proxychains4 git clone git@xxx failed. 
I use ssh from homebres, ssl is OpenSSL 1.1.1o. proxychains4 git clone git@xxx is successful.

proxychains4 may has bug in LibreSSL

**Comment by rofl0r** [comment]
> when I use ssh from system

it's more likely the apple system protection stuff prevents this from working.
