### ISSUE TITLE
dns_proxy not work with ssh

### ISSUE THREAD

**Issue by NA3** [rofl0r/proxychains-ng#458]
# select2: Bad file descriptor

![image](https://user-images.githubusercontent.com/3059879/176986876-d5bec63b-3cc7-4029-882a-efebf4b6f0e7.png)
![image](https://user-images.githubusercontent.com/3059879/176986885-3a3ce626-1869-499f-a779-11b07cb1bfb1.png)
![image](https://user-images.githubusercontent.com/3059879/176987015-0a526e2b-b266-4c8d-9ce3-c2fe0843d052.png)

**Comment by rofl0r** [comment]
this is fixed in master via 000000006265577643cdcdefbc94aef903ffaf5e
