### ISSUE TITLE
port 993

### ISSUE THREAD

**Issue by LeeeJoe** [rofl0r/proxychains-ng#459]
Hello
Cannot connect to imap.gmail.com:993
**Output:**
> [proxychains] Dynamic chain  ...  142.111.189.254:20000  ...  74.125.133.108:993 <--denied
[proxychains] Dynamic chain  ...  142.111.189.254:20000  ...  74.125.133.109:993 <--denied
[proxychains] Dynamic chain  ...  142.111.189.254:20000  ...  2a00:1450:400c:c0c::6d:993 <--denied
[proxychains] Dynamic chain  ...  142.111.189.254:20000  ...  2a00:1450:400c:c0c::6c:993 <--denied
[00:12:29.215061]: Error reading mail.
Connection refused

**proxychains.conf:**
> [ProxyList]
http 142.111.189.254 20000

Any ideas?

**Comment by rofl0r** [comment]
it says "denied", so either the proxy disallows connections to 993 (to prevent spammers from using it) or the target doesnt have that port open.
try another proxy, optimally one you control.

**Comment by LeeeJoe** [comment]
Thank you. 
I had such a thought. 
After your message, I requested the provider. 
You were absolutely right. 
Good luck.
