### ISSUE TITLE
Versioning libproxychains4 so file

### ISSUE THREAD

**Issue by pranavk** [rofl0r/proxychains-ng#46]
It would be great if we could version the so file. Currently proxychains-ng provide only unversioned so file which usually goes in -dev, -devel packages when one packages it downstream. Versioning the so file would solve such problems.

**Comment by rofl0r** [comment]
proxychains needs no dev package as it does not provide any headers or libraries that are usable for development. the .so file is used solely by the preloader.

**Comment by mschwendt** [comment]
https://bugzilla.redhat.com/1147013#c37
