### ISSUE TITLE
quiet_mode cannot disable all output

### ISSUE THREAD

**Issue by Freed-Wu** [rofl0r/proxychains-ng#460]
1. Uncomment `quiet_mode` in /etc/proxychains.conf
2. `proxychains XXX`

output:
```
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
...
```

However, if use `proxychains -q XXX`, nothing be outputed. Why quiet_mode is different from `-q`? Is it a bug? Why in quiet_mode, there also has output?

Thanks.

**Comment by rofl0r** [comment]
> [proxychains] config file found: /etc/proxychains.conf
> [proxychains] preloading /usr/lib/libproxychains4.so

these 2 messages come both from the main proxychains4 application, not from the shared library. so they are printed before the config file is parsed.
proxychains-ng can be used in 2 ways:

- launched via proxychains4 executable, in which case -q needs to be used
- directly injected into processes via export LD_PRELOAD=/lib/libproxychains4.so - in this case quiet_mode works as you expect.

**Comment by Freed-Wu** [comment]
So, the problem is unable to be fixed because the binary program proxychains4 must output information before libproxychains4 is loaded? Thanks.

**Comment by Yegorov** [comment]
You can add alias to `~/.bash_profile`
```
alias pp='proxychains4 -q'
```
