### ISSUE TITLE
Any user-specific proxychains.conf?

### ISSUE THREAD

**Issue by Freed-Wu** [rofl0r/proxychains-ng#461]
Like `${XDG_CONFIG:-$HOME/.config}/proxychains/proxychains.conf` for linux?

Thanks.

**Comment by rofl0r** [comment]
proxychains-ng already supports $HOME/.proxychains/proxychains.conf. see src/common.c

XDG stuff is not supported, but you can write your own proxychains launcher that does it, just write a shell script that exports the 3 or so environment variables src/main.c sets (grep for setenv in that file). or add a line to the pathsearch routine in common.c directly.
