### ISSUE TITLE
I got five messages "DLL init: proxychains-ng 4.16" and "skypeforlinux" does not open!

### ISSUE THREAD

**Issue by hamedsbt** [rofl0r/proxychains-ng#469]
I'm trying to use skypeforlinux with proxy because it doesn't support proxy natively.
```
#proxychains skypeforlinux 
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.16
[proxychains] DLL init: proxychains-ng 4.16
[proxychains] DLL init: proxychains-ng 4.16
[proxychains] DLL init: proxychains-ng 4.16
[proxychains] DLL init: proxychains-ng 4.16
```

config:
```
# proxychains.conf  VER 4.x
strict_chain
proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000
[ProxyList]
socks5 	 	127.0.0.1 1080
```

OS: ArchLinux

**Comment by rofl0r** [comment]
the `#` prompt suggests you run as root, is that the case ?

**Comment by hamedsbt** [comment]
I tried both (root and normal user) and same results.

**Comment by rofl0r** [comment]
this might be related to #468 - these days proprietary apps are often shipped in some sort of containerized image, like a "snap", and i seem to recall that skype binary used to be statically linked in the past. regarding the root question, some distros have security restrictions, such as involving dynlinker hooks, for applications started as root and/or suid-root.
