### ISSUE TITLE
localnet in proxychains.conf seems to cause error

### ISSUE THREAD

**Issue by stupGit133** [rofl0r/proxychains-ng#47]
When I add to /etc/proxychains.conf:
```
localnet 127.0.0.0/255.0.0.0
```
or any localnet setting so I can communicate to my localhost, and I try to run proxchains4 I get an error.

```
root:~# proxychains4 nmap
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
error: invalid item in proxylist section: localnet 127.0.0.0/255.0.0.0
root:~# proxychains nmap
ProxyChains-3.1 (http://proxychains.sf.net)
Nmap 6.47 ( http://nmap.org )
Usage: nmap [Scan Type(s)] [Options]
```

The "proxychains4" command causes an error but "proxychains" doesn't.

Removing the localnet from my conf file causes it to work fine:
```
root:~# proxychains4 nmap
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.8.1
Nmap 6.47 ( http://nmap.org )
Usage: nmap [Scan Type(s)] [Options] 
```

**Comment by rofl0r** [comment]
see the error message:

```error: invalid item in proxylist section: localnet 127.0.0.0/255.0.0.0```

you put the localnet stuff in the wrong place
it needs to be on the top of your config
