### ISSUE TITLE
proxychains-ng with wsl problem

### ISSUE THREAD

**Issue by sandori01** [rofl0r/proxychains-ng#473]
Hi,
I have a socks5 proxy set up to an environment. This setup works fine for programs supporting socks5. Now I need to access an application (kafka) on that environment for which I do not have a client supporting connections over socks proxies. 
I installed proxychains4 in ubuntu on one of my machines, configured proxychains as to use 127.0.0.1:1099 as socks5 proxy. This works like a charm.
However when I did the same on my windows machine in WSL, it fails. 
The configuration, socks setup and the client application is the same. When I start up like
`# proxychains4 offsetexplorer`

I get:
[proxychains] Strict chain  ...  127.0.0.1:1099  ...  127.0.0.1:6000 <--socket error or timeout!
There is no config for the 127.0.0.1:6000 proxy, I don't know where proxychain gets the idea that there would be a second hop.
I removed the socks5 line from /etc/proxychains4.conf as an experiment, but then it correctly states:
error: no valid proxy found in config

WSL has Ubuntu 18.04 installed (the desktop linux is Ubuntu 20.04)
I have proxychains4 4.12-1 installed in WSL and 4.14-1 in the desktop Ubuntu. (Both installation are from the official repositories, I didn't add any 3rd party repos).
What could be the problem here?

**Comment by sandori01** [comment]
Weird. When I fire up offsetexplorer it does not try to connect anywhere. I would need to connect to a kafka service  to initiate any connection. 
On plain ubuntu it logs
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] Strict chain  ...  127.0.0.1:1099  ...  mykafkabrokers:9091  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:1099  ...  mykafkabrokers:9092  ...  OK
And the connection message about mykafkabrokers only appears after I press connect in the application.
In WSL I do not even get to the application, it exits before I would get the gui. (Or not started at all).
Imre

**Comment by rofl0r** [comment]
well, WSL isn't a supported target. if it works, that's great, but it's quite unlikely. from what i know m$ engineers were kinda sloppy when implementing the linux syscalls and there's lots of stuff that doesn't behave as it should (that's why they need a specially adapted linux distro to begin with - otherwise any distro would work out of the box).
your best bet on WSL is to use the proxydns_daemon method documented in the config file, or turn proxy_dns off completely, as the default method does some threading tricks that are likely to cause hickups.

**Comment by sandori01** [comment]
Thanks. I'll try that.

**Comment by sandori01** [comment]
I think I know what the problem could be. I was looking into the possibility to migrate from WSL to WSL2 and found that in order to make X11 work on WSL2, I need to enable port 6000 in the windows firewall. As this is the exact port that proxychains was complaining about, I think the problem could be, that offsetexplorer tries to display its window, it does try to open a connection toward the X11 server on port 6000. As the xserver runs on Windows, not on Ubunto (in WSL) this should be enabled as a direct connection in the proxychains config. 
Uncommenting 
localnet 127.0.0.0/255.0.0.0 solved the problem. 
(I was under the impression that this was a default setting but apperantly not)

Thanks anyway for the help.
Imre
