### ISSUE TITLE
1 warning generated.

### ISSUE THREAD

**Issue by chillbytess** [rofl0r/proxychains-ng#477]
~ ./configure

checking whether C compiler works ... yes
checking whether C compiler understands -Wno-unknown-pragmas ... yes
checking whether getnameinfo() servlen argument is POSIX compliant (socklen_t) ... yes
checking whether we have GNU-style getservbyname_r() ... no
checking whether we have pipe2() and O_CLOEXEC ... no
checking whether we have SOCK_CLOEXEC ... no
checking whether we have clock_gettime ... yes
checking whether $CC defines __APPLE__ ... yes
checking whether $CC defines __x86_64__ ... no
checking whether $CC defines __FreeBSD__ ... no
checking whether $CC defines __OpenBSD__ ... no
checking whether $CC defines __sun ... no
checking whether $CC defines __HAIKU__ ... no
checking whether we can use -Wl,--no-as-needed ... no
checking what's the option to use in linker to set library name ... -install_name
checking checking whether we can use -ldl ... yes
checking checking whether we can use -lpthread ... yes
using Monterey style DYLD hooking
Done, now run make && make install

~ make && make install

1 warning generated.
cc src/daemon/hsearch.o src/daemon/sblist.o src/daemon/sblist_delete.o src/daemon/daemon.o src/daemon/udpserver.o   -o proxychains4-daemon
./tools/install.sh -D -m 644 libproxychains4.dylib /usr/local/lib/libproxychains4.dylib
./tools/install.sh: line 53: /usr/local/lib/libproxychains4

I've tried to research the errors but I haven't had any luck. 
trying this on m2

**Comment by rofl0r** [comment]
i don't see any errors. it seems your log lacks various lines. the warning line is not of interest.

**Comment by chillbytess** [comment]
thanks for getting back with me. sorry I didn't post the full  message

make: Nothing to be done for `all'.
./tools/install.sh -D -m 644 libproxychains4.dylib /usr/local/lib/libproxychains4.dylib
./tools/install.sh: line 53: /usr/local/lib/libproxychains4.dylib.tmp.1605: Permission denied
make: *** [/usr/local/lib/libproxychains4.dylib] Error 1

once installed all I do is edit the config file right?
 I don't understand the permissions denied.

**Comment by chillbytess** [comment]
thanks for getting back with me. sorry I didn't post the full message.

this is the last warning I get. it seems somewhere in the the install.sh
script permissions were denied?

make: Nothing to be done for `all'.
./tools/install.sh -D -m 644 libproxychains4.dylib
/usr/local/lib/libproxychains4.dylib
./tools/install.sh: line 53: /usr/local/lib/libproxychains4.dylib.tmp.1605:
Permission denied
make: *** [/usr/local/lib/libproxychains4.dylib] Error 1

once installed all I do is edit the config file right?

**Comment by chillbytess** [comment]
thanks for getting back with me. sorry I didn't post the full message.

this is the last warning I get. it seems somewhere in the the install.sh script permissions were denied?

make: Nothing to be done for `all'.
./tools/install.sh -D -m 644 libproxychains4.dylib /usr/local/lib/libproxychains4.dylib
./tools/install.sh: line 53: /usr/local/lib/libproxychains4.dylib.tmp.1605: Permission denied
make: *** [/usr/local/lib/libproxychains4.dylib] Error 1

once installed all I do is edit the config file right?

**Comment by rofl0r** [comment]
maybe u need to use sudo for `make install` step to get proper permissions

**Comment by chillbytess** [comment]
how silly of me that worked!

**Comment by chillbytess** [comment]
ty 4 your time!

**Comment by chillbytess** [comment]
hey whenever I try launching proxychains it never exe. the proxies 
I only  get this message 

~ ❯ proxychains4 open http://www.dnsleaktest.com
[proxychains] config file found: /usr/local/etc/proxychains.conf
[proxychains] preloading /usr/local/lib/libproxychains4.dylib

it dosent change my IP at all.
or show what type of chain or a DLL int
what I am I doing wrong?
