### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by rmb122** [rofl0r/proxychains-ng#479]
I think https://github.com/rofl0r/proxychains-ng/commit/000000006265577643cdcdefbc94aef903ffaf5e is an important commit that fixes bug https://github.com/rofl0r/proxychains-ng/issues/439. Could you make a release so that distros (e.g. archlinux, ubuntu) can upgrade their package?

Archlinux's proxychains is still in [version 4.16](https://archlinux.org/packages/community/x86_64/proxychains-ng/) and not usable with ssh or git.

**Comment by rmb122** [comment]
I have use proxychains-ng at commit hash 060801d8c8613692469c8d1ccfc2598fb8a2992a for about three months. It works totally fine in arch and fixed the issue, but I have not tested it in CentOS, maybe you can make a release after it's confirmed fixed in CentOS.

**Comment by crab2313** [comment]
We need a release to fix #439.

**Comment by keenwon** [comment]
need a release.

**Comment by rofl0r** [comment]
https://github.com/rofl0r/proxychains-ng/releases/tag/v4.17
