### ISSUE TITLE
proxychains can't load process....: Permission denied

### ISSUE THREAD

**Issue by nodje** [rofl0r/proxychains-ng#49]
I'm trying to run an .app file with proxychain4 and I seem to be out of luck:
```
sudo proxychains4 /Applications/BBC\ iPlayer\ Downloads.app
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading ./libproxychains4.dylib
proxychains can't load process....: Permission denied
```
I can't think of any reason why there could be a permission problem. What could cause this?

**Comment by vikerian** [comment]
check X(execute) permissions on .app and on binary :)
Viker

**Comment by nodje** [comment]
permissions are all x on .app and binary, but I tried to run the binary directly and got
```
sudo proxychains4 /Applications/BBC\ iPlayer\ Downloads.app/Contents/MacOS/BBC\ iPlayer\ Downloads 
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.dylib
dyld: could not load inserted library '/usr/lib/libproxychains4.dylib' because no suitable image found.  Did find:
	/usr/lib/libproxychains4.dylib: mach-o, but wrong architecture
```
This app is using Adobe AIR behind the scene, I guess it would be the culprit. I compiled for my platform so I guess the lib is 64bit. Can I compile for both 32b & 64b arch and would it solve this issue?

**Comment by rofl0r** [comment]
@nodje yes you can compile for both archs
```make clean ; ./configure --fat-binary ; make```
possible that it solves your problem

**Comment by nodje** [comment]
eheh :)
just great, don't have to mess up with transparent proxying
