### ISSUE TITLE
Error: unknown type name ‘GN_NODELEN_T’         IN ARCH LINUX

### ISSUE THREAD

**Issue by codroc** [rofl0r/proxychains-ng#492]
**My system env:**
6.2.2-arch1-1, x86_64, GNU/Linux

**when i run "sudo make clean install", i met this problem:**
src/core.h:113:31: error: unknown type name ‘GN_NODELEN_T’
  113 |                               GN_NODELEN_T, char *, GN_SERVLEN_T, GN_FLAGS_T);
      |                               ^~~~~~~~~~~~
src/core.h:113:53: error: unknown type name ‘GN_SERVLEN_T’
  113 |                               GN_NODELEN_T, char *, GN_SERVLEN_T, GN_FLAGS_T);
      |                                                     ^~~~~~~~~~~~
src/core.h:113:67: error: unknown type name ‘GN_FLAGS_T’
  113 |                               GN_NODELEN_T, char *, GN_SERVLEN_T, GN_FLAGS_T);
      |                                                                   ^~~~~~~~~~
src/core.h:124:8: error: unknown type name ‘getnameinfo_t’
  124 | extern getnameinfo_t true_getnameinfo;
      |        ^~~~~~~~~~~~

**My Solution:**
vim src/core.h
go to line 113, add three lines:
```
typedef socklen_t GN_NODELEN_T;
typedef socklen_t GN_SERVLEN_T ;
typedef int GN_FLAGS_T;
```

**Comment by rofl0r** [comment]
the real solution is to run ./configure before make, as documented in the README.
