### ISSUE TITLE
Core dumped when querying non-existent host name with `proxy_dns_old`

### ISSUE THREAD

**Issue by jeff-an** [rofl0r/proxychains-ng#493]
When running proxychains on a NodeJS program that queries a non-existent DNS name, I get the following error:
```
|DNS-request| analytics
|DNS-response|: analytics does not exist
err_dns: Invalid argument
../deps/uv/src/unix/getaddrinfo.c:90: uv__getaddrinfo_translate_error: Assertion `!"unknown EAI_* error code"' failed.
Aborted (core dumped)
```
This crashes the program entirely (the expected behavior is just to accept that there is no host name and continue).

I've tested this on proxychains 4.15 and 4.16 with the same result. I compiled on a ubuntu buster docker image with `build-essential` installed. `./configure && make && make install` completely successfully and I can run `proxychains4 curl google.com` successfully.

BTW, i'm using `query_dns_old` because I need to add the `+search` option to `dig` in order to resolve some domain names in my Kubernetes environment. The `query_dns` option does not seem to have this capability or respect the configuration in `/etc/resolv.conf`.

The issue seems very similar to github.com/rofl0r/proxychains-ng/issues/343. Any help would be appreciated!

**Comment by jeff-an** [comment]
I was able to reproduce minimally with the `ubuntu:18.04` docker image, node version `v14.10.0`, and the `node-fetch@2` module for making the actual HTTP request.

**Comment by rofl0r** [comment]
please try whether current master fixes it, if not, paste output from a debug build (`CFLAGS=-DDEBUG ./configure`)

**Comment by jeff-an** [comment]
`master` works, thanks for the fast fix!
