### ISSUE TITLE
Provide HTTP or SOCKs interface as an alternative to executing a command

### ISSUE THREAD

**Issue by r3a1d3a1** [rofl0r/proxychains-ng#494]
Hello!

It'd be great to be able to use this as a proxy _itself_ for apps like Firefox that allow specifying proxies within them, but not in a chained fashion.
So another argument for the type and port of the proxy would need to be specified instead of a command to run.

Thanks!

**Comment by rofl0r** [comment]
if i understand correctly what you want, you can just combine this program with a proxy server program, for example microsocks or tinyproxy, e.g. `proxychains4 microsocks` and connect with firefox to the socks5 service provided by microsocks.

**Comment by rofl0r** [comment]
well, any project written in a language interfacing with the C standard library, such as C, C++, etc is compatible with proxychains-ng, as long as it's dynamically linked and not containerized.

**Comment by rofl0r** [comment]
since it is written in C++, yes.
