### ISSUE TITLE
proxychains4 does not work with stunnel! 

### ISSUE THREAD

**Issue by qaiwiz** [rofl0r/proxychains-ng#495]
when I run stunnel.conf and then port forward using ssh -D 1080 on my macos Monterey (this issue was present in older OS), I can explore internet and whatnot but on the terminal proxychains returns "socket error or timeout". However, when I kill stunnel, and directly port forward using the same ssh -D 1080, proxychains4 works perfectly fine. I am guessing since data is forwarded to another port (8888 in my case) I have to somehow specify this in the chain. Here is my server and my client stunnel.conf:

server stunnel.conf:
client = no
[squid]
accept = 8888
connect = 127.0.0.1:3128
cert = /etc/stunnel/stunnel.pem

client stunnel.conf
sslVersion = all
debug = 7
[squid]
client = yes
options = NO_SSLv2
options = DONT_INSERT_EMPTY_FRAGMENTS

cert = /usr/local/etc/stunnel/stunnel.pem
accept = 127.0.0.1:1080
connect = xx.xx.xx.xx:8888

**Comment by rofl0r** [comment]
please clarify what you're trying to do. ssh -D provides a socks server, and stunnel a TLS wrapper for some port, whereas squid provides a http proxy. in case you want to go proxychains -> stunnel -> squid: proxychains does not support https proxies.

**Comment by qaiwiz** [comment]
I want to use secured socks5 proxy, and be able to send the traffic from kernel and web browsers to this socks port.  Should I use other services than squid? I used squid for caching.

**Comment by rofl0r** [comment]
i'm not aware of any programs supporting socks5 behind TLS, so i guess what you want to do is currently impossible.

**Comment by qaiwiz** [comment]
Uh i see. That means, if I use stunnel even [ssh-tls] configuration, I would not be able to somehow use proxychains or anything similar. I tried to use tun2socks to socksify all my traffic, yet it has a UDP problem. My ISP throttle any other *inorganic* traffic, so the best I can do is to stay close to organic ssh traffic, yet I want to add an extra layer of encryption. Maybe I can do openvpn over ssh (so far, it has been unsuccessful).

**Comment by qaiwiz** [comment]
May I ask you this question. Now that all https are using tls, and almost all apps (like whatsapp,etc) are encrypted why I need additional layer of tls on my socks5? I already have it working, but I can not find it very useful.

**Comment by rofl0r** [comment]
exactly - most apps are already sending encrypted traffic, so there's rarely a need for additional encryption at the socks level.
i personally would find it helpful if there was one, because to someone sniffing the traffic it's visible in clear where connections are being forwarded, but the socks protocol was devised decades ago when privacy concerns weren't really an issue.
the solution would be to devise a new proxying protocol with lightweight encryption built in and trying to get it adopted in all major networking apps, but this is a herculean effort.
also TLS is way too complex and unsuited for such a protocol.

**Comment by qaiwiz** [comment]
Thanks for taking your time explaining this to me, as it is very hard to find details from stackexchange, etc. You mentioned, "i personally would find it helpful if there was one, because to someone sniffing the traffic it's visible in clear where connections are being forwarded". Would you mind elaborating how tls will cover this? I thought socks with or without tls is sending to specific IP and port, so there is no way to obfuscate IP. Does for example, stunnel with [ssh-tls] hide my destination or local IP? I am not sure what information is visible to outside when I browsing web or secured app (like whatsapp or telegram) using socks with and without TLS layer. As I understood Tor hide IPs by making a chain (I assume two connected server would be enough), but I could be wrong.

**Comment by rofl0r** [comment]
> I thought socks with or without tls is sending to specific IP and port, so there is no way to obfuscate IP.

socks protocol sends target ip in clear, and if that step is encrypted, an eavesdropper can no longer conclude with certainty what the target is. of course if the machine in question is fully surveilled and traffic to it low, this information could be gathered via timestamps of incoming and outgoing connections, but if there are many connections to and from the proxy machine, it gets harder to make this correlation.

**Comment by qaiwiz** [comment]
aaahh I see. Thanks. Can I use wireshark (or simpler tools) to see the difference between the two? The reason I am asking is that my ISP detect tls and drop the connection but https works fine. I assume ISP can drop connection IF the ip is not clear.

**Comment by rofl0r** [comment]
> Can I use wireshark (or simpler tools) to see the difference between the two?

you can use it to see and analyze socks5 packets but since there's no "encrypted socks" you have no way of comparing. from an ISP POV raw TLS (provided by stunnel to tlsify whatever service) and https should be undistinguishable afaict, so maybe they just block based on port number. TLS + 443 = fine, TLS + everything else = blocked ?

**Comment by qaiwiz** [comment]
Well, I am running tls on port 443 to cover that. However, somehow my connection is throttled. Here my server stunnel:

server.conf
output = /var/run/stunnel4/stunnel.log
pid = /var/run/stunnel4.pid
debug=7
client = no
[ssh-tls]
accept = 443
connect = 127.0.0.1:22
;connect=127.0.0.1:443
cert = /etc/stunnel/stunnel.pem
(I have checked both 443 or 22). 

client.conf
debug = 7
output=/usr/local/etc/stunnel/stunnel.log
[ssh-tls]
client = yes

sslVersion = all
options = DONT_INSERT_EMPTY_FRAGMENTS

accept = 127.0.0.1:8080
connect = xx.xx.xx.xx:443

I have tried to use [quic-proxy] which also runs on 443 but have not been successful yet.

**Comment by rofl0r** [comment]
sorry, can't help you with this. i guess you'll have to do some research about how your ISP identifies that sort of traffic and then circumvent it appropiately. i'm closing this now as i suppose the original question has been answered.

**Comment by qaiwiz** [comment]
Thanks. Sure.
