### ISSUE TITLE
Config path specified but still get "couldnt find configuration file: No such file or directory

### ISSUE THREAD

**Issue by francestu96** [rofl0r/proxychains-ng#501]
![image](https://user-images.githubusercontent.com/32491001/230045514-42a2a357-971d-488b-808a-88cfe0ee3bf4.png)

As you can see from the output of my binary, the first time I run it, proxychains get the config file, however, after few input of mine, it doesn't find it anymore.

Could it be because the binary I wanna run creates some threads or processes?

In case how can I workaround this issue? I hano no root permission on the machine, so I cannot write on /etc. 
Is there a way to change the default file config location instead of /etc/proxychains.config?

Thank you

**Comment by rofl0r** [comment]
seems something changes directory. just use an absolute path.

**Comment by francestu96** [comment]
Holy **** are you a bot? 
You solved the problem in 1 minute thank you so much
