### ISSUE TITLE
Does it support pure TCP packets?

### ISSUE THREAD

**Issue by oilel** [rofl0r/proxychains-ng#502]
If a program only sends pure TCP packets, can it proxy the packets?

**Comment by rofl0r** [comment]
if by pure you mean raw, then no. if it uses libc connect(), then yes.

**Comment by oilel** [comment]
> if by pure you mean raw, then no

But the file ```/etc/proxychains.conf``` contains the sentence "raw: The traffic is simply forwarded to the proxy without modification."

**Comment by rofl0r** [comment]
i was talking about raw packets (creating those requires root permission), not "raw proxy type".
