### ISSUE TITLE
mac Couldn't connect to server

### ISSUE THREAD

**Issue by ppuuoo** [rofl0r/proxychains-ng#513]
<img width="572" alt="image" src="https://github.com/rofl0r/proxychains-ng/assets/28812583/d5028bd5-2a1c-4b14-8059-8fd3f32b795f">

**Comment by rofl0r** [comment]
read pinned issue about how to get mac os to behave. you also need to use binaries that are not in system default path. for example you can copy curl binary to $HOME, and use it from there.
