### ISSUE TITLE
Reverse SSH tunnel through proxy with proxychains-ng not working?

### ISSUE THREAD

**Issue by ylluminate** [rofl0r/proxychains-ng#514]
I'm currently using `proxychains-ng` (on macOS Ventura via Homebrew) to establish a SSH connection to a remote server from an environment where direct connections are sometimes blocked.

My workflow involves using the `rsubl` command (part of `rmate`) on the remote server to edit files locally in Sublime Text. This involves setting up a reverse SSH tunnel from the remote server back to my local machine, where Sublime Text is listening. 

The command I use is:
```
proxychains4 ssh -R 12345:localhost:12345 -p 22222 root@remote.server.tld
```

When connected as per above and I use `rsubl`, it fails with a "Connection refused" error:
```
$ rsubl /home/username/public_html/.htaccess
[proxychains] Strict chain  ...  192.168.0.2:1080  ...  127.0.0.1:12345 <--socket error or timeout!
connect to localhost port 12345 failed: Connection refused
```

It appears that the reverse SSH tunnel is also being routed through the proxy. As the listening Sublime Text server isn't reachable through the proxy, the connection fails.

Ideally, I'd like the reverse tunnel to go through the proxy and still reach the Sublime Text server on my local machine. Is there a way to achieve this with `proxychains-ng`, or is there a workaround I'm missing?

Fwiw, my conf file users:
```
strict_chain
proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000
```

(Thank you for your awesome work with this project!)

**Comment by rofl0r** [comment]
maybe you need to activate the localnet directive so localhost access isnt routed through proxy

**Comment by ylluminate** [comment]
Thank you very much @rofl0r. That does seem to have done the trick. If you have time, could you please further elucidate why that works for this in context of the reverse tunnel?

**Comment by rofl0r** [comment]
there are 2 ways how local addresses can be treated, either it's being used for something on your side or on the proxies side (default config). as the reverse proxy opens a port on your side, it makes sense to not forward packets destined for localhost to the proxy.
