### ISSUE TITLE
can't download dependencies using bazel

### ISSUE THREAD

**Issue by a7853z** [rofl0r/proxychains-ng#518]
Using proxychains in bazel to download dependencies, errors like **"connect time out"** or **"No subject alternative DNS name matching github.com found."** occured.  Here are the details:
- I am using following instructions to install secretflow: [https://github.com/secretflow/secretflow/blob/main/docs/getting_started/installation.md#option-3-from-source](url)

- In the above document, running

> python setup.py bdist_wheel

will run bazel: 

> bazel build //secretflow_lib/binding:_lib.so --symlink_prefix=build/temp.linux-x86_64-cpython-38/bazel- --compilation_mode=opt

 and it will download dependencies from github.

- My server can't connect to github, so I use proxychains to setup a proxy, this proxy (localnet ::1/128 added in conf) can telnet and wget github directly, No problem. 

`(secretflow) [randy@federated-develop secretflow]$ ./proxychains4 -f /usr/local/etc/proxychains.conf wget https://github.com/bazelbuild/rules_foreign_cc/archive/refs/tags/0.9.0.tar.gz

[proxychains] config file found: /usr/local/etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.16-git-15-g0c79508
--2023-09-06 11:32:07--  https://github.com/bazelbuild/rules_foreign_cc/archive/refs/tags/0.9.0.tar.gz
Resolving github.com (github.com)... 224.0.0.1
Connecting to github.com (github.com)|224.0.0.1|:443... [proxychains] Strict chain  ...  127.0.0.1:9060  ...  github.com:443  ...  OK
connected.

./proxychains4 -f /usr/local/etc/proxychains.conf telnet github.com 80
[proxychains] config file found: /usr/local/etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.16-git-15-g0c79508
Trying 224.0.0.1...
[proxychains] Strict chain  ...  127.0.0.1:9060  ...  github.com:80  ...  OK
Connected to github.com.

`

- But if I use this proxy to run setup.py which will run bazel, errors occured:
> ./proxychains4 -f /usr/local/etc/proxychains.conf python setup.py bdist_wheel

errors like:

1. "ERROR: no such package '@rules_foreign_cc//foreign_cc': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_foreign_cc/archive/refs/tags/0.9.0.tar.gz] to /home/randy/.cache/bazel/_bazel_randy/083d6ac12f533e3f374ece45cc7df093/external/rules_foreign_cc/temp6777806408797802941/0.9.0.tar.gz: **connect timed out**"
2. "ERROR: no such package '@rules_foreign_cc//foreign_cc': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_foreign_cc/archive/refs/tags/0.9.0.tar.gz] to /home/randy/.cache/bazel/_bazel_randy/083d6ac12f533e3f374ece45cc7df093/external/rules_foreign_cc/temp8184421799046572597/0.9.0.tar.gz: **No subject alternative DNS name matching github.com found.**"

**Comment by rofl0r** [comment]
maybe try different proxy_dns method. bazel is written in java and java programs are known to work badly with proxychains or not at all.

**Comment by a7853z** [comment]
> maybe try different proxy_dns method. bazel is written in java and java programs are known to work badly with proxychains or not at all.

frustrated, tried all three proxy methods and no dns proxy, still not working.

**Comment by rofl0r** [comment]
yeah, it frustrated me too when google wrote and propagated a new build tool written in the proprietary java language, because it prevents me from using it (java needs to be bootstrapped from binaries and cant be built from source).

**Comment by a7853z** [comment]
> yeah, it frustrated me too when google wrote and propagated a new build tool written in the proprietary java language, because it prevents me from using it (java needs to be bootstrapped from binaries and cant be built from source).

Thank you, I setted up a new http proxy, problem is solved.
