### ISSUE TITLE
bash no, curl www.google.com yes

### ISSUE THREAD

**Issue by N0o01** [rofl0r/proxychains-ng#523]
➜  ~ proxychains4 bash
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /Applications/proxychains4/libproxychains4.dylib
dyld[95839]: terminating because inserted dylib '/Applications/Xc7ACD/Nscan/proxychains-ng/libproxychains4.dylib' could not be loaded: tried: '/Applications/proxychains4/libproxychains4.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/proxychains4/libproxychains4.dylib' (no such file), '/Applications/proxychains4/libproxychains4.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
dyld[95839]: tried: '/Applications/proxychains4/libproxychains4.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/proxychains4/libproxychains4.dylib' (no such file), '/Applications/proxychains4/libproxychains4.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
[1]    95839 abort      /Applications/proxychains4 bash

  ~ proxychains4 curl www.google.com
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /libproxychains4.dylib
[proxychains] DLL init: proxychains-ng 4.16
[proxychains] Strict chain  ...  127.0.0.1:1111  ...  www.google.com:80  ...  OK
<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="zh-HK"><head><meta content="text/html;

**Comment by N0o01** [comment]
CFLAGS="-arch x86_64 -arch=arm64e" LDFLAGS="-arch x86_64 -arch=arm64e" ./configure

make

**Comment by N0o01** [comment]
13-inch, M1,  macos:13.5

**Comment by rofl0r** [comment]
you need --fat-binary-m1 option for configure, also there's plenty of issues containing tricks and tips for M1 mac on this bugtracker. (go to issues, then search for M1 in both closed and open issues).

**Comment by rofl0r** [comment]
#481 has instructions which seem to work for most people.
