### ISSUE TITLE
m1 13.5 (22G74)

### ISSUE THREAD

**Issue by N0o01** [rofl0r/proxychains-ng#528]
➜  ~ proxychains4 Firefox.app
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/local/lib/libproxychains4.dylib
proxychains: can't load process 'Firefox.app'. (hint: it's probably a typo): No such file or directory

**Comment by rofl0r** [comment]
firefox.app isn't an executable, it's a directory. 
see https://stackoverflow.com/questions/1308755/how-to-launch-an-app-on-os-x-with-command-line-the-best-way
so you probably got to run `proxychains4 open Firefox.app` or similar.

**Comment by N0o01** [comment]
> firefox.app isn't an executable, it's a directory. see https://stackoverflow.com/questions/1308755/how-to-launch-an-app-on-os-x-with-command-line-the-best-way so you probably got to run `proxychains4 open Firefox.app` or similar.
nononononono
