### ISSUE TITLE
Not working on macos 14.1.1

### ISSUE THREAD

**Issue by sorosunrain** [rofl0r/proxychains-ng#533]
proxychains-ng not working on macos 14.1.1, but fine on 13.6.1

new device: macbook pro m3 max

----------------------

sr@srMacBook-Pro ~ % proxys ping google.com
[proxychains] config file found: /opt/homebrew/etc/proxychains.conf
[proxychains] preloading /opt/homebrew/Cellar/proxychains-ng/4.16/lib/libproxychains4.dylib
PING google.com (172.217.163.46): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5

**Comment by rofl0r** [comment]
proxychains never supported ICMP, that's why ping isnt working in any version.
