### ISSUE TITLE
frp+proxychaincant use any command

### ISSUE THREAD

**Issue by YNUzzq** [rofl0r/proxychains-ng#543]
frp use successful

fprs.ini
`[common]
bind_addr = 0.0.0.0
bind_port = 7000`

frpc.ini
`[common]
server_addr = 192.168.213.129
server_port = 7000
 
[http_proxy]
type = tcp
remote_port = 1080
plugin = socks5
local_ip = 192.168.213.1
local_port = 8000`

proxychains.conf
`socks4 	127.0.0.1 1080`

command
`┌──(kali㉿kali)-[~]
└─$ proxychains4 ping 192.168.97.167                 
[proxychains] config file found: /etc/proxychains4.conf
[proxychains] preloading /usr/lib/x86_64-linux-gnu/libproxychains.so.4
PING 192.168.97.167 (192.168.97.167) 56(84) bytes of data.

zsh: suspended  proxychains4 ping 192.168.97.167`

**Comment by YNUzzq** [comment]
┌──(kali㉿kali)-[~]
└─$ proxychains firefox 192.168.97.167:8082
[proxychains] config file found: /etc/proxychains4.conf
[proxychains] preloading /usr/lib/x86_64-linux-gnu/libproxychains.so.4
[proxychains] DLL init: proxychains-ng 4.16
[proxychains] DLL init: proxychains-ng 4.16
[proxychains] DLL init: proxychains-ng 4.16
[proxychains] DLL init: proxychains-ng 4.16
[proxychains] DLL init: proxychains-ng 4.16
[proxychains] DLL init: proxychains-ng 4.16
[proxychains] DLL init: proxychains-ng 4.16
[proxychains] DLL init: proxychains-ng 4.16
[proxychains] DLL init: proxychains-ng 4.16
[proxychains] DLL init: proxychains-ng 4.16
[proxychains] DLL init: proxychains-ng 4.16
[proxychains] DLL init: proxychains-ng 4.16
[proxychains] Strict chain  ...  0.0.0.0:1080  ...  44.239.61.189:443 <--socket error or timeout!
[proxychains] Strict chain  ...  0.0.0.0:1080  ...  52.24.234.54:443 <--socket error or timeout!
[proxychains] Strict chain  ...  0.0.0.0:1080  ...  44.241.184.110:443 <--socket error or timeout!
[proxychains] Strict chain  ...  0.0.0.0:1080  ...  34.117.237.239:443 <--socket error or timeout!
[proxychains] Strict chain  ...  0.0.0.0:1080  ...  192.168.97.167:8082 <--socket error or timeout!
[proxychains] Strict chain  ...  0.0.0.0:1080  ...  34.117.237.239:443 <--socket error or timeout!

i dont know why it go to 52.24.234.54

**Comment by rofl0r** [comment]
0.0.0.0 isn't a valid address to connect to, it's only valid as an address to bind to (it means "all interfaces").
change your proxy ip and i suppose it should work.
proxychains4 ping never works because ping uses ICMP and proxychains only supports TCP.
