### ISSUE TITLE
mac m2

### ISSUE THREAD

**Issue by BestToYou** [rofl0r/proxychains-ng#548]
dyld[9089]: terminating because inserted dylib '/usr/local/lib/libproxychains4.dylib' could not be loaded: tried: '/usr/local/lib/libproxychains4.dylib' (mach-o file, but is an incompatible architecture (have 'arm64e', need '')), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libproxychains4.dylib' (no such file), '/usr/local/lib/libproxychains4.dylib' (mach-o file, but is an incompatible architecture (have 'arm64e', need ''))

**Comment by rofl0r** [comment]
search for "incompatible architecture" in issues to find the solution, or look at the pinned issues.
