### ISSUE TITLE
what should I do if I encountered something like below? I'm working with MacOS m1 pro silicon.

### ISSUE THREAD

**Issue by Minet7** [rofl0r/proxychains-ng#557]
➜  proxychains-ng git:(master) ./configure --prefix=/usr --sysconfdir=/etc
checking whether C compiler works ... yes
checking whether libc headers are complete ... yes
checking whether C compiler understands -Wno-unknown-pragmas ... yes
checking whether getnameinfo() servlen argument is POSIX compliant (socklen_t) ... yes
checking whether we have GNU-style getservbyname_r() ... no
checking whether we have pipe2() and O_CLOEXEC ... no
checking whether we have SOCK_CLOEXEC ... no
checking whether we have clock_gettime ... yes
checking whether $CC defines __APPLE__ ... yes
checking whether $CC defines __x86_64__ ... no
checking whether $CC defines __FreeBSD__ ... no
checking whether $CC defines __OpenBSD__ ... no
checking whether $CC defines __sun ... no
checking whether $CC defines __HAIKU__ ... no
checking whether we can use -Wl,--no-as-needed ... no
checking what's the option to use in linker to set library name ... -install_name
checking checking whether we can use -ldl ... yes
checking checking whether we can use -lpthread ... yes
using Monterey style DYLD hooking
Done, now run make && make install
➜  proxychains-ng git:(master) make
printf '#define VERSION "%s"\n' "$(sh tools/version.sh)" > src/version.h
cc -DSUPER_SECURE -Wno-unknown-pragmas -DGN_NODELEN_T=socklen_t -DGN_SERVLEN_T=socklen_t -DGN_FLAGS_T=int -DHAVE_CLOCK_GETTIME -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -DMONTEREY_HOOKING  -DIS_MAC=1 -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/version.o src/version.c
cc -DSUPER_SECURE -Wno-unknown-pragmas -DGN_NODELEN_T=socklen_t -DGN_SERVLEN_T=socklen_t -DGN_FLAGS_T=int -DHAVE_CLOCK_GETTIME -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -DMONTEREY_HOOKING  -DIS_MAC=1 -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/core.o src/core.c
cc -DSUPER_SECURE -Wno-unknown-pragmas -DGN_NODELEN_T=socklen_t -DGN_SERVLEN_T=socklen_t -DGN_FLAGS_T=int -DHAVE_CLOCK_GETTIME -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -DMONTEREY_HOOKING  -DIS_MAC=1 -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/common.o src/common.c
cc -DSUPER_SECURE -Wno-unknown-pragmas -DGN_NODELEN_T=socklen_t -DGN_SERVLEN_T=socklen_t -DGN_FLAGS_T=int -DHAVE_CLOCK_GETTIME -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -DMONTEREY_HOOKING  -DIS_MAC=1 -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/libproxychains.o src/libproxychains.c
src/libproxychains.c:919:2: error: incompatible function pointer types assigning to 'freeaddrinfo_t' (aka 'int (*)(struct addrinfo *)') from 'void (*)(struct addrinfo *)' [-Wincompatible-function-pointer-types]
        SETUP_SYM(freeaddrinfo);
        ^~~~~~~~~~~~~~~~~~~~~~~
src/libproxychains.c:906:57: note: expanded from macro 'SETUP_SYM'
#define SETUP_SYM(X) do { if (! true_ ## X ) true_ ## X = &X; } while(0)
                                                        ^ ~~
1 error generated.
make: *** [src/libproxychains.o] Error 1
➜  proxychains-ng git:(master)

**Comment by rofl0r** [comment]
can you confirm this to be fixed in current master ? (use git pull, then run make again)
