### ISSUE TITLE
How to let an application that started or enabled by "systemctl " use proxychains-ng on Linux?

### ISSUE THREAD

**Issue by zwl1619** [rofl0r/proxychains-ng#568]
How to let an application that started or enabled by "systemctl " use proxychains-ng on Linux?
For example, I installed sing-box, manage it with the commands below:
```
sudo systemctl enable sing-box
sudo systemctl disable sing-box
sudo systemctl start sing-box
sudo systemctl stop sing-box
sudo systemctl kill sing-box
sudo systemctl restart sing-box
```
How to launch sing-box via proxychains-ng?

**Comment by rofl0r** [comment]
you edit the service script so instead of executing "/bin/singbox" it executes "/bin/proxychains4 -f /etc/proxychains-singbox.conf /bin/singbox". adjust paths as needed.
