### ISSUE TITLE
OpenBSD: proxychains crashes with 'Abort trap (core dumped)' error on launch

### ISSUE THREAD

**Issue by sysfu** [rofl0r/proxychains-ng#57]
Environment;
OpenBSD i386 5.7-release
pf disabled

```
/etc/proxychains.conf
---------------------------
strict_chain
proxy_dns 
tcp_read_time_out 15000
tcp_connect_time_out 8000
[ProxyList]
socks5 192.168.0.100 9050
```

Tried getting proxychains4 to run both znc and nc (netcat). Fails on both with error "Abort trap (core dumped) "

```
$ proxychains4 nc -vz yahoo.com 80                                                                                                                                      
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/local/lib/libproxychains4.so
Abort trap (core dumped) 
$ gdb -c nc.core                                                                                                                                                        
This GDB was configured as "i386-unknown-openbsd5.7".
Core was generated by `nc'.
Program terminated with signal 6, Aborted.
#0  0x0fbf2471 in ?? ()
```

Kernel trace using OpenBSD ktrace util:
https://cryptobin.org/02y0f065 (password is 'proxychains')

**Comment by rofl0r** [comment]
did it work earlier when we fixed the build?

**Comment by sysfu** [comment]
No, this is the first opportunity I've had to test it since you fixed the compilation problem.

**Comment by rofl0r** [comment]
unfortunately your backtrace is worthless without symbol names. see if you can provide a better backtrace with full debug info activated (proxychains is by default built with debug info so i'm unclear why yours is missing)

**Comment by sysfu** [comment]
I'm having a hard time finding information about how or where to load the symbol names for OpenBSD. If you have any suggestions please let me know.

**Comment by rofl0r** [comment]
this seems to be due to a bug in openbsd's dynlinker.
seems we need to wait for a openbsd crack who knows how to get libc + dynlinker with debug symbols to track down the issue (due to lack of a pre-installed openbsd developer image for usage in qemu i went through the installer process, which left me with a semi-unusable system with a 1970's userland - no git, no wget, no curl, etc which took me about 2 hrs of investigation, manual download of tools just to reproduce the issue, but nowhere near getting a proper backtrace)

**Comment by rofl0r** [comment]
try if modifying Makefile to
```diff
 $(LDSO_PATHNAME): $(LOBJS)
- $(CC) -shared -lpthread $(LIBDL) $(LDFLAGS) $(LD_SET_SONAME)$(LDSO_PATHNAME) -o $@ $(LOBJS)
+ $(CC) $(CFLAGS) -lsocket -lnsl -shared -lpthread $(LIBDL) $(LDFLAGS) $(LD_SET_SONAME)$(LDSO_PATHNAME) -o $@ $(LOBJS)
```
fixes it

**Comment by rofl0r** [comment]
nope, those libraries are apparently not existing on OpenBSD

**Comment by sysfu** [comment]
Yes, fails to build with Makefile mod

```
/usr/bin/ld: cannot find -lsocket
collect2: ld returned 1 exit status
Makefile:85: recipe for target 'libproxychains4.so' failed
gmake: *** [libproxychains4.so] Error 1
```

**Comment by sysfu** [comment]
Also, if you need an OpenBSD 5.7 system to bang on, send me your pub SSH key and I'll reply with access info.

**Comment by anoduck** [comment]
@sysfu This issue needs to be closed out since OpenBSD does not even compile with ProxyChains-ng anymore AND the release 5.7 is outdated, new release is 6.7.
