### ISSUE TITLE
Firefox can’t establish a connection to the server at wss:// (<--socket error or timeout!) with proxychains-ng 4.17

### ISSUE THREAD

**Issue by bugshunter673** [rofl0r/proxychains-ng#576]
Hello I'm getting the following error while visiting [speedtest.net ](https://speedtest.net )and performing test
Trying to use different proxy servers (`ssh -D 1080`, etc) does not help.
Environment:</br>`Fedora Linux 40 under toolbox`
CMD: </br> `toolbox run proxychains  env MOZ_ENABLE_WAYLAND=1 /home/user/.local/firefox/firefox`
```
Firefox can’t establish a connection to the server at wss://redacted
```
```
[proxychains] DLL init: proxychains-ng 4.17
<--socket error or timeout!
[proxychains] Strict chain  ...  127.0.0.1:1080  ...  ip redacted <--socket error or timeout!
```

**Comment by rofl0r** [comment]
no idea what toolbox is, but proxychains supports only native, dynamically linked programs that are **not containerized**.

**Comment by bugshunter673** [comment]
> no idea what toolbox is, but proxychains supports only native, dynamically linked programs that are **not containerized**.

Even not containerized still does not work with `Firefox 129.0`

**Comment by rofl0r** [comment]
read #575 . it works for him. there are also workarounds mentioned.

**Comment by bugshunter673** [comment]
> read #575 . it works for him. there are also workarounds mentioned.

Yeah. Setting socks proxy settings in firefox to remote socks works fine on speedtest.  `firefox  --> [ proxychains --> ssh -D 1080] ---> address_of_remote_socks_set_in_firefox`
