### ISSUE TITLE
Is it still working on macOS version 14.4 ?

### ISSUE THREAD

**Issue by JackLau1222** [rofl0r/proxychains-ng#584]
I installed it with Brew, but I can't get it to work well.
there are two method i tried to use proxychains
1. modify `/opt/homebrew/etc/proxychains.conf` last line to `socks5  127.0.0.1 7890`
2. use `PROXYCHAINS_SOCKS5_HOST` and `PROXYCHAINS_SOCKS5_PORT` like `PROXYCHAINS_SOCKS5_HOST=127.0.0.1 PROXYCHAINS_SOCKS5_PORT=7890 proxychains4 ping google.com`

the program found `proxychains.conf`  and preload libproxychains4.dylib successfully
but there are no any chains
this is entire log:
```zsh
jacklau@Jacks-iMac Downloads %  PROXYCHAINS_SOCKS5_HOST=127.0.0.1 PROXYCHAINS_SOCKS5_PORT=7890 proxychains4 ping google.com
[proxychains] config file found: /opt/homebrew/etc/proxychains.conf
[proxychains] preloading /opt/homebrew/Cellar/proxychains-ng/4.17/lib/libproxychains4.dylib
PING google.com (59.24.3.174): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
```

**Comment by JackLau1222** [comment]
sry, i test this command in my another mac(always run proxychains successfully), proxychains seems not support ping command.
but this iMac still can't support git, i even use same conf with another mac
```
jacklau@Jacks-iMac Downloads % proxychains4 git clone https://github.com/BabitMF/bmf
[proxychains] config file found: /Users/jacklau/Downloads/proxychains.conf
[proxychains] preloading /opt/homebrew/Cellar/proxychains-ng/4.17/lib/libproxychains4.dylib
Cloning into 'bmf'...
^C

```
Normal situation maybe like that
```
> proxychains4 git clone  https://github.com/BabitMF/bmf
[proxychains] config file found: /opt/homebrew/etc/proxychains.conf
[proxychains] preloading /opt/homebrew/Cellar/proxychains-ng/4.17/lib/libproxychains4.dylib
[proxychains] DLL init: proxychains-ng 4.17
Cloning into 'bmf'...
[proxychains] DLL init: proxychains-ng 4.17
[proxychains] DLL init: proxychains-ng 4.17
[proxychains] Strict chain  ...  127.0.0.1:7890  ...  github.com:443  ...  OK
remote: Enumerating objects: 7628, done.
remote: Counting objects: 100% (1746/1746), done.
[proxychains] DLL init: proxychains-ng 4.17
remote: Compressing objects: 100% (609/609), done.
remote: Total 7628 (delta 1281), reused 1343 (delta 1124), pack-reused 5882 (from 1)
Receiving objects: 100% (7628/7628), 61.86 MiB | 16.51 MiB/s, done.
Resolving deltas: 100% (4614/4614), done.
[proxychains] DLL init: proxychains-ng 4.17
```
and i reinstall the proxychians using homebrew

**Comment by JackLau1222** [comment]
the telnet run normally
```zsh
jacklau@Jacks-iMac Downloads % proxychains4 telnet github.com                       
[proxychains] config file found: /Users/jacklau/Downloads/proxychains.conf
[proxychains] preloading /opt/homebrew/Cellar/proxychains-ng/4.17/lib/libproxychains4.dylib
[proxychains] DLL init: proxychains-ng 4.17
Trying 224.0.0.1...
[proxychains] Strict chain  ...  127.0.0.1:7890  ...  github.com:23  ...  OK
Connected to github.com.
Escape character is '^]'.
```

**Comment by JackLau1222** [comment]
> sry, i test this command in my another mac(always run proxychains successfully, OS version 14.1), proxychains seems not support ping command. but this iMac still can't support git, i even use same conf with another mac
> 
> ```
> jacklau@Jacks-iMac Downloads % proxychains4 git clone https://github.com/BabitMF/bmf
> [proxychains] config file found: /Users/jacklau/Downloads/proxychains.conf
> [proxychains] preloading /opt/homebrew/Cellar/proxychains-ng/4.17/lib/libproxychains4.dylib
> Cloning into 'bmf'...
> ^C
> ```
> 
> Normal situation maybe like that
> 
> ```
> > proxychains4 git clone  https://github.com/BabitMF/bmf
> [proxychains] config file found: /opt/homebrew/etc/proxychains.conf
> [proxychains] preloading /opt/homebrew/Cellar/proxychains-ng/4.17/lib/libproxychains4.dylib
> [proxychains] DLL init: proxychains-ng 4.17
> Cloning into 'bmf'...
> [proxychains] DLL init: proxychains-ng 4.17
> [proxychains] DLL init: proxychains-ng 4.17
> [proxychains] Strict chain  ...  127.0.0.1:7890  ...  github.com:443  ...  OK
> remote: Enumerating objects: 7628, done.
> remote: Counting objects: 100% (1746/1746), done.
> [proxychains] DLL init: proxychains-ng 4.17
> remote: Compressing objects: 100% (609/609), done.
> remote: Total 7628 (delta 1281), reused 1343 (delta 1124), pack-reused 5882 (from 1)
> Receiving objects: 100% (7628/7628), 61.86 MiB | 16.51 MiB/s, done.
> Resolving deltas: 100% (4614/4614), done.
> [proxychains] DLL init: proxychains-ng 4.17
> ```
> 
> and i reinstall the proxychians using homebrew

i found the reason, the apple git is not support proxy, the proxychains work after i installed git manually

**Comment by rofl0r** [comment]
line 7 of README:
>   It supports TCP only (no UDP/ICMP etc).
so ping will never work.

line 252 of README:
> - Mac OS X 10.11 (El Capitan) ships with a new security feature called SIP ...
>   or to copy the system binary into the home directory and run it from there.
>   see github issue #78 for details.
