### ISSUE TITLE
Possible to allow local server cons while using libproxychains.so.4/proxychains4?

### ISSUE THREAD

**Issue by 0XC7R** [rofl0r/proxychains-ng#585]
I am trying to connect to a local server like `127.0.0.1/192.168.x.x` however connections do not work. I cannot curl the server while connected. I am using `libproxychains.so.4` via the `/etc/profile` file. I will provide the full `/etc/profile` file below as well as my config.

I am running tor via tornet which is where all my tor traffic gets routed through. However I do not think this is the issue. I believe I could do something with the configuration. If not then I will just keep logging in and out of my kali user as that is a fix but a bit annoying if I am in the middle of doing a few things at once.

This allows it to run system wide for terminal usage. Using root terminals allows connections however using any other program etc does not. 

What I mean:
Hosting the server within vsc via root terminal:
[![image.png](https://i.postimg.cc/6qmTKypy/image.png)](https://postimg.cc/3023CrpT)

Curling my local ip via a normal terminal vs root terminal:
[![image.png](https://i.postimg.cc/1zQXyxsc/image.png)](https://postimg.cc/dh5w9x7L)
[![image.png](https://i.postimg.cc/NMNj85Tp/image.png)](https://postimg.cc/0MwvP5Vw)

As you can see we can connect via a root terminal but not a normal bash terminal. Yes I think there might be a config that could fix this and yes I don't mind just re-logging like said before. 
The reason I do it like this is so I can have a practical system wide proxy. Makes my life easier and I am also lazy.

**IF you want to reproduce this your self then go here: [https://github.com/0XC7R/Tornet-x-Proxychains](https://github.com/0XC7R/Tornet-x-Proxychains)**

# proxychains.conf
```
# proxychains.conf  VER 3.1
#
#        HTTP, SOCKS4, SOCKS5 tunneling proxifier with DNS.
#	

# The option below identifies how the ProxyList is treated.
# only one option should be uncommented at time,
# otherwise the last appearing option will be accepted
#
#dynamic_chain
#
# Dynamic - Each connection will be done via chained proxies
# all proxies chained in the order as they appear in the list
# at least one proxy must be online to play in chain
# (dead proxies are skipped)
# otherwise EINTR is returned to the app
#
strict_chain
#
# Strict - Each connection will be done via chained proxies
# all proxies chained in the order as they appear in the list
# all proxies must be online to play in chain
# otherwise EINTR is returned to the app
#
#random_chain
#
# Random - Each connection will be done via random proxy
# (or proxy chain, see  chain_len) from the list.
# this option is good to test your IDS :)

# Make sense only if random_chain
#chain_len = 2

# Quiet mode (no output from library)
#quiet_mode

# Proxy DNS requests - no leak for DNS data
proxy_dns 

# Some timeouts in milliseconds
tcp_read_time_out 15000
tcp_connect_time_out 8000

# ProxyList format
#       type  host  port [user pass]
#       (values separated by 'tab' or 'blank')
#
#
#        Examples:
#
#		socks5	127.0.0.1	9050		
#		http	192.168.89.3	8080	justu	hidden
#	 	socks4	192.168.1.49	1080
#	        http	192.168.39.93	8080	
#		
#
#       proxy types: http, socks4, socks5
#        ( auth types supported: "basic"-http  "user/pass"-socks )
#
[ProxyList]
socks4	127.0.0.1 9050
#socks5 127.0.0.1 9050
```

# /etc/profile
```# /etc/profile: system-wide .profile file for the Bourne shell (sh(1))
# and Bourne compatible shells (bash(1), ksh(1), ash(1), ...).

if [ "$(id -u)" -eq 0 ]; then
  PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
else
  PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
fi
export PATH

if [ "${PS1-}" ]; then
  if [ "${BASH-}" ] && [ "$BASH" != "/bin/sh" ]; then
    # The file bash.bashrc already sets the default PS1.
    # PS1='\h:\w\$ '
    if [ -f /etc/bash.bashrc ]; then
      . /etc/bash.bashrc
    fi
  else
    if [ "$(id -u)" -eq 0 ]; then
      PS1='# '
    else
      PS1='$ '
    fi
  fi
fi

if [ -d /etc/profile.d ]; then
  for i in $(run-parts --list --regex '^[a-zA-Z0-9_][a-zA-Z0-9._-]*\.sh$' /etc/profile.d); do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi

export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libproxychains.so.4
export PROXYCHAINS_CONF_FILE=/etc/proxychains.conf
```

**Comment by rofl0r** [comment]
check localnet directive in example config

**Comment by 0XC7R** [comment]
> check localnet directive in example config

Did not realize that thanks.
