### ISSUE TITLE
Quiet mode in config doesn't suppress all output

### ISSUE THREAD

**Issue by baileyparker** [rofl0r/proxychains-ng#59]
Just got up and running with proxychains. Such a useful tool! I've been doing a lot of manual work to proxy terminal stuff outside of a restrictive connection that I'm commonly behind, and this is definitely a huge timesaver! Thanks so much for reviving & maintaining this project!

I have a question (possible bug?) about the quiet mode setting.

I have my config file in my home directory and have uncommented the quiet mode line. It appears to suppress most output, however I still see:

    $ proxychains4 curl 'https://api.ipify.org?format=json'
    [proxychains] config file found: ~/.proxychains/proxychains.conf
    [proxychains] preloading /usr/local/Cellar/proxychains-ng/4.7/lib/libproxychains4.dylib

I've tried adding a `-s` flag, but that doesn't seem to be recognized. Is there anyway to suppress this output (or is quiet mode supposed to suppress it in the first place)?

I suspect the problem is that those two lines are outputted before the config is loaded (so maybe it might make sense to queue them for printing until the config is loaded so that they can be suppressed if there is a quiet mode flag in the config).

**Comment by baileyparker** [comment]
Digging through the source, I've found that the correct flag is `-q`. However, is there a way to suppress this output in config?

**Comment by baileyparker** [comment]
Further digging reveals that there is an environment variable `PROXYCHAINS_QUIET_MODE` that if set to `1` [should suppress output](https://github.com/rofl0r/proxychains-ng/blob/30495fde39f08348ad0f12145530b71865f0885d/src/libproxychains.c#L183-L185). However this doesn't appear to suppress the lines mentioned in my first post on this issue.

**Comment by rofl0r** [comment]
everything works as intended by passing -q to proxychains4 executable.

**Comment by OdinF13** [comment]
**You need to remove second line(echo)**

```bash
$ sudo sed '2d' -i `which proxychains`
```

**Comment by rofl0r** [comment]
> You need to remove second line(echo)
> $ sudo sed '2d' -i `which proxychains`

wtf are you talking about? proxychains-ng is not a shell script. anyway, this issue is resolved since 5 years. locking.
