### ISSUE TITLE
add uninstall target

### ISSUE THREAD

**Issue by sysfu** [rofl0r/proxychains-ng#67]
Would be nice to have an uninstall target to remove the software.

```
$ sudo gmake uninstall
gmake: *** No rule to make target 'uninstall'.  Stop.
```

**Comment by MuSamDu** [comment]
>proxychains-4.10$ sudo make uninstall
>make: *** No rule to make target 'uninstall'. Stop.   
   
**Same Here!!!**

**Comment by CzBiX** [comment]
Use `stow` to manage it.

**Comment by rofl0r** [comment]
yes. you can ```make install DESTDIR=foo``` and then you see exactly which files are being installed by looking into foo.
i'm not going to add code that deletes files from user's boxes - they can and will shoot themselves in the foot.
