### ISSUE TITLE
cannot git clone 

### ISSUE THREAD

**Issue by jk2K** [rofl0r/proxychains-ng#68]
➜  android  proxychains4 git clone https://github.com/izzyleung/ZhihuDailyPurify 
[proxychains] config file found: /Users/lee/.proxychains/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.10/lib/libproxychains4.dylib
[proxychains] DLL init: proxychains-ng 4.10
[proxychains] DLL init: proxychains-ng 4.10
Cloning into 'ZhihuDailyPurify'...
[proxychains] DLL init: proxychains-ng 4.10
[proxychains] Strict chain  ...  127.0.0.1:1080  ...  127.0.0.1:1080  ...  OK
fatal: unable to access 'https://github.com/izzyleung/ZhihuDailyPurify/': SOCKS5 read error occurred

**Comment by rofl0r** [comment]
are you sure your proxy works ?
also it seems that you specified your proxy twice in the config, which won't work

**Comment by jk2K** [comment]
my proxy can works
```
➜  query git:(master) ✗ proxychains4 curl www.google.com
[proxychains] config file found: /Users/lee/.proxychains/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.10/lib/libproxychains4.dylib
[proxychains] DLL init: proxychains-ng 4.10
[proxychains] Strict chain  ...  127.0.0.1:1080  ...  www.google.com:80  ...  OK
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://www.google.co.jp/?gfe_rd=cr&amp;ei=CyuTVeoQhovwBdXZgIAO">here</A>.
</BODY></HTML>
```

**Comment by ravomavain** [comment]
I think your git is already configured to use your proxy at 127.0.0.1:1080.
Run `git config -l` and `env` and look for any reference to proxy or the address 127.0.0.1:1080

**Comment by jk2K** [comment]
thanks, @ravomavain , you are right, my git is already configured to use proxy at 127.0.0.1:1080

**Comment by FrankFang** [comment]
Thanks for you  @ravomavain
