### ISSUE TITLE
Compilation error with Windows/Cygwin

### ISSUE THREAD

**Issue by nagromc** [rofl0r/proxychains-ng#69]
`proxychains-ng` won't compile for Windows/Cygwin.

Am I missing something?

Commit id: https://github.com/haad/proxychains/commit/ec404a9e6152224058891e525ed21478f46f54a2

What I did:
```
> ./configure --prefix=/usr --sysconfdir=/etc
> make
```

Here is the error log:
```
cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/libproxychains.o src/libproxychains.c
src/libproxychains.c:1:0: attention : -fPIC ignoré pour la cible (tout le code set indépendant de la position)
 /***************************************************************************
 ^
src/libproxychains.c: In function ‘load_sym’:
src/libproxychains.c:79:24: erreur: ‘RTLD_NEXT’ undeclared (first use in this function)
  void *funcptr = dlsym(RTLD_NEXT, symname);
                        ^
src/libproxychains.c:79:24: note: each undeclared identifier is reported only once for each function it appears in
src/libproxychains.c: Hors de toute fonction :
src/libproxychains.c:310:5: erreur: conflicting types for ‘connect’
 int connect(int sock, const struct sockaddr *addr, unsigned int len) {
     ^
In file included from /usr/include/netdb.h:67:0,
                 from src/libproxychains.c:27:
/usr/include/sys/socket.h:28:7: note: previous declaration of ‘connect’ was here
   int connect (int, const struct sockaddr *, socklen_t);
       ^
src/libproxychains.c:426:17: erreur: conflicting types for ‘gethostbyaddr’
 struct hostent *gethostbyaddr(const void *addr, socklen_t len, int type) {
                 ^
In file included from src/libproxychains.c:27:0:
/usr/include/netdb.h:217:17: note: previous declaration of ‘gethostbyaddr’ was here
 struct hostent *gethostbyaddr (const char *, int, int);
                 ^
Makefile:81 : la recette pour la cible « src/libproxychains.o » a échouée
make: *** [src/libproxychains.o] Erreur 1
```

**Comment by rofl0r** [comment]
you have a link to haad's repo which is a different version. are you using haad or this one ?
also please ```export LC_ALL=C``` before doing anything that gives localized error messages (i don't speak french)
as to your error it seems cygwin uses non-posix conforming headers and since RTLD_NEXT is not declared it probably means that cygwin does not implement the functionality needed  to hook function calls and as such the cygwin platform cannot be supported.

**Comment by nagromc** [comment]
Oops, wrong tab... but I do cloned rofl0r/proxychains-ng. Commit id: https://github.com/rofl0r/proxychains-ng/commit/9969dd3a227abe06c8f7c2f4c217607c344fb6bd

Here are the logs with `LC_ALL=C` for further reference:

    cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/libproxychains.o src/libproxychains.c
    src/libproxychains.c:1:0: warning: -fPIC ignored for target (all code is position independent)
     /***************************************************************************
     ^
    src/libproxychains.c: In function 'load_sym':
    src/libproxychains.c:79:24: error: 'RTLD_NEXT' undeclared (first use in this function)
      void *funcptr = dlsym(RTLD_NEXT, symname);
                            ^
    src/libproxychains.c:79:24: note: each undeclared identifier is reported only once for each function it appears in
    src/libproxychains.c: At top level:
    src/libproxychains.c:310:5: error: conflicting types for 'connect'
     int connect(int sock, const struct sockaddr *addr, unsigned int len) {
         ^
    In file included from /usr/include/netdb.h:67:0,
                     from src/libproxychains.c:27:
    /usr/include/sys/socket.h:28:7: note: previous declaration of 'connect' was here
       int connect (int, const struct sockaddr *, socklen_t);
           ^
    src/libproxychains.c:426:17: error: conflicting types for 'gethostbyaddr'
     struct hostent *gethostbyaddr(const void *addr, socklen_t len, int type) {
                     ^
    In file included from src/libproxychains.c:27:0:
    /usr/include/netdb.h:217:17: note: previous declaration of 'gethostbyaddr' was here
     struct hostent *gethostbyaddr (const char *, int, int);
                     ^
    Makefile:81: recipe for target 'src/libproxychains.o' failed
    make: *** [src/libproxychains.o] Error 1

Well, I'm not really into C stuff. But, at the moment, I understand there is no way to make `proxychains-ng` compile easily on Cygwin.

Thanks anyway!
