### ISSUE TITLE
proxydns setting prevents the localnet resolving request by name...

### ISSUE THREAD

**Issue by GrantStreetGroup** [rofl0r/proxychains-ng#72]
There is an issue where connects to localnet IP that was made by name, do not match the localnet IP as the proxydns coverts them to 244.*.*.* instead of the real IP.  

For example: Say some.local.host  is 192.168.100.10

With proxydns on:
localnet 192.168.100.0/255.255.255.0 should allow request to some.local.host to bypass the proxy.
however request by name fail to bypass. Only requests to 192.168.100.10 work.

either localnet should be by name or proxydns should 'test' the named connection to see if it's a localnet.

**Comment by rofl0r** [comment]
which mechanism do you use to map some.local.host to 192.168.100.10 ?

**Comment by GrantStreetGroup** [comment]
Sorry, missed your reply.   

Here is a specific example, I attempt to telnet to our internal redis host `intrds01-dev1` which is at `192.168.24.166`. This is running inside a docker container.

```
[root@b759259e1974 hubot]# proxychains4 -f proxy/proxychains.conf telnet intrds01-dev1 6379
[proxychains] config file found: proxy/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.10-git-10-g2237749
Trying 224.0.0.1...
[proxychains] Strict chain  ...  192.168.118.51:3128  ...  intrds01-dev1:6379 <--denied
telnet: connect to address 224.0.0.1: Connection refused
```

As you can see telnet is given the 244.* proxied IP when proxydns is enabled. This  prevent the localnet setup to not catch the request. It ends up at the proxy where it's blocked.

If I telnet to the IP address it works:

```
[root@b759259e1974 hubot]# proxychains4 -f proxy/proxychains.conf telnet 192.168.26.166 6379
[proxychains] config file found: proxy/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.10-git-10-g2237749
Trying 192.168.26.166...
Connected to 192.168.26.166.
Escape character is '^]'.
```

Some how the localnet rule needs to check against the real IP for the host not the proxified IP.

**Comment by GrantStreetGroup** [comment]
#50  is the different take on the same issue

**Comment by rofl0r** [comment]
i understand your problem, but not which name mapping mechanism you're using. is the name mapping done via an internal DNS server or a hosts file ?

**Comment by rofl0r** [comment]
@GrantStreetGroup ping

**Comment by GrantStreetGroup** [comment]
internal DNS server..

**Comment by rofl0r** [comment]
since remote_dns does the DNS lookup on the proxy, this can only work if the proxy is configured to use your companies' DNS server.

**Comment by GrantStreetGroup** [comment]
This has nothing to do with which DNS we are using or not.   

proxydns feature conflicts with the localnet feature making mutual exclusive.

**Comment by rofl0r** [comment]
well if you have an idea how this could work as you expect, let me know.

**Comment by GrantStreetGroup** [comment]
Also without proxydns setting proxychains4 passes on the connection request to the defined proxy by IP not name, which does not work for proxy with name based rules.

One way to resolve this is:
When a request for a named host is made, proxychains-ng should

* Attempt to determine the true IP of the request name.
* If 'proxydns' setting in true, return 'fake' IP from defined range
* Check 'true IP' (if available) against 'localnet' setting(s) to determine whether to bypass proxy
* Submit connection request to proxy by name (Add an option to define whether IP or Name is sent)
