### ISSUE TITLE
Proxychains error, wont run

### ISSUE THREAD

**Issue by NickWinston123** [rofl0r/proxychains-ng#73]
Hey,
When ever I try to run proxy chains with the configuration file configured right I get this error which causes it to fail to run.
```
root@Nicks-Kali:~/Desktop# proxychains iceweasel
ProxyChains-3.1 (http://proxychains.sf.net)

(process:5152): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
```

Any help would be appreciated. Thank you.

**Comment by rofl0r** [comment]
proxychains 3.1 is not supported anymore- use the latest release ( http://sourceforge.net/projects/proxychains-ng/files ) or the current git version from this repo
