### ISSUE TITLE
random_chain always picks last proxy from list

### ISSUE THREAD

**Issue by asconix** [rofl0r/proxychains-ng#75]
random_chain doesn't return a random proxy but always the same one on Mac OS X 10.10 (installed via homebrew). This my config:

    random_chain
    chain_len = 1
    tcp_read_time_out 15000
    tcp_connect_time_out 8000
    localnet 127.0.0.0/255.0.0.0

    [ProxyList]
    socks5 117.110.100.1 5080 userX mySecretPW
    socks5 117.110.100.2 5080 userX mySecretPW
    socks5 117.110.100.3 5080 userX mySecretPW
    socks5 117.110.100.4 5080 userX mySecretPW

A simple call like this:

    proxychains4 -f proxychains.conf curl http://ifconfig.co/

returns me _always_:

    [proxychains] config file found: proxychains.conf
    [proxychains] preloading /usr/local/Cellar/proxychains-ng/4.10/lib/libproxychains4.dylib
    [proxychains] DLL init: proxychains-ng 4.10
    [proxychains] Random chain  ...  117.110.100.4:5080  ...  188.113.88.193:80  ...  OK
    117.110.100.4

When I set chain_len = 2 the cascading starts always with the same proxy 117.110.110.4 (so no random proxy for first selection) and picks up a random proxy for the second step.

But how to get a random proxy with chain_len = 1 ?

**Comment by rofl0r** [comment]
works for me on linux with wget. maybe mac's rand() is broken ?
you could try if you experience the issue with other programs (such as wget).

**Comment by asconix** [comment]
hi rofl0r et al.,

i have cloned the repo on a brand new OS X installation. random_chain is definitely not working on OS X. I tried curl, wget, firefox, safari. random_chain seems to pick always the last element of the list. no issues with same code on linux

**Comment by ravomavain** [comment]
On [src/core.c#L467](https://github.com/rofl0r/proxychains-ng/blob/master/src/core.c#L467) we have:
```i = 0 + (unsigned int) (proxy_count * 1.0 * rand() / (RAND_MAX + 1.0));```
Maybe there's some overflow or something during type conversion. Why not simply using `i = rand()%proxy_count` ?

**Comment by rofl0r** [comment]
yeah that code looks suspicious (hideously complex).
@asconix can you try if the change suggested by @ravomavain fixes the issue.

**Comment by rofl0r** [comment]
@asconix ping

**Comment by rofl0r** [comment]
can anyone using a mac show up and test if random chain is broken and if @ravomavain 's change fixes it?
@ravomavain if you prepare a PR (and test it a bit) i'll probably merge it

**Comment by jaytaylor** [comment]
@rofl0r I just tested out @ravomavain's fix and it works for me.  I'm testing on Linux next to ensure it still works.  If all is well I'll open the PR.

**Comment by jaytaylor** [comment]
https://github.com/rofl0r/proxychains-ng/pull/143

**Comment by rofl0r** [comment]
@jaytaylor thanks for testing. however what i would like to know is not only if the fix works but also if random chain is really broken on mac (without the fix).

**Comment by rofl0r** [comment]
(for testing you could probably use 127.0.0.1, 127.0.0.2, etc)

**Comment by rofl0r** [comment]
@jaytaylor did you find some time to test if the random chain feature is broken without your patch ?

**Comment by jaytaylor** [comment]
Yes, it is definitely broken without the patch.
