### ISSUE TITLE
[Feature Request] support PAC URL auto proxy

### ISSUE THREAD

**Issue by stardiviner** [rofl0r/proxychains-ng#76]
Currently, many proxy service only give out PAC URL as proxy, and it is very popular now. I hope proxychains-ng can support it.

**Comment by rofl0r** [comment]
sorry, but since parsing of PAC files requires a javascript interpreter, this is way off the scope what proxychains wants to achieve. however i'm sure there are tools out there that parse the file so you can make them dump the proxy url and then use it in proxychains config.

**Comment by stardiviner** [comment]
@rofl0r If you know that method, please add it into README, or wiki. let people know how to do that, I really like this easy way `$ proxychains command`.
At last, thanks for your project.

**Comment by rofl0r** [comment]
this program here seems to do the job: https://github.com/pacparser/pacparser

**Comment by stardiviner** [comment]
That's great, I will use it with proxychains. thanks.

**Comment by jmiserez** [comment]
@stardiviner Did you ever integrate pacparser into proxychains?

@rofl0r PAC files may specify different proxies for different URLs, i.e. it's a dynamic lookup. Parsing a complex PAC file will not necessarily result in a single proxy server that can be added to the proxychains config. Pacparser would need to be integrated within proxychains and lookup the correct proxy server for each and every request from the provided PAC file. Just FYI.

**Comment by stardiviner** [comment]
@jmiserez No, I have not work on it. I have other work to do. So have no time on this for now.

**Comment by ihipop** [comment]
@rofl0r Meet libproxy https://github.com/libproxy/libproxy

libproxy offers the following features:
- support for all major platforms: Windows, Mac and Linux/UNIX (see upcoming 0.4 release)
- extremely small core footprint
- no external dependencies within libproxy core (libproxy plugins may have dependencies)
- only 3 functions in the stable-ish external API (1.0 will offer full stability)
- dynamic adjustment to changing network topology
- a standard way of dealing with proxy settings across all scenarios
- a sublime sense of joy and accomplishment

**Comment by rofl0r** [comment]
@ihipop Meet the door

the requirements of a preloaded hook library are unique but you are free to try to implement your own proxychains on libwhatever

**Comment by ppKrauss** [comment]
Please, reopen, all people need and Linux are lossing opportunities without it.
