### ISSUE TITLE
Operation timed out

### ISSUE THREAD

**Issue by Lilacs** [rofl0r/proxychains-ng#82]
I just read this page to install.
<https://github.com/shadowsocks/shadowsocks/wiki/Using-Shadowsocks-with-Command-Line-Tools>

    ➜  ~  proxychains4 curl https://www.twitter.com/
    [proxychains] config file found: /usr/local/Cellar/proxychains-ng/4.10/etc/proxychains.conf
    [proxychains] preloading /usr/local/Cellar/proxychains-ng/4.10/lib/libproxychains4.dylib
    curl: (7) Failed to connect to www.twitter.com port 443: Operation timed out

I system verison is OSX 10.11 Beta 7

**Comment by rofl0r** [comment]
remove the line "quiet_mode" from your config and try again

see also this: https://github.com/rofl0r/proxychains-ng/issues/78

**Comment by Lilacs** [comment]
I remove the "quiet_mode",not useful,but in the Recovery Mode let csrutil disable, the problem disappears.
Thanks!
