### ISSUE TITLE
Curl ignores proxychains on OSX 10.11

### ISSUE THREAD

**Issue by vonnyfly** [rofl0r/proxychains-ng#84]
Hi Sir,

I have tested in two installing way.
One is from git code, the other way is from brew.
They are not working both.

Example:
```
$ proxychains4 curl google.com                                                                                         35 ↵
[proxychains] config file found: /Users/vonnyfly/.proxychains/proxychains.conf
[proxychains] preloading /usr/local/lib/libproxychains4.dylib

curl: (52) Empty reply from server
 $ curl google.com --socks5-hostname 192.168.1.112:1081                                                                 52 ↵
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>

$ cat ~/.proxychains/proxychains.conf
socks5 192.168.1.112 1081
```

**Comment by vonnyfly** [comment]
I have known the root cause.
OSX10.11 add a rootless mode. Root account doesn't have permission to modify /usr/bin files. So proxychains couldn't works on curl which is located in /usr/bin.

**Comment by vonnyfly** [comment]
You could close this issue. But I think keep it here maybe help users who uses OSX10.11.

**Comment by rofl0r** [comment]
yes, this is due to https://github.com/rofl0r/proxychains-ng/issues/78

**Comment by magicians** [comment]
☁  ~  proxychains4 curl ip.cn
[proxychains] config file found: /Users/meilunzhi/.proxychains/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.10/lib/libproxychains4.dylib
当前 IP：182.18.110.217 来自：北京市 shadowocks?

**Comment by haobingwang** [comment]
~ ⮀ proxychains4 curl ip.cn
[proxychains] config file found: /Users/jack/.proxychains/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib
当前 IP：101.81.227.28 来自：上海市 电信

**Comment by yehgdotnet** [comment]
```
cp /usr/bin/curl .
proxychains4 ./curl yourhost
```

**Comment by james-see** [comment]
> ```
> cp /usr/bin/curl .
> proxychains4 ./curl yourhost
> ```

This does not work for me. Still gets ignored. wget works fine.

**Comment by james-see** [comment]
It works after installing curl via homebrew and using that version.

```❯ proxychains4 curl https://ipinfo.io/ip
[proxychains] config file found: /opt/homebrew/etc/proxychains.conf
[proxychains] preloading /opt/homebrew/Cellar/proxychains-ng/4.16/lib/libproxychains4.dylib
[proxychains] DLL init: proxychains-ng 4.16
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  127.0.0.1:9050 <--denied
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  ipinfo.io:443  ...  OK
185.220.101.18```

**Comment by roboticsexpert** [comment]
install curl with brew and add it to your bash or zsh rc with this command for example (for zsh): 

echo 'export PATH="/opt/homebrew/opt/curl/bin:$PATH"' >> ~/.zshrc

after that open new terminal and make sure if you run `which curl` you will get `/opt/homebrew/opt/curl/bin/curl`

after that proxychains will works as well
