### ISSUE TITLE
socket error when http request

### ISSUE THREAD

**Issue by toniss** [rofl0r/proxychains-ng#87]
proxychains works fine when the request is https but gives me an error if the request is http. This is my config:

strict_chain
chain_len = 1
#quiet_mode
proxy_dns
remote_dns_subnet 127
remote_dns_subnet 10
tcp_read_time_out 15000
tcp_connect_time_out 8000
localnet 127.0.0.0/255.0.0.0
localnet 10.0.0.0/255.0.0.0
[ProxyList]
http    127.0.0.1        8082

and this is an output example using iceweasel browser

[proxychains] Strict chain  ...  127.0.0.1:8080  ...  google.com:80 <--socket error or timeout!
[proxychains] Strict chain  ...  127.0.0.1:8080  ...  google.com:80 <--socket error or timeout!
[proxychains] Strict chain  ...  127.0.0.1:8080  ...  google.com:80 <--socket error or timeout!
[proxychains] Strict chain  ...  127.0.0.1:8080  ...  google.com:80 <--socket error or timeout!
[proxychains] Strict chain  ...  127.0.0.1:8080  ...  google.com:80 <--socket error or timeout!
[proxychains] Strict chain  ...  127.0.0.1:8080  ...  google.com:80 <--socket error or timeout!
 

I tried everything that I found on google, so far nothing work. Help!

**Comment by rofl0r** [comment]
your proxy seems to be a local application. maybe it's misconfigured ?

**Comment by dkreider** [comment]
Your config file shows " http 127.0.0.1 8082 " and the output is 127.0.01:8080. 

Why would this be if proxychains is configured to use port 8082? Port redirects?

**Comment by rofl0r** [comment]
oh btw you should put ```remote_dns_subnet 224``` in your config and remove the 2 entries you have there
they overlap with your localnet *and* with the address of your proxy so thats a seriously wrong setup.

**Comment by toniss** [comment]
the problem persist, these are two output examples:

#proxychains4 nc google.com 80
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/local/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.10
[proxychains] Strict chain  ...  127.0.0.1:8082  ...  google.com:80 <--socket error or timeout!
google.com [224.0.0.1] 80 (http) : Connection refused

#proxychains4 nc google.com 443
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/local/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.10
[proxychains] Strict chain  ...  127.0.0.1:8082  ...  google.com:443  ...  OK
^C 
the conf is this:

chain_len = 1
#dynamic_chain
strict_chain
#quiet_mode
proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000
localnet 10.0.0.0/255.0.0.0
[ProxyList]
http    127.0.0.1       8082

**Comment by rofl0r** [comment]
in that case it's your proxy thats misconfigured...

**Comment by toniss** [comment]
The problem was the proxy only accept method connect at port 443.
