### ISSUE TITLE
add auto-complete feature

### ISSUE THREAD

**Issue by DarKnight24** [rofl0r/proxychains-ng#88]
The auto-complete feature will be great and does not need much working. 
I have created a file named `proxychains4` in `/etc/bash_completion.d/` and wrote `complete -F _command proxychains4` in it. 
I think it will require a change in make file just like `install-config` copies `proxychains.conf`.

Or any guide to me so that I can work on the enhancement and contribute.

**Comment by rofl0r** [comment]
which option of proxychains would need completion in your opinion ?

**Comment by DarKnight--** [comment]
The bash completion feature in proxychains. At present I need to type a complete command for ex. `proxychains firefox` or `proxychains youtube-dl`. If we will have bash completion it will be a lot easier.

**Comment by JayGoldberg** [comment]
+1, we just want binary path completion. `pcw <tab>` will not tab-complete executables, only the pwd's files/dirs.

**Comment by rofl0r** [comment]
patches welcome

**Comment by dragon788** [comment]
This could be slightly tricky or rather easy depending on how complete/safe the implementation needs to be.

Essentially what you need to do is `pass through` the Tab completion to the binary that is the first argument once one is selected.

So the first `Tab` in `proxychains fire<Tab>` would search for executable binaries, then once it has `proxychains firefox <Tab>` would use `complete -F _command firefox` to find the valid completions for that one.

Here are some articles I've researched a bit on doing this or something similar for `alias` commands which is rather closely related.
https://superuser.com/questions/436314/how-can-i-get-bash-to-perform-tab-completion-for-my-aliases/437508#437508
https://github.com/cykerway/complete-alias
https://brbsix.github.io/2015/11/29/accessing-tab-completion-programmatically-in-bash/

**Comment by rofl0r** [comment]
@dragon788 thanks for your research. as it turns out that the autocomplete is a shell feature, pull requests should be filed against the respective shell repositories.
