### ISSUE TITLE
proxychians+nmap, the target was changed to 224.0.0.1

### ISSUE THREAD

**Issue by h4wkooo** [rofl0r/proxychains-ng#90]
When I used nmap with proxychains, it showed that the target was changed to 224.0.0.1:

Nmap scan report for mysite (224.0.0.1)
Host is up (0.00036s latency).
rDNS record for 224.0.0.1: all-systems.mcast.net

But when proxychains + curl,it works well.
Is it the problem of nmap?

**Comment by rofl0r** [comment]
when you use remote_dns, the dns name will be translated to an ip in the remote dns subnet.
use ip addresses rather than dns names and it will work as expected.
